<?php

# @autogenerated
declare(strict_types=1);

namespace Civi\Lughauth\Features\Access\TrustedClient\Infrastructure\Driver;

use Override;
use Slim\Routing\RouteCollectorProxy;
use Civi\Lughauth\Features\Access\TrustedClient\Infrastructure\Driver\Rest\TrustedClientAllowController;
use Civi\Lughauth\Features\Access\TrustedClient\Infrastructure\Driver\Rest\TrustedClientListController;
use Civi\Lughauth\Features\Access\TrustedClient\Infrastructure\Driver\Rest\TrustedClientCreateController;
use Civi\Lughauth\Features\Access\TrustedClient\Infrastructure\Driver\Rest\TrustedClientRetrieveController;
use Civi\Lughauth\Features\Access\TrustedClient\Infrastructure\Driver\Rest\TrustedClientUpdateController;
use Civi\Lughauth\Features\Access\TrustedClient\Infrastructure\Driver\Rest\TrustedClientDeleteController;
use Civi\Lughauth\Features\Access\TrustedClient\Infrastructure\Driver\Rest\TrustedClientEnableController;
use Civi\Lughauth\Features\Access\TrustedClient\Infrastructure\Driver\Rest\TrustedClientDisableController;
use Civi\Lughauth\Shared\Infrastructure\MicroPlugin;
use Civi\Lughauth\Shared\Event\EventListenersRegistrarInterface;
use Civi\Lughauth\Features\Access\TrustedClient\Application\Policy\Allow\Create\IsAutenticatedCreateAllow;
use Civi\Lughauth\Features\Access\TrustedClient\Application\Policy\Allow\Update\IsAutenticatedUpdateAllow;
use Civi\Lughauth\Features\Access\TrustedClient\Application\Policy\Allow\Retrieve\IsAutenticatedRetrieveAllow;
use Civi\Lughauth\Features\Access\TrustedClient\Application\Policy\Allow\List\IsAutenticatedListAllow;
use Civi\Lughauth\Features\Access\TrustedClient\Application\Policy\Allow\Delete\IsAutenticatedDeleteAllow;
use Civi\Lughauth\Features\Access\TrustedClient\Application\Policy\Allow\Enable\IsAutenticatedEnableAllow;
use Civi\Lughauth\Features\Access\TrustedClient\Application\Policy\Allow\Disable\IsAutenticatedDisableAllow;
use Civi\Lughauth\Features\Access\TrustedClient\Application\Usecase\Create\TrustedClientCreateAllowDecision;
use Civi\Lughauth\Features\Access\TrustedClient\Application\Usecase\Update\TrustedClientUpdateAllowDecision;
use Civi\Lughauth\Features\Access\TrustedClient\Application\Usecase\Retrieve\TrustedClientRetrieveAllowDecision;
use Civi\Lughauth\Features\Access\TrustedClient\Application\Usecase\List\TrustedClientListAllowDecision;
use Civi\Lughauth\Features\Access\TrustedClient\Application\Usecase\Delete\TrustedClientDeleteAllowDecision;
use Civi\Lughauth\Features\Access\TrustedClient\Application\Usecase\Enable\TrustedClientEnableAllowDecision;
use Civi\Lughauth\Features\Access\TrustedClient\Application\Usecase\Disable\TrustedClientDisableAllowDecision;

class TrustedClientPlugin extends MicroPlugin
{
    #[Override]
    public function registerRoutes(RouteCollectorProxy $app)
    {
        $app->group('/api/access/trusted-clients', [$this, 'setRoutesForTrustedClient']);
        $app->group('/api/me/acl/access/trusted-clients', [$this, 'setRoutesForTrustedClientAcl']);
    }
    #[Override]
    public function registerEvents(EventListenersRegistrarInterface $bus)
    {
        $bus->registerListener(TrustedClientCreateAllowDecision::class, IsAutenticatedCreateAllow::class);
        $bus->registerListener(TrustedClientUpdateAllowDecision::class, IsAutenticatedUpdateAllow::class);
        $bus->registerListener(TrustedClientRetrieveAllowDecision::class, IsAutenticatedRetrieveAllow::class);
        $bus->registerListener(TrustedClientListAllowDecision::class, IsAutenticatedListAllow::class);
        $bus->registerListener(TrustedClientDeleteAllowDecision::class, IsAutenticatedDeleteAllow::class);
        $bus->registerListener(TrustedClientEnableAllowDecision::class, IsAutenticatedEnableAllow::class);
        $bus->registerListener(TrustedClientDisableAllowDecision::class, IsAutenticatedDisableAllow::class);
    }
    public function setRoutesForTrustedClientAcl(RouteCollectorProxy $trustedClientGroup)
    {
        $trustedClientGroup->get('', [TrustedClientAllowController::class, 'genericAllow']);
        $trustedClientGroup->get('/{uid}', [TrustedClientAllowController::class, 'contextualAllow']);
    }
    public function setRoutesForTrustedClient(RouteCollectorProxy $trustedClientGroup)
    {
        $trustedClientGroup->get('', [TrustedClientListController::class, 'list']);
        $trustedClientGroup->post('', [TrustedClientCreateController::class, 'create']);
        $trustedClientGroup->get('/{uid}', [TrustedClientRetrieveController::class, 'retrieve']);
        $trustedClientGroup->put('/{uid}', [TrustedClientUpdateController::class, 'update']);
        $trustedClientGroup->delete('/{uid}', [TrustedClientDeleteController::class, 'delete']);
        $trustedClientGroup->delete('', [TrustedClientDeleteController::class, 'deleteAllForQuery']);
        $trustedClientGroup->get('/~/delete-status/{uid}', [TrustedClientDeleteController::class, 'checkDeleteAllForQueryStatus']);
        $trustedClientGroup->patch('/~/enable', [TrustedClientEnableController::class, 'enableAllForQuery']);
        $trustedClientGroup->patch('/{uid}/enable', [TrustedClientEnableController::class, 'enable']);
        $trustedClientGroup->get('/~/enable-status/{uid}', [TrustedClientEnableController::class, 'checkEnableAllForQueryStatus']);
        $trustedClientGroup->patch('/~/disable', [TrustedClientDisableController::class, 'disableAllForQuery']);
        $trustedClientGroup->patch('/{uid}/disable', [TrustedClientDisableController::class, 'disable']);
        $trustedClientGroup->get('/~/disable-status/{uid}', [TrustedClientDisableController::class, 'checkDisableAllForQueryStatus']);
    }
}
