<?php

/* @autogenerated */
declare(strict_types=1);

namespace Civi\Lughauth\Features\Document\ThemeVersion\Application\Policy\Allow\Update;

use Throwable;
use Civi\Lughauth\Features\Document\ThemeVersion\Application\Usecase\Update\ThemeVersionUpdateAllowDecision;
use Civi\Lughauth\Shared\Context;
use Civi\Lughauth\Shared\Observability\LoggerAwareTrait;
use Civi\Lughauth\Shared\Observability\TracerAwareTrait;

class IsAuthenticatedUpdateAllow
{
    use LoggerAwareTrait;
    use TracerAwareTrait;

    public function __construct(private readonly Context $context)
    {
    }
    public function __invoke(ThemeVersionUpdateAllowDecision $proposal): ThemeVersionUpdateAllowDecision
    {
        $this->logDebug("Check IsAuthenticatedUpdateAllow Theme version");
        $span = $this->startSpan("Check IsAuthenticatedUpdateAllow Theme version");
        try {
            $userContext = $this->context->getIdentity();
            if ($proposal->isAllowed()) {
                if ($userContext->anonymous) {
                    $proposal->deny('Disabled if not IsAuthenticatedUpdate');
                }
            }
            return $proposal;
        } catch (Throwable $ex) {
            $span->recordException($ex);
            throw $ex;
        } finally {
            $span->end();
        }
    }
}
