<?php

/* @autogenerated */
declare(strict_types=1);

use PHPUnit\Framework\TestCase;
use Civi\Lughauth\Shared\Exception\ConstraintException;
use Civi\Lughauth\Shared\Value\Validation\ConstraintFailList;
use Civi\Lughauth\Features\Access\TrustedClient\Domain\ValueObject\TrustedClientPolicyUriVO;

final class TrustedClientPolicyUriVOUnitTest extends TestCase
{
    public function test_asignation_keep_value(): void
    {
        $value = 'one';
        $ref = TrustedClientPolicyUriVO::from($value);
        $this->assertEquals('one', $ref->value());
        $other = TrustedClientPolicyUriVO::tryFrom($ref, new ConstraintFailList());
        $this->assertSame($other, $ref);
        $more = TrustedClientPolicyUriVO::from($ref);
        $this->assertSame($more, $ref);
    }
    public function test_asignation_invalid_type(): void
    {
        $errors = new ConstraintFailList();
        $other = TrustedClientPolicyUriVO::tryFrom(1, $errors);
        $this->assertNull($other);
        $this->assertTrue($errors->hasErrors());
    }
    public function test_optimist_asignation_invalid_type(): void
    {
        $this->expectException(ConstraintException::class);
        $method = new ReflectionMethod(TrustedClientPolicyUriVO::class, 'fromUnsafe');
        $method->invoke(null, [11, "bad"]);
    }
    public function test_equals(): void
    {
        $one = TrustedClientPolicyUriVO::from('one');
        $same = TrustedClientPolicyUriVO::from('one');
        $other = TrustedClientPolicyUriVO::from('other');
        $withEmpty = $one->equals(null);
        $withSame = $one->equals($same);
        $withOther = $one->equals($other);

        $this->assertFalse($withEmpty);
        $this->assertTrue($withSame);
        $this->assertFalse($withOther);
    }
    public function test_empty(): void
    {
        $ref = TrustedClientPolicyUriVO::empty();
        $this->assertNull($ref->value());
    }
    public function test_try_from_empty(): void
    {
        $ref = TrustedClientPolicyUriVO::tryFrom(null, new ConstraintFailList());
        $this->assertNull($ref->value());
    }
    public function test_exception_on_wrong_value_1(): void
    {
        $this->expectException(ConstraintException::class);
        TrustedClientPolicyUriVO::from('Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus in consectetur purus, sit amet rutrum mi. Vestibulum finibus velit ac ligula feugiat, fermentum mattis justo pretium. Nullam blandit nibh nec tortor ultricies, sit amet pretium tellus ullamcorper. Nulla eu bibendum quam, sed vestibulum est. Nunc vitae imperdiet turpis, vel maximus massa. Mauris vel egestas odio. Sed malesuada a lorem non rhoncus. In sagittis scelerisque risus nec consectetur. In est neque, efficitur ut blandit ut, accumsan vitae sem.');
    }
}
