<?php

/* @autogenerated */
declare(strict_types=1);

namespace Civi\Lughauth\Features\Document\SnippetVersion\Domain\ValueObject;

use Civi\Lughauth\Shared\Value\Validation\ConstraintFailList;
use Civi\Lughauth\Shared\Value\Validation\ConstraintFail;
use Civi\Lughauth\Shared\Value\Validation\Rule\Length;

class SnippetVersionLocaleVO
{
    public static function empty(): SnippetVersionLocaleVO
    {
        return new SnippetVersionLocaleVO(null);
    }
    public static function from(SnippetVersionLocaleVO|string|null $value): SnippetVersionLocaleVO
    {
        return self::fromUnsafe($value);
    }
    public static function tryFrom(mixed $value, ConstraintFailList $list): ?SnippetVersionLocaleVO
    {
        if ($value instanceof SnippetVersionLocaleVO) {
            // If is a ValueObject, its already validated... nothing to append
            return $value;
        } elseif (!$value) {
            return new SnippetVersionLocaleVO($value);
        } elseif (is_string($value)) {
            // If is a ValueObject, we need to append all the errors for the context
            $valid = true;
            foreach (self::rules() as $rule) {
                if ($fail = $rule->check($value)) {
                    $list->add(ConstraintFail::fromRuleFail('locale', $fail));
                    $valid = false;
                }
            }
            return $valid ? new SnippetVersionLocaleVO($value) : null;
        } else {
            $list->add(new ConstraintFail('wrong_type', ['locale'], [$value], ['string']));
            return null;
        }
    }
    public static function rules(): array
    {
        return [
          new Length(min: null, max: 250),
        ];
    }
    private static function fromUnsafe(mixed $value): SnippetVersionLocaleVO
    {
        if ($value instanceof SnippetVersionLocaleVO) {
            // If is a ValueObject, its already validated
            return $value;
        } else {
            // If is not a ValueObject, validation is need and exception throw
            $errorsList = new ConstraintFailList();
            $candidate = self::tryFrom($value, $errorsList);
            if ($errorsList->hasErrors()) {
                throw $errorsList->asConstraintException();
            }
            \assert($candidate instanceof SnippetVersionLocaleVO);
            return $candidate;
        }
    }
    /**
     * private constructor to avoid build a value without all the rule validations.
     */
    private function __construct(
        private readonly ?string $locale
    ) {
    }
    public function value(): ?string
    {
        return $this->locale;
    }
    public function equals(?SnippetVersionLocaleVO $other): bool
    {
        return $this->value() == $other?->value();
    }
}
