<?php

/* @autogenerated */
declare(strict_types=1);

use PHPUnit\Framework\TestCase;
use Civi\Lughauth\Shared\Exception\ConstraintException;
use Civi\Lughauth\Shared\Value\Validation\ConstraintFailList;
use Civi\Lughauth\Features\Access\UserInvitation\Domain\ValueObject\UserInvitationStatusVO;
use Civi\Lughauth\Features\Access\UserInvitation\Domain\UserInvitationStatusOptions;

final class UserInvitationStatusVOUnitTest extends TestCase
{
    public function test_asignation_keep_value(): void
    {
        $value = UserInvitationStatusOptions::PENDING;
        $ref = UserInvitationStatusVO::from($value);
        $this->assertEquals(UserInvitationStatusOptions::PENDING, $ref->value());
        $other = UserInvitationStatusVO::tryFrom($ref, new ConstraintFailList());
        $this->assertSame($other, $ref);
        $more = UserInvitationStatusVO::from($ref);
        $this->assertSame($more, $ref);
    }
    public function test_asignation_invalid_type(): void
    {
        $errors = new ConstraintFailList();
        $other = UserInvitationStatusVO::tryFrom('1', $errors);
        $this->assertNull($other);
        $this->assertTrue($errors->hasErrors());
    }
    public function test_optimist_asignation_invalid_type(): void
    {
        $this->expectException(ConstraintException::class);
        $method = new ReflectionMethod(UserInvitationStatusVO::class, 'fromUnsafe');
        $method->invoke(null, [11, "bad"]);
    }
    public function test_equals(): void
    {
        $one = UserInvitationStatusVO::from(UserInvitationStatusOptions::PENDING);
        $same = UserInvitationStatusVO::from(UserInvitationStatusOptions::PENDING);
        $other = UserInvitationStatusVO::from(UserInvitationStatusOptions::ACCEPTED);
        $withEmpty = $one->equals(null);
        $withSame = $one->equals($same);
        $withOther = $one->equals($other);

        $this->assertFalse($withEmpty);
        $this->assertTrue($withSame);
        $this->assertFalse($withOther);
    }
    public function test_empty(): void
    {
        $ref = UserInvitationStatusVO::empty();
        $this->assertNull($ref->value());
    }
    public function test_try_from_empty(): void
    {
        $ref = UserInvitationStatusVO::tryFrom(null, new ConstraintFailList());
        $this->assertNull($ref->value());
    }
}
