<?php

/* @autogenerated */
declare(strict_types=1);

use PHPUnit\Framework\TestCase;
use PHPUnit\Framework\Attributes\AllowMockObjectsWithoutExpectations;
use DI\ContainerBuilder;
use Slim\Psr7\Response;
use Slim\Psr7\Factory\ServerRequestFactory;
use Psr\Http\Message\ResponseInterface;
use Civi\Lughauth\Shared\AppConfig;
use Civi\Lughauth\Shared\Context;
use Civi\Lughauth\Features\OAuth\Client\Domain\ClientData;
use Civi\Lughauth\Features\OAuth\Authentication\Domain\StepName;
use Civi\Lughauth\Features\OAuth\Authentication\Domain\StepResult;
use Civi\Lughauth\Features\OAuth\Authentication\Domain\ChallengesState;
use Civi\Lughauth\Features\OAuth\Authentication\Application\AuthenticateUser;
use Civi\Lughauth\Features\OAuth\Authentication\Application\SessionManager;
use Civi\Lughauth\Features\OAuth\Authentication\Infrastructure\Driver\Html\OidcStepRouter;
use Civi\Lughauth\Features\OAuth\Authentication\Infrastructure\Driver\Html\AuthorizeHtml;
use Civi\Lughauth\Features\OAuth\Authentication\Infrastructure\Driver\Html\Forms\TermsAndGdprConsentForm;
use Civi\Lughauth\Features\OAuth\Authentication\Infrastructure\Driver\Html\Forms\ScopeConsentForm;
use Civi\Lughauth\Features\OAuth\Authentication\Infrastructure\Driver\Html\Forms\DelegateForm;
use Civi\Lughauth\Features\OAuth\Authentication\Infrastructure\Driver\Html\Forms\LoginForm;
use Civi\Lughauth\Features\OAuth\Authentication\Infrastructure\Driver\Html\Forms\NewMfaForm;
use Civi\Lughauth\Features\OAuth\Authentication\Infrastructure\Driver\Html\Forms\NewPassForm;
use Civi\Lughauth\Features\OAuth\Authentication\Infrastructure\Driver\Html\Forms\RecoverPassForm;
use Civi\Lughauth\Features\OAuth\Authentication\Infrastructure\Driver\Html\Forms\UseMfaForm;
use Civi\Lughauth\Features\OAuth\Authentication\Infrastructure\Driver\Html\Forms\RegisterUserForm;
use Civi\Lughauth\Features\OAuth\Authentication\Infrastructure\Driver\Html\Forms\WebAuthnLoginForm;
use Civi\Lughauth\Features\OAuth\Authentication\Infrastructure\Driver\Html\Forms\MagicLinkLoginForm;
use Civi\Lughauth\Features\OAuth\Theme\Application\DecorateHtml;
use Civi\Lughauth\Features\OAuth\Authentication\Infrastructure\Driver\Html\Services\HtmlSecurer;
use Civi\Lughauth\Features\OAuth\Authentication\Infrastructure\Driver\Html\Services\OidcCookieManager;
use Civi\Lughauth\Features\OAuth\Authentication\Infrastructure\Driver\Html\Services\OidcResponseBuilder;
use Civi\Lughauth\Features\OAuth\Authentication\Domain\OidcUrlBuilder;
use Civi\Lughauth\Features\OAuth\Client\Domain\Gateway\ClientStoreGateway;
use Civi\Lughauth\Features\OAuth\Par\Application\Usecase\ResolveParRequest\ResolveParRequestUsecase;
use Civi\Lughauth\Features\OAuth\Authentication\Domain\RequestObjectValidator;
use Civi\Lughauth\Features\OAuth\Par\Domain\Gateway\ParRequestGateway;
use Civi\Lughauth\Features\OAuth\Authentication\Domain\AuthenticationResult;
use Civi\Lughauth\Features\OAuth\User\Domain\PublicLoginAuthResponse;
use Civi\Lughauth\Features\OAuth\TokenSecurity\Domain\Gateway\TokenSigner;
use Civi\Lughauth\Features\OAuth\Session\Domain\Gateway\TemporalKeysGateway;
use Civi\Lughauth\Shared\Exception\UnauthorizedException;
use Jose\Component\Core\AlgorithmManager;
use Jose\Component\KeyManagement\JWKFactory;
use Jose\Component\Signature\Algorithm\RS256;
use Jose\Component\Signature\JWSBuilder;
use Jose\Component\Signature\Serializer\CompactSerializer;
use Psr\Http\Client\ClientInterface;
use Psr\Http\Message\RequestFactoryInterface;

/**
 * Integration tests for {@see AuthorizeHtml} step delegation.
 */
#[AllowMockObjectsWithoutExpectations]
final class AuthorizeHtmlIntegrationUnitTest extends TestCase
{
    private array $serverBackup = [];

    #[Override]
    protected function setUp(): void
    {
        $this->serverBackup = $_SERVER;
        $_SERVER['HTTPS'] = 'on';
        $_SERVER['HTTP_HOST'] = 'example.com';
        $_SERVER['SCRIPT_NAME'] = '/index.php';
    }

    #[Override]
    protected function tearDown(): void
    {
        $_SERVER = $this->serverBackup;
    }

    /**
     * Verifies authorize delegates render to the routed form.
     */
    public function testAuthorizeDelegatesToStepRouter(): void
    {
        $request = (new ServerRequestFactory())
            ->createServerRequest('GET', '/oauth/openid/tenant1/authorize')
            ->withQueryParams([
                'response_type' => 'code',
                'client_id' => 'client-123',
                'state' => 'state-xyz',
                'redirect_uri' => 'https://client.example/callback',
                'scope' => 'openid',
                'nonce' => 'nonce-abc',
                'step' => StepName::CONSENT->value,
                'code_challenge' => 'E9Melhoa2OwvFrEMTJguCHaoeK1t8URWbuGJSstw-cM',
                'code_challenge_method' => 'S256',
            ]);

        $builder = new ContainerBuilder();
        $config = $this->createMock(AppConfig::class);
        $context = new Context($builder, $config);

        $clients = $this->createMock(ClientStoreGateway::class);
        $clients->expects($this->once())
            ->method('publicClientData')
            ->with('client-123', 'tenant1', 'https://client.example/callback', 'openid')
            ->willReturn(new ClientData('client-123', ['code'], true));
        $sessions = $this->createMock(SessionManager::class);
        $sessions->expects($this->once())
            ->method('loadSession')
            ->willReturn(null);

        $consentForm = $this->createMock(TermsAndGdprConsentForm::class);
        $consentForm->method('render')->willReturn(StepResult::render(new Response(), new ChallengesState()));

        $loginForm = $this->createMock(LoginForm::class);
        $loginForm->method('render')->willReturn(StepResult::render(new Response(), new ChallengesState()));

        $router = new OidcStepRouter(
            $consentForm,
            $this->createMock(ScopeConsentForm::class),
            $loginForm,
            $this->createMock(NewMfaForm::class),
            $this->createMock(NewPassForm::class),
            $this->createMock(UseMfaForm::class),
            $this->createMock(RecoverPassForm::class),
            $this->createMock(DelegateForm::class),
            $this->createMock(RegisterUserForm::class),
            $this->createMock(WebAuthnLoginForm::class),
            $this->createMock(MagicLinkLoginForm::class)
        );

        $cookies = $this->createMock(OidcCookieManager::class);
        $cookies->expects($this->once())
            ->method('clearSession')
            ->willReturnCallback(static fn (ResponseInterface $response): ResponseInterface => $response);

        $authorize = new AuthorizeHtml(
            $context,
            $clients,
            $sessions,
            $this->createMock(AuthenticateUser::class),
            $this->createMock(HtmlSecurer::class),
            $this->createMock(DecorateHtml::class),
            $this->createMock(OidcResponseBuilder::class),
            $cookies,
            new OidcUrlBuilder($context),
            $router,
            new ResolveParRequestUsecase($this->createMock(ParRequestGateway::class)),
            $this->buildRequestObjectValidator()
        );

        $response = $authorize->authorize($request, new Response(), ['tenant' => 'tenant1']);

        $this->assertInstanceOf(ResponseInterface::class, $response);
    }

    /**
     * Verifies formAuthorize proceeds through the step router.
     */
    public function testFormAuthorizeProceedsWithCsid(): void
    {
        $request = (new ServerRequestFactory())
            ->createServerRequest('POST', '/oauth/openid/tenant1/authorize')
            ->withQueryParams([
                'response_type' => 'code',
                'client_id' => 'client-123',
                'state' => 'state-xyz',
                'redirect_uri' => 'https://client.example/callback',
                'scope' => 'openid',
                'nonce' => 'nonce-abc',
                'code_challenge' => 'E9Melhoa2OwvFrEMTJguCHaoeK1t8URWbuGJSstw-cM',
                'code_challenge_method' => 'S256',
            ])
            ->withParsedBody([
                'csid' => 'signed-csid'
            ]);

        $builder = new ContainerBuilder();
        $config = $this->createMock(AppConfig::class);
        $context = new Context($builder, $config);

        $clients = $this->createMock(ClientStoreGateway::class);
        $clients->expects($this->once())
            ->method('publicClientData')
            ->with('client-123', 'tenant1', 'https://client.example/callback', 'openid')
            ->willReturn(new ClientData('client-123', ['code'], true));

        $securer = $this->createMock(HtmlSecurer::class);
        $securer->expects($this->once())
            ->method('verifyToken')
            ->with('signed-csid')
            ->willReturn('csid-123');

        $authResponse = new PublicLoginAuthResponse(
            tenant: 'tenant1',
            auth: new AuthenticationResult(
                valid: true,
                id: 'user-1',
                name: 'User 1',
                email: 'user@example.com',
                tenant: 'tenant1',
                tenantName: 'Tenant 1',
                scope: 'openid',
                audiences: ['client-123'],
                roles: [],
                groups: []
            ),
            issuer: 'https://example.com/oauth/openid/tenant1',
            clientId: 'client-123',
            authExpiration: new \DateInterval('PT10M'),
            idData: [],
            idExpiration: new \DateInterval('PT10M'),
            sessionId: 'sess-123',
            sessionExpiration: new \DateInterval('PT10M')
        );

        $loginForm = $this->createMock(LoginForm::class);
        $loginForm->expects($this->once())
            ->method('authenticate')
            ->willReturn(StepResult::proceed($authResponse, new ChallengesState()));

        $temporals = $this->createMock(TemporalKeysGateway::class);
        $temporals->expects($this->once())
            ->method('registerTemporalAuthCode')
            ->willReturn('temp-code');

        $consentForm = $this->createMock(TermsAndGdprConsentForm::class);
        $scopesTermsAndGdprConsentForm = $this->createMock(ScopeConsentForm::class);
        $newMfaForm = $this->createMock(NewMfaForm::class);
        $newPassForm = $this->createMock(NewPassForm::class);
        $useMfaForm = $this->createMock(UseMfaForm::class);
        $recoverForm = $this->createMock(RecoverPassForm::class);
        $delegateForm = $this->createMock(DelegateForm::class);
        $registerForm = $this->createMock(RegisterUserForm::class);
        $webAuthnForm = $this->createMock(WebAuthnLoginForm::class);
        $magicLinkForm = $this->createMock(MagicLinkLoginForm::class);

        $router = new OidcStepRouter(
            $consentForm,
            $scopesTermsAndGdprConsentForm,
            $loginForm,
            $newMfaForm,
            $newPassForm,
            $useMfaForm,
            $recoverForm,
            $delegateForm,
            $registerForm,
            $webAuthnForm,
            $magicLinkForm
        );

        $cookies = new OidcCookieManager($context, $this->createMock(TokenSigner::class));
        $responseBuilder = new OidcResponseBuilder(
            $this->createMock(TokenSigner::class),
            $temporals,
            $cookies
        );
        $urlBuilder = new OidcUrlBuilder($context);

        $authorize = new AuthorizeHtml(
            $context,
            $clients,
            $this->createMock(SessionManager::class),
            $this->createMock(AuthenticateUser::class),
            $securer,
            $this->createMock(DecorateHtml::class),
            $responseBuilder,
            $cookies,
            $urlBuilder,
            $router,
            new ResolveParRequestUsecase($this->createMock(ParRequestGateway::class)),
            $this->buildRequestObjectValidator()
        );

        $response = $authorize->formAuthorize($request, new Response(), ['tenant' => 'tenant1']);

        $this->assertSame(302, $response->getStatusCode());
        $this->assertStringContainsString('code=temp-code', $response->getHeaderLine('Location'));
        $this->assertStringContainsString('state=state-xyz', $response->getHeaderLine('Location'));
    }

    public function testRefreshWithInvalidCsidRedirectsToLogin(): void
    {
        $request = (new ServerRequestFactory())
            ->createServerRequest('POST', '/oauth/openid/tenant1/authorize')
            ->withQueryParams([
                'response_type' => 'code',
                'client_id' => 'client-123',
                'state' => 'state-xyz',
                'redirect_uri' => 'https://client.example/callback',
                'scope' => 'openid',
                'nonce' => 'nonce-abc',
                'code_challenge' => 'E9Melhoa2OwvFrEMTJguCHaoeK1t8URWbuGJSstw-cM',
                'code_challenge_method' => 'S256',
            ])
            ->withParsedBody([
                'csid' => 'invalid-csid'
            ]);

        $builder = new ContainerBuilder();
        $config = $this->createMock(AppConfig::class);
        $context = new Context($builder, $config);

        $clients = $this->createMock(ClientStoreGateway::class);
        $clients->expects($this->once())
            ->method('publicClientData')
            ->with('client-123', 'tenant1', 'https://client.example/callback', 'openid')
            ->willReturn(new ClientData('client-123', ['code'], true));

        $sessions = $this->createMock(SessionManager::class);
        $sessions->expects($this->never())
            ->method('loadSession')
            ->willReturn(null);

        $securer = $this->createMock(HtmlSecurer::class);
        $securer->expects($this->once())
            ->method('verifyToken')
            ->with('invalid-csid')
            ->willReturn(null);

        $cookies = $this->createMock(OidcCookieManager::class);
        $cookies->expects($this->once())
            ->method('clearSession')
            ->willReturnCallback(static fn (ResponseInterface $response): ResponseInterface => $response);

        $authorize = new AuthorizeHtml(
            $context,
            $clients,
            $sessions,
            $this->createMock(AuthenticateUser::class),
            $securer,
            $this->createMock(DecorateHtml::class),
            $this->createMock(OidcResponseBuilder::class),
            $cookies,
            new OidcUrlBuilder($context),
            new OidcStepRouter(
                $this->createMock(TermsAndGdprConsentForm::class),
                $this->createMock(ScopeConsentForm::class),
                $this->createMock(LoginForm::class),
                $this->createMock(NewMfaForm::class),
                $this->createMock(NewPassForm::class),
                $this->createMock(UseMfaForm::class),
                $this->createMock(RecoverPassForm::class),
                $this->createMock(DelegateForm::class),
                $this->createMock(RegisterUserForm::class),
                $this->createMock(WebAuthnLoginForm::class),
                $this->createMock(MagicLinkLoginForm::class)
            ),
            new ResolveParRequestUsecase($this->createMock(ParRequestGateway::class)),
            $this->buildRequestObjectValidator()
        );

        $response = $authorize->refresh($request, new Response(), ['tenant' => 'tenant1']);

        $this->assertSame(302, $response->getStatusCode());
        $this->assertStringContainsString('/oauth/openid/tenant1/authorize', $response->getHeaderLine('Location'));
    }

    public function testAuthorizeWithRequestObjectUsesJwtParamsPrecedence(): void
    {
        [$privateJwk, $jwksJson] = $this->buildRsaJwks();
        $requestJwt = $this->buildRequestObjectJwt($privateJwk, [
            'response_type' => 'code',
            'client_id' => 'client-123',
            'state' => 'state-xyz',
            'redirect_uri' => 'https://client.example/from-jwt',
            'scope' => 'openid',
            'nonce' => 'nonce-abc',
            'step' => StepName::CONSENT->value,
            'code_challenge' => 'E9Melhoa2OwvFrEMTJguCHaoeK1t8URWbuGJSstw-cM',
            'code_challenge_method' => 'S256',
        ]);

        $request = (new ServerRequestFactory())
            ->createServerRequest('GET', '/oauth/openid/tenant1/authorize')
            ->withQueryParams([
                'response_type' => 'code',
                'client_id' => 'client-123',
                'state' => 'state-xyz',
                'redirect_uri' => 'https://client.example/query-value',
                'scope' => 'openid',
                'nonce' => 'nonce-abc',
                'request' => $requestJwt,
            ]);

        $builder = new ContainerBuilder();
        $config = $this->createMock(AppConfig::class);
        $context = new Context($builder, $config);

        $clients = $this->createMock(ClientStoreGateway::class);
        $clients->expects($this->once())
            ->method('preValidatedClient')
            ->with('client-123')
            ->willReturn(new ClientData('client-123', ['code'], true, [], 3600, 'RS256', null, $jwksJson));
        $clients->expects($this->once())
            ->method('publicClientData')
            ->with('client-123', 'tenant1', 'https://client.example/from-jwt', 'openid')
            ->willReturn(new ClientData('client-123', ['code'], true));

        $sessions = $this->createMock(SessionManager::class);
        $sessions->expects($this->once())->method('loadSession')->willReturn(null);

        $consentForm = $this->createMock(TermsAndGdprConsentForm::class);
        $consentForm->method('render')->willReturn(StepResult::render(new Response(), new ChallengesState()));

        $loginForm = $this->createMock(LoginForm::class);
        $loginForm->method('render')->willReturn(StepResult::render(new Response(), new ChallengesState()));

        $router = new OidcStepRouter(
            $consentForm,
            $this->createMock(ScopeConsentForm::class),
            $loginForm,
            $this->createMock(NewMfaForm::class),
            $this->createMock(NewPassForm::class),
            $this->createMock(UseMfaForm::class),
            $this->createMock(RecoverPassForm::class),
            $this->createMock(DelegateForm::class),
            $this->createMock(RegisterUserForm::class),
            $this->createMock(WebAuthnLoginForm::class),
            $this->createMock(MagicLinkLoginForm::class)
        );

        $cookies = $this->createMock(OidcCookieManager::class);
        $cookies->method('clearSession')->willReturn(new Response());

        $authorize = new AuthorizeHtml(
            $context,
            $clients,
            $sessions,
            $this->createMock(AuthenticateUser::class),
            $this->createMock(HtmlSecurer::class),
            $this->createMock(DecorateHtml::class),
            $this->createMock(OidcResponseBuilder::class),
            $cookies,
            new OidcUrlBuilder($context),
            $router,
            new ResolveParRequestUsecase($this->createMock(ParRequestGateway::class)),
            $this->buildRequestObjectValidator()
        );

        $response = $authorize->authorize($request, new Response(), ['tenant' => 'tenant1']);
        $this->assertInstanceOf(ResponseInterface::class, $response);
    }

    public function testAuthorizeWithInvalidRequestObjectThrowsUnauthorized(): void
    {
        $request = (new ServerRequestFactory())
            ->createServerRequest('GET', '/oauth/openid/tenant1/authorize')
            ->withQueryParams([
                'response_type' => 'code',
                'client_id' => 'client-123',
                'state' => 'state-xyz',
                'redirect_uri' => 'https://client.example/callback',
                'scope' => 'openid',
                'nonce' => 'nonce-abc',
                'request' => 'eyJhbGciOiJub25lIn0.eyJjbGllbnRfaWQiOiJjbGllbnQtMTIzIn0.',
            ]);

        $builder = new ContainerBuilder();
        $config = $this->createMock(AppConfig::class);
        $context = new Context($builder, $config);

        $clients = $this->createMock(ClientStoreGateway::class);
        $clients->expects($this->once())
            ->method('preValidatedClient')
            ->with('client-123')
            ->willReturn(new ClientData('client-123', ['code'], true));

        $authorize = new AuthorizeHtml(
            $context,
            $clients,
            $this->createMock(SessionManager::class),
            $this->createMock(AuthenticateUser::class),
            $this->createMock(HtmlSecurer::class),
            $this->createMock(DecorateHtml::class),
            $this->createMock(OidcResponseBuilder::class),
            $this->createMock(OidcCookieManager::class),
            new OidcUrlBuilder($context),
            new OidcStepRouter(
                $this->createMock(TermsAndGdprConsentForm::class),
                $this->createMock(ScopeConsentForm::class),
                $this->createMock(LoginForm::class),
                $this->createMock(NewMfaForm::class),
                $this->createMock(NewPassForm::class),
                $this->createMock(UseMfaForm::class),
                $this->createMock(RecoverPassForm::class),
                $this->createMock(DelegateForm::class),
                $this->createMock(RegisterUserForm::class),
                $this->createMock(WebAuthnLoginForm::class),
                $this->createMock(MagicLinkLoginForm::class)
            ),
            new ResolveParRequestUsecase($this->createMock(ParRequestGateway::class)),
            $this->buildRequestObjectValidator()
        );

        $this->expectException(UnauthorizedException::class);
        $this->expectExceptionMessage('invalid_request_object');
        $authorize->authorize($request, new Response(), ['tenant' => 'tenant1']);
    }

    private function buildRequestObjectJwt(object $privateJwk, array $payload): string
    {
        $builder = new JWSBuilder(new AlgorithmManager([new RS256()]));
        $jws = $builder->create()
            ->withPayload((string) json_encode($payload))
            ->addSignature($privateJwk, ['alg' => 'RS256'])
            ->build();

        return (new CompactSerializer())->serialize($jws, 0);
    }

    private function buildRsaJwks(): array
    {
        $resource = openssl_pkey_new(['private_key_type' => OPENSSL_KEYTYPE_RSA, 'private_key_bits' => 2048]);
        if ($resource === false) {
            $this->fail('Unable to generate rsa key');
        }

        openssl_pkey_export($resource, $privatePem);
        $details = openssl_pkey_get_details($resource);
        $publicPem = is_array($details) ? (string) ($details['key'] ?? '') : '';

        $privateJwk = JWKFactory::createFromKey($privatePem, null, ['kid' => 'k1', 'alg' => 'RS256', 'use' => 'sig']);
        $publicJwk = JWKFactory::createFromKey($publicPem, null, ['kid' => 'k1', 'alg' => 'RS256', 'use' => 'sig']);
        $jwksJson = (string) json_encode(['keys' => [$publicJwk->all()]]);

        return [$privateJwk, $jwksJson];
    }

    private function buildRequestObjectValidator(): RequestObjectValidator
    {
        $http = $this->createMock(ClientInterface::class);
        $requestFactory = $this->createMock(RequestFactoryInterface::class);
        $requestFactory->method('createRequest')->willReturn(new \GuzzleHttp\Psr7\Request('GET', 'https://client.example/jwks'));
        return new RequestObjectValidator($http, $requestFactory);
    }
}
