<?php

# @autogenerated
declare(strict_types=1);

use Civi\Lughauth\Features\Access\Tenant\Domain\TenantRef;
use PHPUnit\Framework\TestCase;
use Civi\Lughauth\Features\Access\TenantConfig\Domain\TenantConfigAttributes;
use Civi\Lughauth\Features\Access\TenantConfig\Domain\TenantConfig;

final class TenantConfigUnitTest extends TestCase
{
    public function test_init_store_values(): void
    {
        // @Arrange
        $one = new TenantConfig(
            uid: 'one',
            tenant: $this->getMockBuilder(TenantRef::class)->setConstructorArgs(['one'])->getMock(),
            innerLabel: 'one',
            forceMfa: true,
            allowRegister: true,
            enableRegisterUsers: true,
            wellcomeEmail: 'one',
            registerdEmail: 'one',
            disabledUserEmail: 'one',
            enabledUserEmail: 'one',
            allowRecoverPass: true,
            recoverPassEmail: 'one',
            version: 1,
        );

        // @Act
        $other = $one->toAttributes()->build();

        // @Assert
        $this->assertEquals($one->uid(), $other->uid());
        $this->assertEquals($one->getTenant(), $other->getTenant());
        $this->assertTrue($one->isTenantChanged());
        $this->assertEquals($one->getInnerLabel(), $other->getInnerLabel());
        $this->assertTrue($one->isInnerLabelChanged());
        $this->assertEquals($one->getForceMfa(), $other->getForceMfa());
        $this->assertTrue($one->isForceMfaChanged());
        $this->assertEquals($one->getAllowRegister(), $other->getAllowRegister());
        $this->assertTrue($one->isAllowRegisterChanged());
        $this->assertEquals($one->getEnableRegisterUsers(), $other->getEnableRegisterUsers());
        $this->assertTrue($one->isEnableRegisterUsersChanged());
        $this->assertEquals($one->getWellcomeEmail(), $other->getWellcomeEmail());
        $this->assertTrue($one->isWellcomeEmailChanged());
        $this->assertEquals($one->getRegisterdEmail(), $other->getRegisterdEmail());
        $this->assertTrue($one->isRegisterdEmailChanged());
        $this->assertEquals($one->getDisabledUserEmail(), $other->getDisabledUserEmail());
        $this->assertTrue($one->isDisabledUserEmailChanged());
        $this->assertEquals($one->getEnabledUserEmail(), $other->getEnabledUserEmail());
        $this->assertTrue($one->isEnabledUserEmailChanged());
        $this->assertEquals($one->getAllowRecoverPass(), $other->getAllowRecoverPass());
        $this->assertTrue($one->isAllowRecoverPassChanged());
        $this->assertEquals($one->getRecoverPassEmail(), $other->getRecoverPassEmail());
        $this->assertTrue($one->isRecoverPassEmailChanged());
        $this->assertEquals($one->getVersion(), $other->getVersion());
        $this->assertTrue($one->isVersionChanged());
    }
    public function test_replace_change_values(): void
    {
        // @Arrange
        $base = new TenantConfig(
            uid: 'one',
            tenant: $this->getMockBuilder(TenantRef::class)->setConstructorArgs(['one'])->getMock(),
            innerLabel: 'one',
            forceMfa: true,
            allowRegister: true,
            enableRegisterUsers: true,
            wellcomeEmail: 'one',
            registerdEmail: 'one',
            disabledUserEmail: 'one',
            enabledUserEmail: 'one',
            allowRecoverPass: true,
            recoverPassEmail: 'one',
            version: 1,
        );
        $other = new TenantConfig(
            uid: 'other',
            tenant: $this->getMockBuilder(TenantRef::class)->setConstructorArgs(['other'])->getMock(),
            innerLabel: 'other',
            forceMfa: false,
            allowRegister: false,
            enableRegisterUsers: false,
            wellcomeEmail: 'other',
            registerdEmail: 'other',
            disabledUserEmail: 'other',
            enabledUserEmail: 'other',
            allowRecoverPass: false,
            recoverPassEmail: 'other',
            version: 2,
        );

        // @Act
        $one = $base->replace($other->toAttributes());

        // @Assert
        $this->assertEquals($one->uid(), $base->uid());
        $this->assertEquals($one->getTenant(), $other->getTenant());
        $this->assertTrue($one->isTenantChanged($base));
        $this->assertEquals($one->getInnerLabel(), $other->getInnerLabel());
        $this->assertTrue($one->isInnerLabelChanged($base));
        $this->assertEquals($one->getForceMfa(), $other->getForceMfa());
        $this->assertTrue($one->isForceMfaChanged($base));
        $this->assertEquals($one->getAllowRegister(), $other->getAllowRegister());
        $this->assertTrue($one->isAllowRegisterChanged($base));
        $this->assertEquals($one->getEnableRegisterUsers(), $other->getEnableRegisterUsers());
        $this->assertTrue($one->isEnableRegisterUsersChanged($base));
        $this->assertEquals($one->getWellcomeEmail(), $other->getWellcomeEmail());
        $this->assertTrue($one->isWellcomeEmailChanged($base));
        $this->assertEquals($one->getRegisterdEmail(), $other->getRegisterdEmail());
        $this->assertTrue($one->isRegisterdEmailChanged($base));
        $this->assertEquals($one->getDisabledUserEmail(), $other->getDisabledUserEmail());
        $this->assertTrue($one->isDisabledUserEmailChanged($base));
        $this->assertEquals($one->getEnabledUserEmail(), $other->getEnabledUserEmail());
        $this->assertTrue($one->isEnabledUserEmailChanged($base));
        $this->assertEquals($one->getAllowRecoverPass(), $other->getAllowRecoverPass());
        $this->assertTrue($one->isAllowRecoverPassChanged($base));
        $this->assertEquals($one->getRecoverPassEmail(), $other->getRecoverPassEmail());
        $this->assertTrue($one->isRecoverPassEmailChanged($base));
        $this->assertEquals($one->getVersion(), $other->getVersion());
        $this->assertTrue($one->isVersionChanged($base));
    }
    public function test_create_store_values(): void
    {
        // @Arrange
        $one = new TenantConfig(
            uid: 'one',
            tenant: $this->getMockBuilder(TenantRef::class)->setConstructorArgs(['one'])->getMock(),
            innerLabel: 'one',
            forceMfa: true,
            allowRegister: true,
            enableRegisterUsers: true,
            wellcomeEmail: 'one',
            registerdEmail: 'one',
            disabledUserEmail: 'one',
            enabledUserEmail: 'one',
            allowRecoverPass: true,
            recoverPassEmail: 'one',
            version: 1,
        );

        // @Act
        $other = TenantConfig::create($one->toAttributes());

        // @Assert
        $this->assertEquals($one->uid(), $other->uid());
        $this->assertEquals($one->getTenant(), $other->getTenant());
        $this->assertTrue($one->isTenantChanged());
        $this->assertEquals($one->getInnerLabel(), $other->getInnerLabel());
        $this->assertTrue($one->isInnerLabelChanged());
        $this->assertEquals($one->getForceMfa(), $other->getForceMfa());
        $this->assertTrue($one->isForceMfaChanged());
        $this->assertEquals($one->getAllowRegister(), $other->getAllowRegister());
        $this->assertTrue($one->isAllowRegisterChanged());
        $this->assertEquals($one->getEnableRegisterUsers(), $other->getEnableRegisterUsers());
        $this->assertTrue($one->isEnableRegisterUsersChanged());
        $this->assertEquals($one->getWellcomeEmail(), $other->getWellcomeEmail());
        $this->assertTrue($one->isWellcomeEmailChanged());
        $this->assertEquals($one->getRegisterdEmail(), $other->getRegisterdEmail());
        $this->assertTrue($one->isRegisterdEmailChanged());
        $this->assertEquals($one->getDisabledUserEmail(), $other->getDisabledUserEmail());
        $this->assertTrue($one->isDisabledUserEmailChanged());
        $this->assertEquals($one->getEnabledUserEmail(), $other->getEnabledUserEmail());
        $this->assertTrue($one->isEnabledUserEmailChanged());
        $this->assertEquals($one->getAllowRecoverPass(), $other->getAllowRecoverPass());
        $this->assertTrue($one->isAllowRecoverPassChanged());
        $this->assertEquals($one->getRecoverPassEmail(), $other->getRecoverPassEmail());
        $this->assertTrue($one->isRecoverPassEmailChanged());
        $this->assertEquals($one->getVersion(), $other->getVersion());
        $this->assertTrue($one->isVersionChanged());
        $this->assertCount(0, $one->getTheEvents());
        $this->assertCount(1, $other->getTheEvents());
    }
    public function test_update_change_values(): void
    {
        $base = new TenantConfig(
            uid: 'one',
            tenant: $this->getMockBuilder(TenantRef::class)->setConstructorArgs(['one'])->getMock(),
            innerLabel: 'one',
            forceMfa: true,
            allowRegister: true,
            enableRegisterUsers: true,
            wellcomeEmail: 'one',
            registerdEmail: 'one',
            disabledUserEmail: 'one',
            enabledUserEmail: 'one',
            allowRecoverPass: true,
            recoverPassEmail: 'one',
            version: 1,
        );
        $other = new TenantConfig(
            uid: 'other',
            tenant: $this->getMockBuilder(TenantRef::class)->setConstructorArgs(['other'])->getMock(),
            innerLabel: 'other',
            forceMfa: false,
            allowRegister: false,
            enableRegisterUsers: false,
            wellcomeEmail: 'other',
            registerdEmail: 'other',
            disabledUserEmail: 'other',
            enabledUserEmail: 'other',
            allowRecoverPass: false,
            recoverPassEmail: 'other',
            version: 2,
        );

        // @Act
        $one = $base->update($other->toAttributes());

        // @Assert
        $this->assertEquals($one->uid(), $base->uid());
        $this->assertEquals($one->getTenant(), $other->getTenant());
        $this->assertTrue($one->isTenantChanged($base));
        $this->assertEquals($one->getInnerLabel(), $other->getInnerLabel());
        $this->assertTrue($one->isInnerLabelChanged($base));
        $this->assertEquals($one->getForceMfa(), $other->getForceMfa());
        $this->assertTrue($one->isForceMfaChanged($base));
        $this->assertEquals($one->getAllowRegister(), $other->getAllowRegister());
        $this->assertTrue($one->isAllowRegisterChanged($base));
        $this->assertEquals($one->getEnableRegisterUsers(), $other->getEnableRegisterUsers());
        $this->assertTrue($one->isEnableRegisterUsersChanged($base));
        $this->assertEquals($one->getWellcomeEmail(), $other->getWellcomeEmail());
        $this->assertTrue($one->isWellcomeEmailChanged($base));
        $this->assertEquals($one->getRegisterdEmail(), $other->getRegisterdEmail());
        $this->assertTrue($one->isRegisterdEmailChanged($base));
        $this->assertEquals($one->getDisabledUserEmail(), $other->getDisabledUserEmail());
        $this->assertTrue($one->isDisabledUserEmailChanged($base));
        $this->assertEquals($one->getEnabledUserEmail(), $other->getEnabledUserEmail());
        $this->assertTrue($one->isEnabledUserEmailChanged($base));
        $this->assertEquals($one->getAllowRecoverPass(), $other->getAllowRecoverPass());
        $this->assertTrue($one->isAllowRecoverPassChanged($base));
        $this->assertEquals($one->getRecoverPassEmail(), $other->getRecoverPassEmail());
        $this->assertTrue($one->isRecoverPassEmailChanged($base));
        $this->assertEquals($one->getVersion(), $other->getVersion());
        $this->assertTrue($one->isVersionChanged($base));
        $this->assertCount(0, $other->getTheEvents());
        $this->assertCount(1, $one->getTheEvents());
    }
    public function test_delete_store_values(): void
    {
        // @Arrange
        $one = new TenantConfig(
            uid: 'one',
            tenant: $this->getMockBuilder(TenantRef::class)->setConstructorArgs(['one'])->getMock(),
            innerLabel: 'one',
            forceMfa: true,
            allowRegister: true,
            enableRegisterUsers: true,
            wellcomeEmail: 'one',
            registerdEmail: 'one',
            disabledUserEmail: 'one',
            enabledUserEmail: 'one',
            allowRecoverPass: true,
            recoverPassEmail: 'one',
            version: 1,
        );

        // @Act
        $other = $one->delete();

        // @Assert
        $this->assertEquals($one->uid(), $other->uid());
        $this->assertEquals($one->getTenant(), $other->getTenant());
        $this->assertTrue($one->isTenantChanged());
        $this->assertEquals($one->getInnerLabel(), $other->getInnerLabel());
        $this->assertTrue($one->isInnerLabelChanged());
        $this->assertEquals($one->getForceMfa(), $other->getForceMfa());
        $this->assertTrue($one->isForceMfaChanged());
        $this->assertEquals($one->getAllowRegister(), $other->getAllowRegister());
        $this->assertTrue($one->isAllowRegisterChanged());
        $this->assertEquals($one->getEnableRegisterUsers(), $other->getEnableRegisterUsers());
        $this->assertTrue($one->isEnableRegisterUsersChanged());
        $this->assertEquals($one->getWellcomeEmail(), $other->getWellcomeEmail());
        $this->assertTrue($one->isWellcomeEmailChanged());
        $this->assertEquals($one->getRegisterdEmail(), $other->getRegisterdEmail());
        $this->assertTrue($one->isRegisterdEmailChanged());
        $this->assertEquals($one->getDisabledUserEmail(), $other->getDisabledUserEmail());
        $this->assertTrue($one->isDisabledUserEmailChanged());
        $this->assertEquals($one->getEnabledUserEmail(), $other->getEnabledUserEmail());
        $this->assertTrue($one->isEnabledUserEmailChanged());
        $this->assertEquals($one->getAllowRecoverPass(), $other->getAllowRecoverPass());
        $this->assertTrue($one->isAllowRecoverPassChanged());
        $this->assertEquals($one->getRecoverPassEmail(), $other->getRecoverPassEmail());
        $this->assertTrue($one->isRecoverPassEmailChanged());
        $this->assertEquals($one->getVersion(), $other->getVersion());
        $this->assertTrue($one->isVersionChanged());
    }
}
