<?php

/* @autogenerated */
declare(strict_types=1);

namespace Civi\Lughauth\Features\Access\UserInvitation\Domain;

use Civi\Lughauth\Features\Access\UserInvitation\Domain\ValueObject\UserInvitationUidVO;

class UserInvitationRef
{
    private readonly UserInvitationUidVO $_uid;
    public ?UserInvitation $_private_resolve = null;
    public function __construct(UserInvitationUidVO|string $uid)
    {
        $this->_uid = UserInvitationUidVO::from($uid);
    }
    public function uid(): ?string
    {
        return $this->_uid->value();
    }
}
