<?php

# @autogenerated
declare(strict_types=1);

namespace Civi\Lughauth\Features\Notification\Message\Application\Usecase\Update;

use Psr\EventDispatcher\EventDispatcherInterface;
use Throwable;
use Civi\Lughauth\Shared\Security\Allow;
use Civi\Lughauth\Shared\Exception\UnauthorizedException;
use Civi\Lughauth\Shared\Exception\NotFoundException;
use Civi\Lughauth\Features\Notification\Message\Domain\MessageRef;
use Civi\Lughauth\Features\Notification\Message\Application\Service\Visibility\MessageVisibilityService;
use Civi\Lughauth\Features\Notification\Message\Domain\Gateway\MessageWriteGateway;
use Civi\Lughauth\Shared\Observability\LoggerAwareTrait;
use Civi\Lughauth\Shared\Observability\TracerAwareTrait;

class MessageUpdateUsecase
{
    use LoggerAwareTrait;
    use TracerAwareTrait;

    public function __construct(
        private readonly EventDispatcherInterface $dispatcher,
        private readonly MessageVisibilityService $visibility,
        private readonly MessageWriteGateway $writer,
    ) {
    }

    public function allowUpdate(?MessageRef $ref = null): Allow
    {
        $this->logDebug("Check allow update usecase for Message");
        $span = $this->startSpan("Check allow update usecase for Message");
        try {
            $result = $this->dispatcher->dispatch(new MessageUpdateAllowDecision(Allow::allowed('update', 'Allowed to update by default')));
            return $result->getAllow();
        } catch (Throwable $ex) {
            $span->recordException($ex);
            throw $ex;
        } finally {
            $span->end();
        }
    }
    public function fixedFields(?MessageRef $ref = null): array
    {
        $this->logDebug("Check fixed fields for update usecase for Message");
        $span = $this->startSpan("Check fixed fields for update usecase for Message");
        try {
            return $this->visibility->fieldsToFix($ref);
        } catch (Throwable $ex) {
            $span->recordException($ex);
            throw $ex;
        } finally {
            $span->end();
        }
    }
    public function update(string $uid, MessageUpdateParams $params): MessageUpdateResult
    {
        $this->logDebug("Run update usecase for Message");
        $span = $this->startSpan("Run update usecase for Message");
        try {
            $ref = new MessageRef($uid);
            $allow = $this->allowUpdate($ref);
            if (!$allow->allowed) {
                throw new UnauthorizedException($allow->reason ?? 'Not allowed to update Message');
            }
            if (!$original = $this->visibility->retrieveVisibleForUpdate($ref)) {
                throw new NotFoundException($uid);
            }
            $this->dispatcher->dispatch(new MessageUpdateCheck($params, $original));
            $enriched = $this->dispatcher->dispatch(new MessageUpdateEnrich($params, $original, $params->toAttributes()));
            $attributes = $enriched->getResult();
            $input = $this->visibility->copyWithFixed($attributes);
            $modified = $original->update($input);
            $result = $this->writer->update($original, $modified);
            $output = $this->visibility->copyWithHidden($this->visibility->prepareVisibleData($result));
            return new MessageUpdateResult($output);
        } catch (Throwable $ex) {
            $span->recordException($ex);
            throw $ex;
        } finally {
            $span->end();
        }
    }
}
