<?php

# @autogenerated
declare(strict_types=1);

use Civi\Lughauth\Features\Notification\SmtpOutboundConfig\Domain\ValueObject\SmtpOutboundConfigHostVO;
use Civi\Lughauth\Features\Notification\SmtpOutboundConfig\Domain\ValueObject\Holder\SmtpOutboundConfigHostAttributeHolder;
use Civi\Lughauth\Shared\Value\Validation\ConstraintFailList;
use PHPUnit\Framework\TestCase;

/**
 * Unit tests for the SmtpOutboundConfigHostAttributeHolder trait.
 *
 * Covers assignment, retrieval, default fallback,
 * transfer between holders, validation rules, and unset operations.
 */
class SmtpOutboundConfigHostAttributeHolderUnitTest extends TestCase
{
        /**
         * Asserts that the code attribute is not assigned by default
         * and that getHost returns null on a freshly created holder.
         */
        public function testHostNotAssignedByDefault(): void
        {
            // Arrange
            $holder = new ImplWithSmtpOutboundConfigHostAttributeHolderUnitTest();

            // Assert
            $this->assertFalse($holder->isHostAssigned());
            $this->assertNull($holder->getHost());
        }
}
class ImplWithSmtpOutboundConfigHostAttributeHolderUnitTest
{
  use SmtpOutboundConfigHostAttributeHolder;
    public function assertRules(ConstraintFailList $errorsList): self
    {
        $result = new self();
        $this->withAssertedHostRules($result, $errorsList);
        return $result;
    }

    public function applyDefaults(): void
    {
        $this->withDefaultHost();
    }}
