<?php

# @autogenerated
declare(strict_types=1);

namespace Civi\Lughauth\Features\Access\RelyingParty\Infrastructure\Driver\Rest;

use Psr\Http\Message\ServerRequestInterface;
use Throwable;
use Civi\Lughauth\Features\Access\RelyingParty\Domain\ValueObject\RelyingPartyUidVO;
use Civi\Lughauth\Features\Access\RelyingParty\Domain\ValueObject\RelyingPartyCodeVO;
use Civi\Lughauth\Features\Access\RelyingParty\Domain\ValueObject\RelyingPartyApiKeyVO;
use Civi\Lughauth\Features\Access\RelyingParty\Domain\ValueObject\RelyingPartyVersionVO;
use Civi\Lughauth\Shared\Value\Validation\ConstraintFailList;
use Civi\Lughauth\Features\Access\RelyingParty\Domain\RelyingPartyAttributes;
use Civi\Lughauth\Shared\Observability\LoggerAwareTrait;
use Civi\Lughauth\Shared\Observability\TracerAwareTrait;

class RelyingPartyRestMapper
{
    use LoggerAwareTrait;
    use TracerAwareTrait;

    public function readRelyingParty(ServerRequestInterface $request): RelyingPartyAttributes
    {
        $this->logDebug("Read entity for Relying party");
        $span = $this->startSpan("Read entity for Relying party");
        try {
            $body = $request->getParsedBody();
            $dto = new RelyingPartyApiDTO();
            $dto->uid = $body['uid'] ?? null;
            $dto->code = $body['code'] ?? null;
            $dto->apiKey = $body['apiKey'] ?? null;
            $dto->enabled = $body['enabled'] ?? null;
            $dto->version = $body['version'] ?? null;
            return $this->mapRelyingPartyApiDTO($dto);
        } catch (Throwable $ex) {
            $span->recordException($ex);
            throw $ex;
        } finally {
            $span->end();
        }
    }
    public function mapRelyingPartyApiDTO(RelyingPartyApiDTO $body): RelyingPartyAttributes
    {
        $this->logDebug("Map input dto to entity for Relying party");
        $span = $this->startSpan("Map input dto to entity for Relying party");
        try {
            $errorsList = new ConstraintFailList();
            $value = new RelyingPartyAttributes();
            $value->uid(RelyingPartyUidVO::tryFrom($body->uid ?? null, $errorsList));
            $value->code(RelyingPartyCodeVO::tryFrom($body->code ?? null, $errorsList));
            $value->apiKey(RelyingPartyApiKeyVO::tryFrom($body->apiKey ?? null, $errorsList));
            // enabled is a calculated value, we cant read it
            $value->version(RelyingPartyVersionVO::tryFrom($body->version ?? null, $errorsList));
            if ($errorsList->hasErrors()) {
                throw $errorsList->asConstraintException();
            }
            return $value;
        } catch (Throwable $ex) {
            $span->recordException($ex);
            throw $ex;
        } finally {
            $span->end();
        }
    }
    public function mapRelyingParty(RelyingPartyAttributes $value): RelyingPartyApiDTO
    {
        $this->logDebug("Map entity to output dto for Relying party");
        $span = $this->startSpan("Map entity to output dto for Relying party");
        try {
            $dto = new RelyingPartyApiDTO();
            $dto->uid = $value->getUid();
            $dto->code = $value->getCode();
            $dto->apiKey = $value->getApiKey();
            $dto->enabled = $value->getEnabled();
            $dto->version = $value->getVersion();
            return $dto;
        } catch (Throwable $ex) {
            $span->recordException($ex);
            throw $ex;
        } finally {
            $span->end();
        }
    }
}
