<?php

# @autogenerated
declare(strict_types=1);

namespace Civi\Lughauth\Features\Access\User\Application\Policy\Allow\Create;

use Override;
use Throwable;
use Civi\Lughauth\Features\Access\User\Application\Usecase\Create\UserCreateAllowProposal;
use Civi\Lughauth\Shared\Context;
use Civi\Lughauth\Shared\Security\Allow;
use Civi\Lughauth\Shared\Observability\LoggerAwareTrait;
use Civi\Lughauth\Shared\Observability\TracerAwareTrait;

class CreateUserOnlyForRootAllow
{
    use LoggerAwareTrait;
    use TracerAwareTrait;

    public function __construct(private readonly Context $context)
    {
    }
    public function __invoke(UserCreateAllowProposal $proposal): UserCreateAllowProposal
    {
        $this->logDebug("Check CreateUserOnlyForRootAllow User");
        $span = $this->startSpan("Check CreateUserOnlyForRootAllow User");
        try {
            $userContext = $this->context->getIdentity();
            if ($proposal->allow->allowed) {
                $belongs = $userContext->hasAnyRole('ROOT');
                $allowed = $belongs ? Allow::allowed('create', 'Enabled for user CreateUserOnlyForRoot') : Allow::disallowed('create', 'Disabled if not CreateUserOnlyForRoot');
                $proposal->allow = $allowed;
            }
            return $proposal;
        } catch (Throwable $ex) {
            $span->recordException($ex);
            throw $ex;
        } finally {
            $span->end();
        }
    }
}
