<?php

# @autogenerated
declare(strict_types=1);

namespace Civi\Lughauth\Features\Access\TenantConfig\Application\Usecase\Create;

use Civi\Lughauth\Features\Access\TenantConfig\Domain\ValueObject\Holder\TenantConfigUidAttributeHolder;
use Civi\Lughauth\Features\Access\TenantConfig\Domain\ValueObject\Holder\TenantConfigTenantAttributeHolder;
use Civi\Lughauth\Features\Access\TenantConfig\Domain\ValueObject\Holder\TenantConfigInnerLabelAttributeHolder;
use Civi\Lughauth\Features\Access\TenantConfig\Domain\ValueObject\Holder\TenantConfigForceMfaAttributeHolder;
use Civi\Lughauth\Features\Access\TenantConfig\Domain\ValueObject\Holder\TenantConfigAllowRegisterAttributeHolder;
use Civi\Lughauth\Features\Access\TenantConfig\Domain\ValueObject\Holder\TenantConfigEnableRegisterUsersAttributeHolder;
use Civi\Lughauth\Features\Access\TenantConfig\Domain\ValueObject\Holder\TenantConfigWellcomeEmailAttributeHolder;
use Civi\Lughauth\Features\Access\TenantConfig\Domain\ValueObject\Holder\TenantConfigRegisterdEmailAttributeHolder;
use Civi\Lughauth\Features\Access\TenantConfig\Domain\ValueObject\Holder\TenantConfigDisabledUserEmailAttributeHolder;
use Civi\Lughauth\Features\Access\TenantConfig\Domain\ValueObject\Holder\TenantConfigEnabledUserEmailAttributeHolder;
use Civi\Lughauth\Features\Access\TenantConfig\Domain\ValueObject\Holder\TenantConfigAllowRecoverPassAttributeHolder;
use Civi\Lughauth\Features\Access\TenantConfig\Domain\ValueObject\Holder\TenantConfigRecoverPassEmailAttributeHolder;
use Civi\Lughauth\Features\Access\TenantConfig\Domain\ValueObject\Holder\TenantConfigVersionAttributeHolder;
use Civi\Lughauth\Features\Access\TenantConfig\Domain\TenantConfigAttributes;

class TenantConfigCreateParams
{
    use TenantConfigUidAttributeHolder;
    use TenantConfigTenantAttributeHolder;
    use TenantConfigInnerLabelAttributeHolder;
    use TenantConfigForceMfaAttributeHolder;
    use TenantConfigAllowRegisterAttributeHolder;
    use TenantConfigEnableRegisterUsersAttributeHolder;
    use TenantConfigWellcomeEmailAttributeHolder;
    use TenantConfigRegisterdEmailAttributeHolder;
    use TenantConfigDisabledUserEmailAttributeHolder;
    use TenantConfigEnabledUserEmailAttributeHolder;
    use TenantConfigAllowRecoverPassAttributeHolder;
    use TenantConfigRecoverPassEmailAttributeHolder;
    use TenantConfigVersionAttributeHolder;

    private const UNSETS = [
      'uid' => 'unsetUid',
      'tenant' => 'unsetTenant',
      'innerLabel' => 'unsetInnerLabel',
      'forceMfa' => 'unsetForceMfa',
      'allowRegister' => 'unsetAllowRegister',
      'enableRegisterUsers' => 'unsetEnableRegisterUsers',
      'wellcomeEmail' => 'unsetWellcomeEmail',
      'registerdEmail' => 'unsetRegisterdEmail',
      'disabledUserEmail' => 'unsetDisabledUserEmail',
      'enabledUserEmail' => 'unsetEnabledUserEmail',
      'allowRecoverPass' => 'unsetAllowRecoverPass',
      'recoverPassEmail' => 'unsetRecoverPassEmail',
      'version' => 'unsetVersion',
    ];

    public function __construct(TenantConfigAttributes|null $att = null)
    {
        $this->uid($att->uid);
        $this->tenant($att->tenant);
        $this->innerLabel($att->innerLabel);
        $this->forceMfa($att->forceMfa);
        $this->allowRegister($att->allowRegister);
        $this->enableRegisterUsers($att->enableRegisterUsers);
        $this->wellcomeEmail($att->wellcomeEmail);
        $this->registerdEmail($att->registerdEmail);
        $this->disabledUserEmail($att->disabledUserEmail);
        $this->enabledUserEmail($att->enabledUserEmail);
        $this->allowRecoverPass($att->allowRecoverPass);
        $this->recoverPassEmail($att->recoverPassEmail);
        $this->version($att->version);
    }
    public function toAttributes(): TenantConfigAttributes
    {
        $att = new TenantConfigAttributes();
        $att->uid($this->uid);
        $att->tenant($this->tenant);
        $att->innerLabel($this->innerLabel);
        $att->forceMfa($this->forceMfa);
        $att->allowRegister($this->allowRegister);
        $att->enableRegisterUsers($this->enableRegisterUsers);
        $att->wellcomeEmail($this->wellcomeEmail);
        $att->registerdEmail($this->registerdEmail);
        $att->disabledUserEmail($this->disabledUserEmail);
        $att->enabledUserEmail($this->enabledUserEmail);
        $att->allowRecoverPass($this->allowRecoverPass);
        $att->recoverPassEmail($this->recoverPassEmail);
        $att->version($this->version);
        return $att;
    }
    public function unset($field)
    {
        if (isset(self::UNSETS[$field])) {
            call_user_func([$this, self::UNSETS[$field]]);
        }
    }
    public function withDefaults(): TenantConfigCreateParams
    {
        $this->withDefaultUid();
        $this->withDefaultTenant();
        $this->withDefaultInnerLabel();
        $this->withDefaultForceMfa();
        $this->withDefaultAllowRegister();
        $this->withDefaultEnableRegisterUsers();
        $this->withDefaultWellcomeEmail();
        $this->withDefaultRegisterdEmail();
        $this->withDefaultDisabledUserEmail();
        $this->withDefaultEnabledUserEmail();
        $this->withDefaultAllowRecoverPass();
        $this->withDefaultRecoverPassEmail();
        $this->withDefaultVersion();
        return $this;
    }
}
