<?php

/* @autogenerated */
declare(strict_types=1);

namespace Civi\Lughauth\Shared\Exception;

/**
 * Exception thrown when an optimistic lock check fails due to concurrent modification.
 */
class OptimistLockException extends \RuntimeException
{
    /**
     * Creates a new optimistic lock exception.
     */
    public function __construct(
        /** @var string The reference to the conflicting resource. */
        public readonly string $ref,
        /** @var string The conflicting lock or version identifier. */
        public readonly string $lock
    ) {
    }
}
