<?php

# @autogenerated
declare(strict_types=1);

namespace Civi\Lughauth\Features\Access\UserAccessTemporalCode\Domain\ValueObject\Accesor;

use Civi\Lughauth\Features\Access\UserAccessTemporalCode\Domain\ValueObject\UserAccessTemporalCodeTempSecondFactorSeedExpirationVO;

trait UserAccessTemporalCodeTempSecondFactorSeedExpirationAccesor
{
    private ?UserAccessTemporalCodeTempSecondFactorSeedExpirationVO $_tempSecondFactorSeedExpiration = null;
    public function getTempSecondFactorSeedExpiration(): ?\DateTimeImmutable
    {
        return $this->_tempSecondFactorSeedExpiration?->value();
    }
    public function tempSecondFactorSeedExpiration(): ?UserAccessTemporalCodeTempSecondFactorSeedExpirationVO
    {
        return $this->_tempSecondFactorSeedExpiration;
    }
    public function isTempSecondFactorSeedExpirationChanged(?self $original = null): bool
    {
        return $this->_tempSecondFactorSeedExpiration->value() !== ($original ? $original->_tempSecondFactorSeedExpiration->value() : null);
    }
    public function withTempSecondFactorSeedExpiration(UserAccessTemporalCodeTempSecondFactorSeedExpirationVO|\DateTimeImmutable|null $tempSecondFactorSeedExpiration): self
    {
        $copy = clone $this;
        $copy->_tempSecondFactorSeedExpiration = UserAccessTemporalCodeTempSecondFactorSeedExpirationVO::from($tempSecondFactorSeedExpiration);
        return $copy;
    }
}
