<?php

/* @autogenerated */
declare(strict_types=1);

namespace Civi\Lughauth\Features\Document\ThemeAsset\Domain\Gateway;

use Civi\Lughauth\Shared\Connector\FileStorage\BinaryContent;
use Civi\Lughauth\Features\Document\Theme\Domain\ThemeRef;
use Civi\Lughauth\Features\Document\ThemeAsset\Domain\ThemeAsset;
use Civi\Lughauth\Features\Document\ThemeAsset\Domain\ThemeAssetRef;

interface ThemeAssetReadGateway
{
    public function resolve(ThemeAssetRef $ref): ?ThemeAsset;
    public function list(?ThemeAssetFilter $filter = null, ?ThemeAssetCursor $cursor = null): ThemeAssetSlide;
    public function retrieve(ThemeAssetFilter $filter): ?ThemeAsset;
    public function exists(ThemeAssetFilter $filter): bool;
    public function count(?ThemeAssetFilter $filter = null): int;
    public function readContent(string $key): BinaryContent;
    public function findOneByCodeAndTheme(string $code, ThemeRef $theme): ?ThemeAsset;
}
