<?php

# @autogenerated
declare(strict_types=1);

namespace Civi\Lughauth\Features\Access\UserAccessTemporalCode\Infrastructure\Driver;

use Override;
use Civi\Lughauth\Shared\Infrastructure\MicroPlugin;
use Civi\Lughauth\Features\Access\UserAccessTemporalCode\Infrastructure\Driven\UserAccessTemporalCodeReadRepositoryAdapter;
use Civi\Lughauth\Features\Access\UserAccessTemporalCode\Infrastructure\Driven\UserAccessTemporalCodeWriteRepositoryAdapter;
use Civi\Lughauth\Features\Access\UserAccessTemporalCode\Domain\Gateway\UserAccessTemporalCodeReadGateway;
use Civi\Lughauth\Features\Access\UserAccessTemporalCode\Domain\Gateway\UserAccessTemporalCodeWriteGateway;

class UserAccessTemporalCodePlugin extends MicroPlugin
{
    #[Override]
    public function registerServiceDefinition(array $def): array
    {
        $def[UserAccessTemporalCodeReadGateway::class] = \DI\autowire(UserAccessTemporalCodeReadRepositoryAdapter::class);
        $def[UserAccessTemporalCodeWriteGateway::class] = \DI\autowire(UserAccessTemporalCodeWriteRepositoryAdapter::class);
        return $def;
    }
}
