<?php

/* @autogenerated */
declare(strict_types=1);

use Civi\Lughauth\Features\Document\SnippetAsset\Domain\ValueObject\Holder\SnippetAssetUidAttributeHolder;
use Civi\Lughauth\Shared\Value\Validation\ConstraintFailList;
use PHPUnit\Framework\TestCase;

/**
 * Unit tests for the SnippetAssetUidAttributeHolder trait.
 *
 * Covers assignment, retrieval, default fallback,
 * transfer between holders, validation rules, and unset operations.
 */
class SnippetAssetUidAttributeHolderUnitTest extends TestCase
{
    /**
     * Asserts that the code attribute is not assigned by default
     * and that getUid returns null on a freshly created holder.
     */
    public function testUidNotAssignedByDefault(): void
    {
        // Arrange
        $holder = new ImplWithSnippetAssetUidAttributeHolderUnitTest();

        // Assert
        $this->assertFalse($holder->isUidAssigned());
        $this->assertNull($holder->getUid());
    }
}
class ImplWithSnippetAssetUidAttributeHolderUnitTest
{
    use SnippetAssetUidAttributeHolder;
    public function assertRules(ConstraintFailList $errorsList): self
    {
        $result = new self();
        $this->withAssertedUidRules($result, $errorsList);
        return $result;
    }

    public function applyDefaults(): void
    {
        $this->withDefaultUid();
    }
}
