<?php

/* @autogenerated */
declare(strict_types=1);

namespace Civi\Lughauth\Features\OAuth\TokenSecurity\Domain\Gateway;

use Jose\Component\Core\JWKSet;

/**
 * Port for signing and verifying JWTs using the tenant's active key pair.
 *
 * `sign` produces a standard access/ID token; `signKeypass` produces a
 * session-scoped internal token (keypass) used to carry challenges between
 * redirect steps without exposing them in the URL.
 * `parseSignedPayload` bypasses time checks — use only in revocation flows.
 * Implementations are responsible for key rotation and must ensure that the
 * JWKS returned by `keysAsJwks` contains all keys still needed for verification,
 * including recently expired ones whose tokens may still be in flight.
 */
interface TokenSigner
{
    /**
     * Signs the given payload claims as a compact JWS using the tenant's current active key.
     * Standard time claims (iat, nbf, exp, jti) are automatically injected and must not
     * be included in the provided data array.
     */
    public function sign(string $tenant, array $data, \DateInterval $expiration): string;

    /**
     * Returns the JSON Web Key Set containing all public keys valid for the tenant.
     * The JWKS includes current and near-future keys so clients can cache it safely
     * without hitting a gap when the active signing key rotates.
     */
    public function keysAsJwks(string $tenant): JWKSet;

    /**
     * Signs a keypass token — an internal short-lived JWT that wraps challenge data
     * as a nested "keypass" claim, preventing it from being confused with access tokens.
     * Used to safely pass challenge state across OIDC redirect hops.
     */
    public function signKeypass(string $tenant, array $data, \DateInterval $expiration): string;

    /**
     * Verifies a JWT signature and validates its time claims (nbf/exp).
     * Returns the decoded payload array on success, or null if the token is invalid,
     * expired, or not yet valid.
     */
    public function verifyTokenPayload(string $tenant, string $token): ?array;

    /**
     * Verifies and unwraps a keypass token, returning only the inner "keypass" claim value.
     * Returns null if the token is invalid, expired, or does not contain a keypass claim.
     */
    public function verifiedKeypass(string $tenant, string $token): mixed;

    /**
     * Verifies the JWT signature but ignores time validity (exp/nbf).
     * Returns the payload claims or null if the signature is invalid.
     * Use for revocation flows where expired tokens must still be parseable.
     */
    public function parseSignedPayload(string $tenant, string $token): ?array;
}
