<?php

/* @autogenerated */
declare(strict_types=1);

namespace Civi\Lughauth\Features\Document\Template\Domain\Gateway;

use Closure;
use Civi\Lughauth\Features\Access\Tenant\Domain\TenantRef;
use Civi\Lughauth\Features\Document\Template\Domain\Template;
use Civi\Lughauth\Features\Document\Template\Domain\TemplateRef;

interface TemplateWriteGateway
{
    public function create(Template $entity, ?Closure $verify = null): Template;
    public function update(TemplateRef $ref, Template $entity): Template;
    public function delete(Template $entity): bool;
    public function resolveForUpdate(TemplateRef $ref): ?Template;
    public function listForUpdate(?TemplateFilter $filter = null, ?TemplateCursor $cursor = null): TemplateSlide;
    public function retrieveForUpdate(TemplateFilter $filter): ?Template;
    public function existsForUpdate(TemplateFilter $filter): bool;
    public function countForUpdate(?TemplateFilter $filter = null): int;
    public function findOneForUpdateByCodeAndTenant(string $code, ?TenantRef $tenant): ?Template;
}
