<?php

# @autogenerated
declare(strict_types=1);

namespace Civi\Lughauth\Features\Access\Master\TenantTermsOfUse\Application\Policy\Allow\Disable;

use Throwable;
use Civi\Lughauth\Features\Access\Master\TenantTermsOfUse\Application\Usecase\Disable\TenantTermsOfUseDisableAllowDecision;
use Civi\Lughauth\Shared\Context;
use Civi\Lughauth\Shared\Observability\LoggerAwareTrait;
use Civi\Lughauth\Shared\Observability\TracerAwareTrait;

class IsAutenticatedDisableAllow
{
    use LoggerAwareTrait;
    use TracerAwareTrait;

    public function __construct(private readonly Context $context)
    {
    }
    public function __invoke(TenantTermsOfUseDisableAllowDecision $proposal): TenantTermsOfUseDisableAllowDecision
    {
        $this->logDebug("Check IsAutenticatedDisableAllow Tenant terms of use");
        $span = $this->startSpan("Check IsAutenticatedDisableAllow Tenant terms of use");
        try {
            $userContext = $this->context->getIdentity();
            if ($proposal->isAllowed()) {
                if (! !$userContext->anonimous) {
                    $proposal->deny('Disabled if not IsAutenticatedDisable');
                }
            }
            return $proposal;
        } catch (Throwable $ex) {
            $span->recordException($ex);
            throw $ex;
        } finally {
            $span->end();
        }
    }
}
