<?php

/* @autogenerated */
declare(strict_types=1);

namespace Civi\Lughauth\Features\OAuth\MagicLink\Domain;

use DateTimeImmutable;

/**
 * Aggregate root for a passwordless magic-link authentication request.
 *
 * Encapsulates the full lifecycle of a single magic-link token: creation, validity checks,
 * and consumption. Only the SHA-256 hash of the raw token is stored; the plaintext token
 * travels exclusively in the email link so it cannot be extracted from the database.
 * The aggregate is tied to a specific tenant, OAuth client, user, and redirect URI to
 * prevent cross-tenant or cross-client replay attacks. Call `isValid()` before accepting
 * a verification attempt — it gates both the expiry and the single-use invariants.
 */
final class MagicLink
{
    /**
     * Unique identifier for this magic-link record used as the primary key in the store.
     * Generated by the factory method as a COMB UUID to allow ordered insertion.
     */
    public readonly string $uid;

    /**
     * Name of the tenant to which this magic-link belongs.
     * Scopes the token so it cannot be used to authenticate against a different tenant.
     */
    public readonly string $tenantId;

    /**
     * Identifier of the user who will be authenticated upon successful verification.
     * Stored as a UID reference rather than an email so renames do not invalidate the link.
     */
    public readonly string $userUid;

    /**
     * OAuth client identifier that initiated the magic-link request.
     * The client-id is verified during token validation to prevent cross-client token reuse.
     */
    public readonly string $clientId;

    /**
     * SHA-256 hash of the raw one-time token sent to the user.
     * Never store or log the raw token; all lookups must go through this hash.
     */
    public readonly string $tokenHash;

    /**
     * The URI to which the authorization server will redirect after successful verification.
     * Must match the value registered for the OAuth client.
     */
    public readonly string $redirectUri;

    /**
     * Space-separated list of OAuth scopes requested for this login attempt.
     * Carried through to the authorization code so token issuance honours the original request.
     */
    public readonly string $scope;

    /**
     * Optional opaque state parameter from the original OAuth request, returned to the client on redirect.
     * Null when the initiating request did not include a state value.
     */
    public readonly ?string $state;

    /**
     * OpenID Connect nonce value associated with this request.
     * Forwarded to the authorization code so the ID token can include the nonce claim.
     */
    public readonly string $nonce;

    /**
     * Timestamp at which this magic-link was created, recorded for auditing purposes.
     */
    public readonly DateTimeImmutable $createdAt;

    /**
     * Timestamp after which this magic-link is no longer valid.
     * Typically set to 15 minutes from creation by the use case.
     */
    public readonly DateTimeImmutable $expiresAt;

    /**
     * Timestamp at which this magic-link was consumed, or null if it has not been used yet.
     * A non-null value indicates the link has already been redeemed and must be rejected on retry.
     */
    public readonly ?DateTimeImmutable $usedAt;

    public function __construct(
        string $uid,
        string $tenantId,
        string $userUid,
        string $clientId,
        string $tokenHash,
        string $redirectUri,
        string $scope,
        ?string $state,
        string $nonce,
        DateTimeImmutable $createdAt,
        DateTimeImmutable $expiresAt,
        ?DateTimeImmutable $usedAt = null,
    ) {
        $this->uid = $uid;
        $this->tenantId = $tenantId;
        $this->userUid = $userUid;
        $this->clientId = $clientId;
        $this->tokenHash = $tokenHash;
        $this->redirectUri = $redirectUri;
        $this->scope = $scope;
        $this->state = $state;
        $this->nonce = $nonce;
        $this->createdAt = $createdAt;
        $this->expiresAt = $expiresAt;
        $this->usedAt = $usedAt;
    }

    /**
     * Factory method that constructs a new unsaved MagicLink with the current timestamp as createdAt.
     * All immutable properties are set here; the usedAt field is intentionally left null.
     */
    public static function create(
        string $uid,
        string $tenantId,
        string $userUid,
        string $clientId,
        string $tokenHash,
        string $redirectUri,
        string $scope,
        ?string $state,
        DateTimeImmutable $expiresAt,
        string $nonce = '',
    ): self {
        return new self(
            uid: $uid,
            tenantId: $tenantId,
            userUid: $userUid,
            clientId: $clientId,
            tokenHash: $tokenHash,
            redirectUri: $redirectUri,
            scope: $scope,
            state: $state,
            nonce: $nonce,
            createdAt: new DateTimeImmutable(),
            expiresAt: $expiresAt,
        );
    }

    /**
     * Returns true if the link's expiry timestamp is in the past relative to the current wall clock.
     * An expired link must be rejected even if it has not yet been marked as used.
     */
    public function isExpired(): bool
    {
        return $this->expiresAt < new DateTimeImmutable();
    }

    /**
     * Returns true if the link has already been redeemed, indicated by a non-null usedAt timestamp.
     * A used link must be rejected on any subsequent verification attempt to prevent replay attacks.
     */
    public function isUsed(): bool
    {
        return $this->usedAt !== null;
    }

    /**
     * Returns true only when the link is both unexpired and has not been used.
     * This is the single authoritative validity check that callers must invoke before accepting a token.
     */
    public function isValid(): bool
    {
        return !$this->isExpired() && !$this->isUsed();
    }
}
