<?php

/* @autogenerated */
declare(strict_types=1);

namespace Civi\Lughauth\Features\Document\SnippetAsset\Application\Usecase\Update;

use Civi\Lughauth\Features\Document\SnippetAsset\Domain\SnippetAssetAttributes;
use Civi\Lughauth\Features\Document\SnippetAsset\Application\Service\Visibility\SnippetAssetEnrichForUpdate;
use Civi\Lughauth\Features\Document\SnippetAsset\Domain\SnippetAsset;

class SnippetAssetUpdateEnrich extends SnippetAssetEnrichForUpdate
{
    public function __construct(
        public readonly SnippetAssetUpdateParams $input,
        public readonly SnippetAsset $current,
        private SnippetAssetAttributes $result
    ) {
    }
    public function getResult(): SnippetAssetAttributes
    {
        return $this->result;
    }
    public function with(SnippetAssetAttributes $result): void
    {
        $this->result = $result;
    }
}
