ALTER TABLE _oauth_session
  ADD COLUMN IF NOT EXISTS ip_address   VARCHAR(45)  NULL,
  ADD COLUMN IF NOT EXISTS user_agent   VARCHAR(500) NULL,
  ADD COLUMN IF NOT EXISTS last_used_at DATETIME     NULL,
  ADD COLUMN IF NOT EXISTS client_name  VARCHAR(200) NULL;
