<?php

# @autogenerated
declare(strict_types=1);

namespace Civi\Lughauth\Features\Access\SecurityDomain\Application\Service\Visibility;

use Civi\Lughauth\Features\Access\SecurityDomain\Domain\SecurityDomainRef;

class SecurityDomainFixedFieldsProposal
{
    public function __construct(
        public array $fields,
        public readonly ?SecurityDomainRef $securityDomainRef
    ) {
    }
}
