<?php

/* @autogenerated */
declare(strict_types=1);

namespace Civi\Lughauth\Features\Access\ClientIdentity\Domain\ValueObject\Accessor;

use Civi\Lughauth\Features\Access\ClientIdentity\Domain\ValueObject\ClientIdentityRolesVO;

trait ClientIdentityRolesAccessor
{
    private ?ClientIdentityRolesVO $_roles = null;
    public function getRoles(): ?string
    {
        return $this->_roles?->value();
    }
    public function roles(): ?ClientIdentityRolesVO
    {
        return $this->_roles;
    }
    public function isRolesChanged(?self $original = null): bool
    {
        return null !== $this->_roles && !$this->_roles->equals($original?->_roles);
    }
    public function withRoles(ClientIdentityRolesVO|string|null $roles): self
    {
        $copy = clone $this;
        $copy->_roles = ClientIdentityRolesVO::from($roles);
        return $copy;
    }
}
