<?php

# @autogenerated
declare(strict_types=1);

namespace Civi\Lughauth\Features\Access\ScopeAttributePermission\Application\Usecase\Update;

use RuntimeException;
use Civi\Lughauth\Features\Access\ScopeAttributePermission\Domain\ScopeAttributePermission;
use Civi\Lughauth\Shared\Exception\ConstraintException;
use Civi\Lughauth\Shared\Value\Validation\ConstraintFail;

class ScopeAttributePermissionUpdateCheck
{
    public function __construct(public readonly ScopeAttributePermissionUpdateParams $input, public readonly ScopeAttributePermission $current)
    {
    }
    public function reject(RuntimeException|ConstraintFail $fail)
    {
        if ($fail instanceof ConstraintFail) {
            throw ConstraintException::ofFail($fail);
        } else {
            throw $fail;
        }
    }
}
