<?php

# @autogenerated
declare(strict_types=1);

namespace Civi\Lughauth\Features\Access\UserConsentedScopes\Domain\Event;

use Override;
use Civi\Lughauth\Features\Access\UserConsentedScopes\Domain\UserConsentedScopes;
use Civi\Lughauth\Shared\Event\PublicEvent;

class UserConsentedScopesUpdateEvent extends UserConsentedScopesEvent implements PublicEvent
{
    public function __construct(
        UserConsentedScopes $payload,
        public readonly UserConsentedScopes $original
    ) {
        parent::__construct($payload);
    }
    #[Override]
    public function eventType(): string
    {
        return 'user-consented-scopes.update';
    }
    #[Override]
    public function schemaVersion(): string
    {
        return 'v1';
    }
    #[Override]
    public function payload(): array
    {
        return $this->payload->asPublicJson();
    }
    #[Override]
    public function original(): array
    {
        return $this->original->asPublicJson();
    }
}
