<?php

/* @autogenerated */
declare(strict_types=1);

namespace Civi\Lughauth\Features\Access\UserProfile\Domain\ValueObject\Accessor;

use Civi\Lughauth\Features\Access\UserProfile\Domain\ValueObject\UserProfilePreferredUsernameVO;

trait UserProfilePreferredUsernameAccessor
{
    private ?UserProfilePreferredUsernameVO $_preferredUsername = null;
    public function getPreferredUsername(): ?string
    {
        return $this->_preferredUsername?->value();
    }
    public function preferredUsername(): ?UserProfilePreferredUsernameVO
    {
        return $this->_preferredUsername;
    }
    public function isPreferredUsernameChanged(?self $original = null): bool
    {
        return null !== $this->_preferredUsername && !$this->_preferredUsername->equals($original?->_preferredUsername);
    }
    public function withPreferredUsername(UserProfilePreferredUsernameVO|string|null $preferredUsername): self
    {
        $copy = clone $this;
        $copy->_preferredUsername = UserProfilePreferredUsernameVO::from($preferredUsername);
        return $copy;
    }
}
