<?php

# @autogenerated
declare(strict_types=1);

namespace Civi\Lughauth\Features\Test\Plan\PlanTenant\Domain\Gateway;

class PlanTenantFilter
{
    public function __construct(
        private ?array $uids = null,
        private ?string $search = null,
        private ?string $name = null,
    ) {
    }
    public function uids(): ?array
    {
        return $this->uids;
    }
    public function withUids(array $uids): self
    {
        $copy = clone $this;
        $copy->uids = $uids;
        return $copy;
    }
    public function search(): ?string
    {
        return $this->search;
    }
    public function withSearch(string $search): self
    {
        $copy = clone $this;
        $copy->search = $search;
        return $copy;
    }
    public function name(): ?string
    {
        return $this->name;
    }
    public function withName($name): self
    {
        $copy = clone $this;
        $copy->name = $name;
        return $copy;
    }
}
