<?php

/* @autogenerated */
declare(strict_types=1);

namespace Civi\Lughauth\Shared\Infrastructure;

use Psr\Container\ContainerInterface;

interface StartupProcess
{
    public function onStartup(ContainerInterface $container): void;
}