<?php

# @autogenerated
declare(strict_types=1);

namespace Civi\Lughauth\Features\Access\ScopeAssignation\Domain\Gateway;

use Civi\Lughauth\Features\Access\ScopeAssignation\Domain\ScopeAssignation;

class ScopeAssignationSlide extends \ArrayIterator
{
    private readonly ?ScopeAssignation $last;
    private readonly ScopeAssignationCursor $nextCursor;
    public function __construct(
        private readonly ?\Closure $next,
        private readonly ?ScopeAssignationCursor $cursor,
        private readonly array $values
    ) {
        parent::__construct($values);
        $this->last = $values ? end($values) : null;
        $this->nextCursor = new ScopeAssignationCursor(
            limit: $this->cursor->limit(),
            sinceUid: $this->last ? $this->last->uid() : null,
        );
    }
    public function cursor(): ?ScopeAssignationCursor
    {
        return $this->cursor;
    }
    public function nextCursor(): ScopeAssignationCursor
    {
        return $this->nextCursor;
    }
    public function values(): array
    {
        return $this->values;
    }
    public function current(): ScopeAssignation
    {
        return parent::current();
    }
    public function map(\Closure $fn): ScopeAssignationSlide
    {
        return new ScopeAssignationSlide($this->next, $this->cursor, array_map($fn, $this->values));
    }
    public function slide(\Closure $fn): ScopeAssignationSlide
    {
        $filtered = array_filter($this->values, $fn);
        $collected = $filtered;
        $last = $this->last;
        $next = $this->next;
        $cursor = $this->cursor;
        if (count($collected) == $cursor->limit()) {
            while (
                count($collected) < count($this->values) && $next
            ) {
                $nextSlide = ($this->next)($this, $cursor->next($last, $cursor->limit()));
                if (count($nextSlide)) {
                    $nextFiltered = array_filter($nextSlide->values, $fn);
                    $collected = array_merge($collected, $nextFiltered);
                    $cursor = $nextSlide->cursor;
                    $next = $nextSlide->next;
                    $last = $nextSlide->last;
                } else {
                    break;
                }
            }
            return new ScopeAssignationSlide($next, $cursor, $collected);
        } else {
            return $this;
        }
    }
}
