<?php

# @autogenerated
declare(strict_types=1);

namespace Civi\Lughauth\Features\Access\User\Domain\ValueObject\Accesor;

use Civi\Lughauth\Features\Access\User\Domain\ValueObject\UserLanguageVO;

trait UserLanguageAccesor
{
    private ?UserLanguageVO $_language = null;
    public function getLanguage(): ?string
    {
        return $this->_language?->value();
    }
    public function language(): ?UserLanguageVO
    {
        return $this->_language;
    }
    public function isLanguageChanged(?self $original = null): bool
    {
        return $this->_language->value() !== ($original ? $original->_language->value() : null);
    }
    public function withLanguage(UserLanguageVO|string|null $language): self
    {
        $copy = clone $this;
        $copy->_language = UserLanguageVO::from($language);
        return $copy;
    }
}
