<?php

/* @autogenerated */
declare(strict_types=1);

namespace Civi\Lughauth\Features\Access\UserConsentPurposes\Domain;

use Civi\Lughauth\Features\Access\UserConsentPurposes\Domain\ValueObject\UserConsentPurposesUidVO;
use Civi\Lughauth\Features\Access\UserConsentPurposes\Domain\ValueObject\UserConsentPurposesUserVO;
use Civi\Lughauth\Features\Access\UserConsentPurposes\Domain\ValueObject\Accessor\UserConsentPurposesUserAccessor;
use Civi\Lughauth\Features\Access\UserConsentPurposes\Domain\ValueObject\UserConsentPurposesConsentPurposeVO;
use Civi\Lughauth\Features\Access\UserConsentPurposes\Domain\ValueObject\Accessor\UserConsentPurposesConsentPurposeAccessor;
use Civi\Lughauth\Features\Access\UserConsentPurposes\Domain\ValueObject\UserConsentPurposesGrantedVO;
use Civi\Lughauth\Features\Access\UserConsentPurposes\Domain\ValueObject\Accessor\UserConsentPurposesGrantedAccessor;
use Civi\Lughauth\Features\Access\UserConsentPurposes\Domain\ValueObject\UserConsentPurposesDecisionAtVO;
use Civi\Lughauth\Features\Access\UserConsentPurposes\Domain\ValueObject\Accessor\UserConsentPurposesDecisionAtAccessor;
use Civi\Lughauth\Features\Access\UserConsentPurposes\Domain\ValueObject\UserConsentPurposesIpAddressVO;
use Civi\Lughauth\Features\Access\UserConsentPurposes\Domain\ValueObject\Accessor\UserConsentPurposesIpAddressAccessor;
use Civi\Lughauth\Features\Access\UserConsentPurposes\Domain\ValueObject\UserConsentPurposesUserAgentVO;
use Civi\Lughauth\Features\Access\UserConsentPurposes\Domain\ValueObject\Accessor\UserConsentPurposesUserAgentAccessor;
use Civi\Lughauth\Features\Access\UserConsentPurposes\Domain\ValueObject\UserConsentPurposesVersionVO;
use Civi\Lughauth\Features\Access\UserConsentPurposes\Domain\ValueObject\Accessor\UserConsentPurposesVersionAccessor;
use Civi\Lughauth\Features\Access\UserConsentPurposes\Domain\Event\UserConsentPurposesCreateEvent;
use Civi\Lughauth\Features\Access\UserConsentPurposes\Domain\Event\UserConsentPurposesUpdateEvent;
use Civi\Lughauth\Features\Access\UserConsentPurposes\Domain\Event\UserConsentPurposesDeleteEvent;
use Civi\Lughauth\Features\Access\User\Domain\UserRef;
use Civi\Lughauth\Features\Access\ConsentPurpose\Domain\ConsentPurposeRef;

class UserConsentPurposes extends UserConsentPurposesRef
{
    use UserConsentPurposesUserAccessor;
    use UserConsentPurposesConsentPurposeAccessor;
    use UserConsentPurposesGrantedAccessor;
    use UserConsentPurposesDecisionAtAccessor;
    use UserConsentPurposesIpAddressAccessor;
    use UserConsentPurposesUserAgentAccessor;
    use UserConsentPurposesVersionAccessor;
    private array $recordedEvents = [];

    public function __construct(
        UserConsentPurposesUidVO|string $uid,
        UserConsentPurposesUserVO|UserRef $user,
        UserConsentPurposesConsentPurposeVO|ConsentPurposeRef $consentPurpose,
        UserConsentPurposesGrantedVO|bool $granted,
        UserConsentPurposesDecisionAtVO|\DateTimeImmutable|null $decisionAt = null,
        UserConsentPurposesIpAddressVO|string|null $ipAddress = null,
        UserConsentPurposesUserAgentVO|string|null $userAgent = null,
        UserConsentPurposesVersionVO|int|null $version = null,
    ) {
        parent::__construct($uid);
        $this->_user = UserConsentPurposesUserVO::from($user);
        $this->_consentPurpose = UserConsentPurposesConsentPurposeVO::from($consentPurpose);
        $this->_granted = UserConsentPurposesGrantedVO::from($granted);
        $this->_decisionAt = null === $decisionAt ? UserConsentPurposesDecisionAtVO::empty() : UserConsentPurposesDecisionAtVO::from($decisionAt);
        $this->_ipAddress = null === $ipAddress ? UserConsentPurposesIpAddressVO::empty() : UserConsentPurposesIpAddressVO::from($ipAddress);
        $this->_userAgent = null === $userAgent ? UserConsentPurposesUserAgentVO::empty() : UserConsentPurposesUserAgentVO::from($userAgent);
        $this->_version = null === $version ? UserConsentPurposesVersionVO::empty() : UserConsentPurposesVersionVO::from($version);
    }
    public function replace(UserConsentPurposesAttributes $values): UserConsentPurposes
    {
        $value = clone $this;
        $value->_user = $values->getUserOrCurrent($this->_user);
        $value->_consentPurpose = $values->getConsentPurposeOrCurrent($this->_consentPurpose);
        $value->_granted = $values->getGrantedOrCurrent($this->_granted);
        $value->_decisionAt = $values->getDecisionAtOrCurrent($this->_decisionAt);
        $value->_ipAddress = $values->getIpAddressOrCurrent($this->_ipAddress);
        $value->_userAgent = $values->getUserAgentOrCurrent($this->_userAgent);
        $value->_version = $values->getVersionOrCurrent($this->_version);
        return $value;
    }
    public static function calculatedFields(): array
    {
        return [];
    }
    public static function create(UserConsentPurposesAttributes $values): UserConsentPurposes
    {
        $value = $values->createNewInstance();
        $value->recordedEvents[] = new UserConsentPurposesCreateEvent($value);
        return $value;
    }
    public function update(UserConsentPurposesAttributes $values): UserConsentPurposes
    {
        $value = $this->replace($values);
        $value->recordedEvents[] = new UserConsentPurposesUpdateEvent($value, $this);
        return $value;
    }
    public function delete(): UserConsentPurposes
    {
        $value = clone $this;
        $value->recordedEvents[] = new UserConsentPurposesDeleteEvent($value);
        return $value;
    }
    public function asPublicJson(): array
    {
        $data = [];
        $data['uid'] = $this->uid();
        $data['user'] = [ '$ref' => $this->getUser()->uid() ];
        $data['consentPurpose'] = [ '$ref' => $this->getConsentPurpose()->uid() ];
        $data['granted'] = $this->isGranted();
        $data['decisionAt'] = $this->getDecisionAt();
        $data['ipAddress'] = $this->getIpAddress();
        $data['userAgent'] = $this->getUserAgent();
        $data['version'] = $this->getVersion();
        return $data;
    }
    public function toAttributes(): UserConsentPurposesAttributes
    {
        return (new UserConsentPurposesAttributes())
          ->uid($this->uid())
          ->user($this->_user)
          ->consentPurpose($this->_consentPurpose)
          ->granted($this->_granted)
          ->decisionAt($this->_decisionAt)
          ->ipAddress($this->_ipAddress)
          ->userAgent($this->_userAgent)
          ->version($this->_version);
    }
    public function getTheEvents(): array
    {
        return [...$this->recordedEvents];
    }
}
