<?php

# @autogenerated
declare(strict_types=1);

namespace Civi\Lughauth\Features\Access\Master\ApiKeyClient\Application\Usecase\Update;

use Civi\Lughauth\Features\Access\Master\ApiKeyClient\Domain\ApiKeyClientAttributes;
use Civi\Lughauth\Features\Access\Master\ApiKeyClient\Domain\ApiKeyClient;

class ApiKeyClientUpdateEnrich
{
    public function __construct(
        public readonly ApiKeyClientUpdateParams $input,
        public readonly ApiKeyClient $current,
        private ApiKeyClientAttributes $result
    ) {
    }
    public function getResult(): ApiKeyClientAttributes
    {
        return $this->result;
    }  public function with(ApiKeyClientAttributes $result)
    {
        $this->result = $result;
    }
}
