<?php

# @autogenerated
declare(strict_types=1);

namespace Civi\Lughauth\Features\Access\Role\Application\Usecase\Delete;

use Civi\Lughauth\Features\Access\Role\Domain\RoleRef;
use Civi\Lughauth\Shared\Security\Allow;

class RoleDeleteAllowProposal
{
    public function __construct(
        public Allow $allow,
        public ?RoleRef $ref
    ) {
    }
}
