<?php

/* @autogenerated */
declare(strict_types=1);

namespace Civi\Lughauth\Features\Access\TenantConfig\Domain\ValueObject\Accessor;

use Civi\Lughauth\Features\Access\TenantConfig\Domain\ValueObject\TenantConfigMagicLinkEnabledVO;

trait TenantConfigMagicLinkEnabledAccessor
{
    private ?TenantConfigMagicLinkEnabledVO $_magicLinkEnabled = null;
    public function isMagicLinkEnabled(): ?bool
    {
        return $this->_magicLinkEnabled?->value();
    }
    public function magicLinkEnabled(): ?TenantConfigMagicLinkEnabledVO
    {
        return $this->_magicLinkEnabled;
    }
    public function isMagicLinkEnabledChanged(?self $original = null): bool
    {
        return null !== $this->_magicLinkEnabled && !$this->_magicLinkEnabled->equals($original?->_magicLinkEnabled);
    }
    public function withMagicLinkEnabled(TenantConfigMagicLinkEnabledVO|bool|null $magicLinkEnabled): self
    {
        $copy = clone $this;
        $copy->_magicLinkEnabled = TenantConfigMagicLinkEnabledVO::from($magicLinkEnabled);
        return $copy;
    }
}
