<?php

# @autogenerated
declare(strict_types=1);

namespace Civi\Lughauth\Features\Access\TrustedClient\Domain\ValueObject\Accesor;

use Civi\Lughauth\Features\Access\TrustedClient\Domain\ValueObject\TrustedClientAllowedRedirectsVersionVO;

trait TrustedClientAllowedRedirectsVersionAccesor
{
    private ?TrustedClientAllowedRedirectsVersionVO $_version = null;
    public function getVersion(): ?int
    {
        return $this->_version?->value();
    }
    public function version(): ?TrustedClientAllowedRedirectsVersionVO
    {
        return $this->_version;
    }
    public function isVersionChanged(?self $original = null): bool
    {
        return $this->_version->value() !== ($original ? $original->_version->value() : null);
    }
    public function withVersion(TrustedClientAllowedRedirectsVersionVO|int|null $version): self
    {
        $copy = clone $this;
        $copy->_version = TrustedClientAllowedRedirectsVersionVO::from($version);
        return $copy;
    }
}
