<?php

# @autogenerated
declare(strict_types=1);

namespace Civi\Lughauth\Features\Access\User\Application\Usecase\Update;

use RuntimeException;
use Civi\Lughauth\Features\Access\User\Domain\User;
use Civi\Lughauth\Shared\Exception\ConstraintException;
use Civi\Lughauth\Shared\Value\Validation\ConstraintFail;

class UserUpdateCheck
{
    public function __construct(public readonly UserUpdateParams $input, public readonly User $current)
    {
    }
    public function reject(RuntimeException|ConstraintFail $fail)
    {
        if ($fail instanceof ConstraintFail) {
            throw ConstraintException::ofFail($fail);
        } else {
            throw $fail;
        }
    }
}
