<?php

/* @autogenerated */
declare(strict_types=1);

namespace Civi\Lughauth\Features\Document\Rendering\Application\Service;

use Civi\Lughauth\Features\Access\Tenant\Domain\TenantRef;
use Civi\Lughauth\Features\Document\Rendering\Domain\TemplateOutputFormat;
use Civi\Lughauth\Features\Document\Rendering\Domain\TemplateRenderRequest;
use Civi\Lughauth\Features\Document\Rendering\Domain\Gateway\TemplateRenderGateway;
use Civi\Lughauth\Features\Document\Theme\Domain\Theme;
use Civi\Lughauth\Features\Document\Theme\Domain\Gateway\ThemeReadGateway;
use Civi\Lughauth\Features\Document\ThemeVersion\Domain\ThemeVersion;
use Civi\Lughauth\Features\Document\ThemeVersion\Domain\ThemeVersionChannelOptions;
use Civi\Lughauth\Features\Document\ThemeVersion\Domain\Gateway\ThemeVersionFilter;
use Civi\Lughauth\Features\Document\ThemeVersion\Domain\Gateway\ThemeVersionReadGateway;

class ThemeRenderService
{
    /** @var array<string, Theme|null> In-request memo for resolveTheme() to avoid duplicate DB queries. */
    private array $themeCache = [];

    public function __construct(
        private readonly ThemeReadGateway $themeGateway,
        private readonly ThemeVersionReadGateway $themeVersionGateway,
        private readonly TemplateRenderGateway $renderGateway,
        private readonly DocumentAssetDumpService $assetDumpService,
    ) {
    }

    /**
     * Wrap $innerContent in the ThemeVersion HTML for the given theme name and channel.
     *
     * Resolves the theme tenant-specifically first, then falls back to the global theme.
     * Picks the best ThemeVersion using BCP 47 locale negotiation.
     * Returns null when no enabled theme or version is found (caller must handle the fallback).
     *
     * @param array<string, string> $extraVars Additional variables merged into the theme template (title, subject, …).
     */
    public function render(
        string $themeName,
        ThemeVersionChannelOptions $channel,
        string $innerContent,
        ?string $locale,
        ?TenantRef $tenantRef,
        array $extraVars = [],
    ): ?string {
        $theme = $this->resolveTheme($themeName, $tenantRef);
        if ($theme === null) {
            return null;
        }

        $version = $this->bestVersion($theme, $channel, $locale);
        if ($version === null) {
            return null;
        }

        $html = $version->getContentHtml();
        if ($html === null || $html === '') {
            return null;
        }

        $this->assetDumpService->syncThemeAssets($theme);
        $assetsPath = $this->assetDumpService->themeAssetsPath($theme->uid() ?? '');

        $vars = array_merge($extraVars, [
            'slot_content'      => $innerContent,
            'locale'            => $locale ?? '',
            'theme_assets_path' => $assetsPath,
        ]);

        $rendered = $this->renderGateway->render(new TemplateRenderRequest(
            htmlContent: $html,
            snippets: [],
            variables: $vars,
            outputFormat: TemplateOutputFormat::HTML,
            subject: null,
            textContent: null,
            assets: [],
        ));

        return $rendered->htmlContent();
    }

    /**
     * Returns the public URL path to the theme's asset directory, or null when
     * the theme cannot be resolved for the given name + tenant combination.
     */
    public function resolveThemeAssetsPath(string $themeName, ?TenantRef $tenantRef): ?string
    {
        $theme = $this->resolveTheme($themeName, $tenantRef);
        if ($theme === null) {
            return null;
        }
        $this->assetDumpService->syncThemeAssets($theme);
        return $this->assetDumpService->themeAssetsPath($theme->uid() ?? '');
    }

    private function resolveTheme(string $name, ?TenantRef $tenantRef): ?Theme
    {
        $key = $name . '::' . ($tenantRef?->uid() ?? '');
        if (array_key_exists($key, $this->themeCache)) {
            return $this->themeCache[$key];
        }

        $theme = null;
        if ($tenantRef !== null) {
            $candidate = $this->themeGateway->findOneByNameAndTenant($name, $tenantRef);
            if ($candidate !== null && $candidate->isEnabled()) {
                $theme = $candidate;
            }
        }

        if ($theme === null) {
            $candidate = $this->themeGateway->findOneByNameAndTenant($name, null);
            $theme     = ($candidate !== null && $candidate->isEnabled()) ? $candidate : null;
        }

        return $this->themeCache[$key] = $theme;
    }

    private function bestVersion(Theme $theme, ThemeVersionChannelOptions $channel, ?string $locale): ?ThemeVersion
    {
        $all = $this->themeVersionGateway
            ->list((new ThemeVersionFilter())->withTheme($theme))
            ->values();

        $byChannel = array_values(array_filter(
            $all,
            static fn (ThemeVersion $v) => $v->getChannel() === $channel
        ));

        if (empty($byChannel)) {
            return null;
        }

        if ($locale !== null) {
            foreach ($byChannel as $v) {
                if ($v->getLocale() === $locale) {
                    return $v;
                }
            }
            $lang = substr($locale, 0, 2);
            foreach ($byChannel as $v) {
                if ($v->getLocale() !== null && str_starts_with($v->getLocale(), $lang)) {
                    return $v;
                }
            }
        }

        foreach ($byChannel as $v) {
            if ($v->getLocale() === null) {
                return $v;
            }
        }

        return $byChannel[0];
    }
}
