<?php

# @autogenerated
declare(strict_types=1);

namespace Civi\Lughauth\Features\Access\User\Application\Usecase\Accept;

use Override;
use Civi\Lughauth\Shared\Security\Allow;
use Civi\Lughauth\Shared\Security\AllowDecision;
use Civi\Lughauth\Features\Access\User\Domain\UserRef;

class UserAcceptAllowDecision extends AllowDecision
{
    public function __construct(
        Allow $allow,
        private ?UserRef $ref = null
    ) {
        parent::__construct($allow);
    }
    public function ref(): ?UserRef
    {
        return $this->ref;
    }
    #[Override]
    public function actionName(): string
    {
        return "accept";
    }

    #[Override]
    public function resourceName(): string
    {
        return "user";
    }
}
