<?php

/* @autogenerated */
declare(strict_types=1);

use Civi\Lughauth\Features\Document\SnippetVersion\Domain\ValueObject\Holder\SnippetVersionContentHtmlAttributeHolder;
use Civi\Lughauth\Shared\Value\Validation\ConstraintFailList;
use PHPUnit\Framework\TestCase;

/**
 * Unit tests for the SnippetVersionContentHtmlAttributeHolder trait.
 *
 * Covers assignment, retrieval, default fallback,
 * transfer between holders, validation rules, and unset operations.
 */
class SnippetVersionContentHtmlAttributeHolderUnitTest extends TestCase
{
    /**
     * Asserts that the code attribute is not assigned by default
     * and that getContentHtml returns null on a freshly created holder.
     */
    public function testContentHtmlNotAssignedByDefault(): void
    {
        // Arrange
        $holder = new ImplWithSnippetVersionContentHtmlAttributeHolderUnitTest();

        // Assert
        $this->assertFalse($holder->isContentHtmlAssigned());
        $this->assertNull($holder->getContentHtml());
    }
}
class ImplWithSnippetVersionContentHtmlAttributeHolderUnitTest
{
    use SnippetVersionContentHtmlAttributeHolder;
    public function assertRules(ConstraintFailList $errorsList): self
    {
        $result = new self();
        $this->withAssertedContentHtmlRules($result, $errorsList);
        return $result;
    }

    public function applyDefaults(): void
    {
        $this->withDefaultContentHtml();
    }
}
