<?php

# @autogenerated
declare(strict_types=1);

namespace Civi\Lughauth\Features\Access\Tenant\Application\Policy\Allow\Update;

use Throwable;
use Civi\Lughauth\Features\Access\Tenant\Application\Usecase\Update\TenantUpdateAllowDecision;
use Civi\Lughauth\Shared\Context;
use Civi\Lughauth\Shared\Security\Allow;
use Civi\Lughauth\Shared\Observability\LoggerAwareTrait;
use Civi\Lughauth\Shared\Observability\TracerAwareTrait;

class UpdateTenantOnlyForRootAllow
{
    use LoggerAwareTrait;
    use TracerAwareTrait;

    public function __construct(private readonly Context $context)
    {
    }
    public function __invoke(TenantUpdateAllowDecision $proposal): TenantUpdateAllowDecision
    {
        $this->logDebug("Check UpdateTenantOnlyForRootAllow Tenant");
        $span = $this->startSpan("Check UpdateTenantOnlyForRootAllow Tenant");
        try {
            $userContext = $this->context->getIdentity();
            if ($proposal->allow->allowed) {
                $belongs = $userContext->hasAnyRole('ROOT');
                $allowed = $belongs ? Allow::allowed('update', 'Enabled for user UpdateTenantOnlyForRoot') : Allow::disallowed('update', 'Disabled if not UpdateTenantOnlyForRoot');
                $proposal->allow = $allowed;
            }
            return $proposal;
        } catch (Throwable $ex) {
            $span->recordException($ex);
            throw $ex;
        } finally {
            $span->end();
        }
    }
}
