<?php

# @autogenerated
declare(strict_types=1);

namespace Civi\Lughauth\Features\Access\RelyingParty\Application\Usecase\Enable;

use Civi\Lughauth\Features\Access\RelyingParty\Domain\ValueObject\Holder\RelyingPartyUidAttributeHolder;
use Civi\Lughauth\Features\Access\RelyingParty\Domain\ValueObject\Holder\RelyingPartyCodeAttributeHolder;
use Civi\Lughauth\Features\Access\RelyingParty\Domain\ValueObject\Holder\RelyingPartyApiKeyAttributeHolder;
use Civi\Lughauth\Features\Access\RelyingParty\Domain\ValueObject\Holder\RelyingPartyEnabledAttributeHolder;
use Civi\Lughauth\Features\Access\RelyingParty\Domain\ValueObject\Holder\RelyingPartyVersionAttributeHolder;
use Civi\Lughauth\Features\Access\RelyingParty\Domain\RelyingPartyAttributes;

class RelyingPartyEnableResult
{
    use RelyingPartyUidAttributeHolder;
    use RelyingPartyCodeAttributeHolder;
    use RelyingPartyApiKeyAttributeHolder;
    use RelyingPartyEnabledAttributeHolder;
    use RelyingPartyVersionAttributeHolder;

    private const UNSETS = [
      'uid' => 'unsetUid',
      'code' => 'unsetCode',
      'apiKey' => 'unsetApiKey',
      'enabled' => 'unsetEnabled',
      'version' => 'unsetVersion',
    ];

    public function __construct(RelyingPartyAttributes|null $att = null)
    {
        $this->uid($att->uid);
        $this->code($att->code);
        $this->apiKey($att->apiKey);
        $this->enabled($att->enabled);
        $this->version($att->version);
    }
    public function toAttributes(): RelyingPartyAttributes
    {
        $att = new RelyingPartyAttributes();
        $att->uid($this->uid);
        $att->code($this->code);
        $att->apiKey($this->apiKey);
        $att->enabled($this->enabled);
        $att->version($this->version);
        return $att;
    }
    public function unset($field)
    {
        if (isset(self::UNSETS[$field])) {
            call_user_func([$this, self::UNSETS[$field]]);
        }
    }
    public function withDefaults(): RelyingPartyEnableResult
    {
        $this->withDefaultUid();
        $this->withDefaultCode();
        $this->withDefaultApiKey();
        $this->withDefaultEnabled();
        $this->withDefaultVersion();
        return $this;
    }
}
