<?php

# @autogenerated
declare(strict_types=1);

namespace Civi\Lughauth\Features\Access\Tenant\Application\Usecase\Update;

use Civi\Lughauth\Shared\Security\Allow;
use Civi\Lughauth\Shared\Security\AllowDecision;

class TenantUpdateAllowDecision extends AllowDecision
{
    public function __construct(
        public Allow $allow
    ) {
    }
    public function actionName(): string
    {
        return "update";
    }

    public function resourceName(): string
    {
        return "tenant";
    }
}
