<?php

# @autogenerated
declare(strict_types=1);

namespace Civi\Lughauth\Features\Access\Tenant\Domain\Gateway;

use Override;
use ArrayIterator;
use Civi\Lughauth\Features\Access\Tenant\Domain\Tenant;

/**
 * @template-extends ArrayIterator<int, Tenant>
 */
class TenantSlide extends \ArrayIterator
{
    private readonly ?Tenant $last;
    private readonly TenantCursor $nextCursor;
    public function __construct(
        private readonly ?\Closure $next,
        private readonly ?TenantCursor $cursor,
        private readonly array $values
    ) {
        parent::__construct($values);
        $this->last = $values ? end($values) : null;
        $cursor = $this->cursor;
        $last = $this->last;
        $this->nextCursor = new TenantCursor(
            limit: null === $cursor ? 1000 : $cursor->limit(),
            sinceUid: null == $last ? null : $last->uid(),
            sinceName: null === $last ? null : $last->getName(),
            sinceDomain: null === $last ? null : $last->getDomain(),
        );
    }
    public function cursor(): ?TenantCursor
    {
        return $this->cursor;
    }
    public function nextCursor(): TenantCursor
    {
        return $this->nextCursor;
    }
    public function values(): array
    {
        return $this->values;
    }
    #[Override]
    public function current(): ?Tenant
    {
        return parent::current();
    }
    public function map(\Closure $fn): TenantSlide
    {
        return new TenantSlide($this->next, $this->cursor, array_map($fn, $this->values));
    }
    public function slide(\Closure $fn): TenantSlide
    {
        $filtered = array_filter($this->values, $fn);
        $collected = $filtered;
        $last = $this->last;
        $next = $this->next;
        $cursor = $this->cursor;
        if (null !== $cursor && count($collected) == $cursor->limit()) {
            while (count($collected) < count($this->values) && $next !== null) {
                if ($last === null) {
                    break;
                }
                $nextSlide = $next($this, $cursor->next($last, $cursor->limit()));
                if (count($nextSlide)) {
                    $nextFiltered = array_filter($nextSlide->values, $fn);
                    $collected = array_merge($collected, $nextFiltered);
                    $cursor = $nextSlide->cursor;
                    $next = $nextSlide->next;
                    $last = $nextSlide->last;
                } else {
                    break;
                }
            }
            return new TenantSlide($next, $cursor, $collected);
        } else {
            return $this;
        }
    }
}
