<?php

/* @autogenerated */
declare(strict_types=1);

namespace Civi\Lughauth\Features\Document\Snippet\Application\Service\Visibility;

use Civi\Lughauth\Features\Document\Snippet\Domain\SnippetAttributes;
use Civi\Lughauth\Features\Document\Snippet\Domain\Snippet;

class SnippetEnrichForView
{
    public function __construct(
        public readonly Snippet $snippet,
        public readonly bool $inlist,
        private SnippetAttributes $snippetAttributes
    ) {
    }
    public function getAttributes(): SnippetAttributes
    {
        return $this->snippetAttributes;
    }
    public function with(SnippetAttributes $snippetAttributes): void
    {
        $this->snippetAttributes = $snippetAttributes;
    }
}
