<?php

/* @autogenerated */
declare(strict_types=1);

namespace Civi\Lughauth\Features\Oidc\User\Application\Usecase;

use Civi\Lughauth\Features\Oidc\Authentication\Domain\AuthenticationRequest;
use Civi\Lughauth\Features\Oidc\Authentication\Domain\AuthenticationResult;
use Civi\Lughauth\Features\Oidc\Authentication\Domain\ChallengesState;
use Civi\Lughauth\Features\Oidc\User\Domain\Gateway\LoginGateway;

class LoginUsecase
{
    public function __construct(
        private readonly LoginGateway $gateway
    ) {
    }

    public function fillPreLoadById(
        string $tenant,
        AuthenticationRequest $client,
        ChallengesState $challenges
    ): AuthenticationResult {
        return $this->gateway->fillPreLoadById($tenant, $client, $challenges);
    }

    public function fillPreAuthenticated(
        string $tenant,
        AuthenticationRequest $client,
        ChallengesState $challenges
    ): AuthenticationResult {
        return $this->gateway->fillPreAuthenticated($tenant, $client, $challenges);
    }

    public function validatedUserData(
        string $tenant,
        string $username,
        string $password,
        AuthenticationRequest $client
    ): AuthenticationResult {
        return $this->gateway->validatedUserData($tenant, $username, $password, $client);
    }
}
