<?php

# @autogenerated
declare(strict_types=1);

use Civi\Lughauth\Features\Access\User\Domain\UserRef;
use Civi\Lughauth\Features\Access\RelyingParty\Domain\RelyingPartyRef;
use Civi\Lughauth\Features\Access\TrustedClient\Domain\TrustedClientRef;
use Civi\Lughauth\Features\Access\UserIdentity\Domain\ValueObject\UserIdentityRolesListRef;
use Civi\Lughauth\Features\Access\UserIdentity\Domain\ValueObject\UserIdentityRolesUidVO;
use Civi\Lughauth\Features\Access\UserIdentity\Domain\ValueObject\UserIdentityRolesRoleVO;
use Civi\Lughauth\Features\Access\Role\Domain\RoleRef;
use Civi\Lughauth\Features\Access\UserIdentity\Domain\ValueObject\UserIdentityRolesVersionVO;
use Civi\Lughauth\Features\Access\UserIdentity\Domain\ValueObject\UserIdentityRolesItem;
use PHPUnit\Framework\TestCase;
use Civi\Lughauth\Features\Access\UserIdentity\Domain\UserIdentity;

final class UserIdentityUnitTest extends TestCase
{
    public function test_init_store_values(): void
    {
        // @Arrange
        $one = new UserIdentity(
            uid: 'one',
            user: $this->getMockBuilder(UserRef::class)->setConstructorArgs(['one'])->getMock(),
            relyingParty: $this->getMockBuilder(RelyingPartyRef::class)->setConstructorArgs(['one'])->getMock(),
            trustedClient: $this->getMockBuilder(TrustedClientRef::class)->setConstructorArgs(['one'])->getMock(),
            roles: new UserIdentityRolesListRef(new UserIdentityRolesItem(
                UserIdentityRolesUidVO::from('one'),
                UserIdentityRolesRoleVO::from($this->getMockBuilder(RoleRef::class)->setConstructorArgs(['one'])->getMock()),
                UserIdentityRolesVersionVO::from(1)
            )),
            version: 1,
        );

        // @Act
        $other = $one->toAttributes()->build();

        // @Assert
        $this->assertEquals($one->uid(), $other->uid());
        $this->assertEquals($one->getUser(), $other->getUser());
        $this->assertTrue($one->isUserChanged());
        $this->assertEquals($one->getRelyingParty(), $other->getRelyingParty());
        $this->assertTrue($one->isRelyingPartyChanged());
        $this->assertEquals($one->getTrustedClient(), $other->getTrustedClient());
        $this->assertTrue($one->isTrustedClientChanged());
        $this->assertEquals($one->getRoles(), $other->getRoles());
        $this->assertTrue($one->isRolesChanged());
        $this->assertEquals($one->getVersion(), $other->getVersion());
        $this->assertTrue($one->isVersionChanged());
    }
    public function test_replace_change_values(): void
    {
        // @Arrange
        $base = new UserIdentity(
            uid: 'one',
            user: $this->getMockBuilder(UserRef::class)->setConstructorArgs(['one'])->getMock(),
            relyingParty: $this->getMockBuilder(RelyingPartyRef::class)->setConstructorArgs(['one'])->getMock(),
            trustedClient: $this->getMockBuilder(TrustedClientRef::class)->setConstructorArgs(['one'])->getMock(),
            roles: new UserIdentityRolesListRef(new UserIdentityRolesItem(
                UserIdentityRolesUidVO::from('one'),
                UserIdentityRolesRoleVO::from($this->getMockBuilder(RoleRef::class)->setConstructorArgs(['one'])->getMock()),
                UserIdentityRolesVersionVO::from(1)
            )),
            version: 1,
        );
        $other = new UserIdentity(
            uid: 'other',
            user: $this->getMockBuilder(UserRef::class)->setConstructorArgs(['other'])->getMock(),
            relyingParty: $this->getMockBuilder(RelyingPartyRef::class)->setConstructorArgs(['other'])->getMock(),
            trustedClient: $this->getMockBuilder(TrustedClientRef::class)->setConstructorArgs(['other'])->getMock(),
            roles: new UserIdentityRolesListRef(new UserIdentityRolesItem(
                UserIdentityRolesUidVO::from('other'),
                UserIdentityRolesRoleVO::from($this->getMockBuilder(RoleRef::class)->setConstructorArgs(['other'])->getMock()),
                UserIdentityRolesVersionVO::from(2)
            )),
            version: 2,
        );

        // @Act
        $one = $base->replace($other->toAttributes());

        // @Assert
        $this->assertEquals($one->uid(), $base->uid());
        $this->assertEquals($one->getUser(), $other->getUser());
        $this->assertTrue($one->isUserChanged($base));
        $this->assertEquals($one->getRelyingParty(), $other->getRelyingParty());
        $this->assertTrue($one->isRelyingPartyChanged($base));
        $this->assertEquals($one->getTrustedClient(), $other->getTrustedClient());
        $this->assertTrue($one->isTrustedClientChanged($base));
        $this->assertEquals($one->getRoles(), $other->getRoles());
        $this->assertTrue($one->isRolesChanged($base));
        $this->assertEquals($one->getVersion(), $other->getVersion());
        $this->assertTrue($one->isVersionChanged($base));
    }
    public function test_create_store_values(): void
    {
        // @Arrange
        $one = new UserIdentity(
            uid: 'one',
            user: $this->getMockBuilder(UserRef::class)->setConstructorArgs(['one'])->getMock(),
            relyingParty: $this->getMockBuilder(RelyingPartyRef::class)->setConstructorArgs(['one'])->getMock(),
            trustedClient: $this->getMockBuilder(TrustedClientRef::class)->setConstructorArgs(['one'])->getMock(),
            roles: new UserIdentityRolesListRef(new UserIdentityRolesItem(
                UserIdentityRolesUidVO::from('one'),
                UserIdentityRolesRoleVO::from($this->getMockBuilder(RoleRef::class)->setConstructorArgs(['one'])->getMock()),
                UserIdentityRolesVersionVO::from(1)
            )),
            version: 1,
        );

        // @Act
        $other = UserIdentity::create($one->toAttributes());

        // @Assert
        $this->assertEquals($one->uid(), $other->uid());
        $this->assertEquals($one->getUser(), $other->getUser());
        $this->assertTrue($one->isUserChanged());
        $this->assertEquals($one->getRelyingParty(), $other->getRelyingParty());
        $this->assertTrue($one->isRelyingPartyChanged());
        $this->assertEquals($one->getTrustedClient(), $other->getTrustedClient());
        $this->assertTrue($one->isTrustedClientChanged());
        $this->assertEquals($one->getRoles(), $other->getRoles());
        $this->assertTrue($one->isRolesChanged());
        $this->assertEquals($one->getVersion(), $other->getVersion());
        $this->assertTrue($one->isVersionChanged());
        $this->assertCount(0, $one->getTheEvents());
        $this->assertCount(1, $other->getTheEvents());
    }
    public function test_update_change_values(): void
    {
        $base = new UserIdentity(
            uid: 'one',
            user: $this->getMockBuilder(UserRef::class)->setConstructorArgs(['one'])->getMock(),
            relyingParty: $this->getMockBuilder(RelyingPartyRef::class)->setConstructorArgs(['one'])->getMock(),
            trustedClient: $this->getMockBuilder(TrustedClientRef::class)->setConstructorArgs(['one'])->getMock(),
            roles: new UserIdentityRolesListRef(new UserIdentityRolesItem(
                UserIdentityRolesUidVO::from('one'),
                UserIdentityRolesRoleVO::from($this->getMockBuilder(RoleRef::class)->setConstructorArgs(['one'])->getMock()),
                UserIdentityRolesVersionVO::from(1)
            )),
            version: 1,
        );
        $other = new UserIdentity(
            uid: 'other',
            user: $this->getMockBuilder(UserRef::class)->setConstructorArgs(['other'])->getMock(),
            relyingParty: $this->getMockBuilder(RelyingPartyRef::class)->setConstructorArgs(['other'])->getMock(),
            trustedClient: $this->getMockBuilder(TrustedClientRef::class)->setConstructorArgs(['other'])->getMock(),
            roles: new UserIdentityRolesListRef(new UserIdentityRolesItem(
                UserIdentityRolesUidVO::from('other'),
                UserIdentityRolesRoleVO::from($this->getMockBuilder(RoleRef::class)->setConstructorArgs(['other'])->getMock()),
                UserIdentityRolesVersionVO::from(2)
            )),
            version: 2,
        );

        // @Act
        $one = $base->update($other->toAttributes());

        // @Assert
        $this->assertEquals($one->uid(), $base->uid());
        $this->assertEquals($one->getUser(), $other->getUser());
        $this->assertTrue($one->isUserChanged($base));
        $this->assertEquals($one->getRelyingParty(), $other->getRelyingParty());
        $this->assertTrue($one->isRelyingPartyChanged($base));
        $this->assertEquals($one->getTrustedClient(), $other->getTrustedClient());
        $this->assertTrue($one->isTrustedClientChanged($base));
        $this->assertEquals($one->getRoles(), $other->getRoles());
        $this->assertTrue($one->isRolesChanged($base));
        $this->assertEquals($one->getVersion(), $other->getVersion());
        $this->assertTrue($one->isVersionChanged($base));
        $this->assertCount(0, $other->getTheEvents());
        $this->assertCount(1, $one->getTheEvents());
    }
    public function test_delete_store_values(): void
    {
        // @Arrange
        $one = new UserIdentity(
            uid: 'one',
            user: $this->getMockBuilder(UserRef::class)->setConstructorArgs(['one'])->getMock(),
            relyingParty: $this->getMockBuilder(RelyingPartyRef::class)->setConstructorArgs(['one'])->getMock(),
            trustedClient: $this->getMockBuilder(TrustedClientRef::class)->setConstructorArgs(['one'])->getMock(),
            roles: new UserIdentityRolesListRef(new UserIdentityRolesItem(
                UserIdentityRolesUidVO::from('one'),
                UserIdentityRolesRoleVO::from($this->getMockBuilder(RoleRef::class)->setConstructorArgs(['one'])->getMock()),
                UserIdentityRolesVersionVO::from(1)
            )),
            version: 1,
        );

        // @Act
        $other = $one->delete();

        // @Assert
        $this->assertEquals($one->uid(), $other->uid());
        $this->assertEquals($one->getUser(), $other->getUser());
        $this->assertTrue($one->isUserChanged());
        $this->assertEquals($one->getRelyingParty(), $other->getRelyingParty());
        $this->assertTrue($one->isRelyingPartyChanged());
        $this->assertEquals($one->getTrustedClient(), $other->getTrustedClient());
        $this->assertTrue($one->isTrustedClientChanged());
        $this->assertEquals($one->getRoles(), $other->getRoles());
        $this->assertTrue($one->isRolesChanged());
        $this->assertEquals($one->getVersion(), $other->getVersion());
        $this->assertTrue($one->isVersionChanged());
    }
}
