<?php

/* @autogenerated */
declare(strict_types=1);

use PHPUnit\Framework\TestCase;
use Civi\Lughauth\Features\Access\UserConsentedScopes\Domain\UserConsentedScopesRef;

final class UserConsentedScopesRefUnitTest extends TestCase
{
    public function test(): void
    {
        $uid = 'uid';
        $ref = new UserConsentedScopesRef(uid: $uid);
        $this->assertSame($uid, $ref->uid());
    }
}
