<?php

/* @autogenerated */
declare(strict_types=1);

namespace Civi\Lughauth\Features\Document\TemplateVariable\Infrastructure\Driver;

use Psr\Container\ContainerInterface;
use Override;
use Slim\Routing\RouteCollectorProxy;
use Civi\Lughauth\Features\Document\TemplateVariable\Infrastructure\Driver\Rest\TemplateVariableAllowController;
use Civi\Lughauth\Features\Document\TemplateVariable\Infrastructure\Driver\Rest\TemplateVariableListController;
use Civi\Lughauth\Features\Document\TemplateVariable\Infrastructure\Driver\Rest\TemplateVariableCreateController;
use Civi\Lughauth\Features\Document\TemplateVariable\Infrastructure\Driver\Rest\TemplateVariableRetrieveController;
use Civi\Lughauth\Features\Document\TemplateVariable\Infrastructure\Driver\Rest\TemplateVariableUpdateController;
use Civi\Lughauth\Features\Document\TemplateVariable\Infrastructure\Driver\Rest\TemplateVariableDeleteController;
use Civi\Lughauth\Features\Document\TemplateVariable\Infrastructure\Driver\Rest\TemplateVariableEnableController;
use Civi\Lughauth\Features\Document\TemplateVariable\Infrastructure\Driver\Rest\TemplateVariableDisableController;
use Civi\Lughauth\Shared\Security\Rbac\Handler;
use Civi\Lughauth\Shared\Infrastructure\MicroPlugin;
use Civi\Lughauth\Shared\Security\SecurityPlugin;
use Civi\Lughauth\Shared\Infrastructure\StartupProcessor;
use Civi\Lughauth\Shared\Event\EventListenersRegistrarInterface;
use Civi\Lughauth\Features\Document\TemplateVariable\Application\Service\Visibility\TemplateVariableRestrictFilterToVisibility;
use Civi\Lughauth\Features\Document\TemplateVariable\Application\Policy\Filter\TenantAccesible;
use Civi\Lughauth\Features\Document\TemplateVariable\Application\Policy\Fields\FixTenantExcludingRoot;
use Civi\Lughauth\Features\Document\TemplateVariable\Application\Service\Visibility\TemplateVariableCollectNonEditableFields;
use Civi\Lughauth\Features\Document\TemplateVariable\Infrastructure\Driven\TemplateVariableReadRepositoryAdapter;
use Civi\Lughauth\Features\Document\TemplateVariable\Infrastructure\Driven\TemplateVariableWriteRepositoryAdapter;
use Civi\Lughauth\Features\Document\TemplateVariable\Domain\Gateway\TemplateVariableReadGateway;
use Civi\Lughauth\Features\Document\TemplateVariable\Domain\Gateway\TemplateVariableWriteGateway;

class TemplateVariablePlugin extends MicroPlugin
{
    #[Override]
    public function registerServiceDefinition(array $def): array
    {
        $def[TemplateVariableReadGateway::class] = \DI\autowire(TemplateVariableReadRepositoryAdapter::class);
        $def[TemplateVariableWriteGateway::class] = \DI\autowire(TemplateVariableWriteRepositoryAdapter::class);
        return $def;
    }
    #[Override]
    public function registerRoutes(RouteCollectorProxy $collector): void
    {
        $collector->group('/api/document/template-variable', [$this, 'setRoutesForTemplateVariable']);
        $collector->group('/api/me/acl/document/template-variable', [$this, 'setRoutesForTemplateVariableAcl']);
    }
    #[Override]
    public function registerEvents(EventListenersRegistrarInterface $listener): void
    {
        $listener->registerListener(TemplateVariableRestrictFilterToVisibility::class, TenantAccesible::class);
        $listener->registerListener(TemplateVariableCollectNonEditableFields::class, FixTenantExcludingRoot::class);
    }
    #[Override]
    public function registerStartup(StartupProcessor $processor): void
    {
        $processor->register(function (ContainerInterface $container) {
            $handler = $container->get(Handler::class);
            $handler->registerResourceAction("template-variable", "list", "READ");
            $handler->registerResourceAction("template-variable", "create", "WRITE");
            $handler->registerResourceAction("template-variable", "retrieve", "READ");
            $handler->registerResourceAction("template-variable", "update", "WRITE");
            $handler->registerResourceAction("template-variable", "delete", "WRITE");
            $handler->registerResourceAction("template-variable", "enable", "WRITE");
            $handler->registerResourceAction("template-variable", "disable", "WRITE");

            $handler->registerResourceAttribute("template-variable", "code", "MANAGE");
            $handler->registerResourceAttribute("template-variable", "tenant", "MANAGE");
            $handler->registerResourceAttribute("template-variable", "type", "MANAGE");
            $handler->registerResourceAttribute("template-variable", "value", "MANAGE");
            $handler->registerResourceAttribute("template-variable", "enabled", "MANAGE");
            $handler->registerResourceAttribute("template-variable", "version", "MANAGE");
        }, StartupProcessor::before(SecurityPlugin::STARTUP_ORDER));
    }
    public function setRoutesForTemplateVariableAcl(RouteCollectorProxy $templateVariableGroup): void
    {
        $templateVariableGroup->get('', [TemplateVariableAllowController::class, 'genericAllow']);
        $templateVariableGroup->get('/{uid}', [TemplateVariableAllowController::class, 'contextualAllow']);
    }
    public function setRoutesForTemplateVariable(RouteCollectorProxy $templateVariableGroup): void
    {
        $templateVariableGroup->get('', [TemplateVariableListController::class, 'list']);
        $templateVariableGroup->post('', [TemplateVariableCreateController::class, 'create']);
        $templateVariableGroup->get('/{uid}', [TemplateVariableRetrieveController::class, 'retrieve']);
        $templateVariableGroup->put('/{uid}', [TemplateVariableUpdateController::class, 'update']);
        $templateVariableGroup->delete('/{uid}', [TemplateVariableDeleteController::class, 'delete']);
        $templateVariableGroup->delete('', [TemplateVariableDeleteController::class, 'deleteAllForQuery']);
        $templateVariableGroup->get('/~/delete-status/{uid}', [TemplateVariableDeleteController::class, 'checkDeleteAllForQueryStatus']);
        $templateVariableGroup->patch('/~/enable', [TemplateVariableEnableController::class, 'enableAllForQuery']);
        $templateVariableGroup->patch('/{uid}/enable', [TemplateVariableEnableController::class, 'enable']);
        $templateVariableGroup->get('/~/enable-status/{uid}', [TemplateVariableEnableController::class, 'checkEnableAllForQueryStatus']);
        $templateVariableGroup->patch('/~/disable', [TemplateVariableDisableController::class, 'disableAllForQuery']);
        $templateVariableGroup->patch('/{uid}/disable', [TemplateVariableDisableController::class, 'disable']);
        $templateVariableGroup->get('/~/disable-status/{uid}', [TemplateVariableDisableController::class, 'checkDisableAllForQueryStatus']);
    }
}
