<?php

# @autogenerated
declare(strict_types=1);

namespace Civi\Lughauth\Features\Document\TemplateSnippet\Application\Usecase\Disable;

use Psr\EventDispatcher\EventDispatcherInterface;
use Throwable;
use Civi\Lughauth\Shared\Security\Allow;
use Civi\Lughauth\Shared\Exception\UnauthorizedException;
use Civi\Lughauth\Shared\Exception\NotFoundException;
use Civi\Lughauth\Features\Document\TemplateSnippet\Domain\TemplateSnippetRef;
use Civi\Lughauth\Features\Document\TemplateSnippet\Application\Service\Visibility\TemplateSnippetVisibilityService;
use Civi\Lughauth\Features\Document\TemplateSnippet\Domain\Gateway\TemplateSnippetWriteGateway;
use Civi\Lughauth\Shared\Observability\LoggerAwareTrait;
use Civi\Lughauth\Shared\Observability\TracerAwareTrait;

class TemplateSnippetDisableUsecase
{
    use LoggerAwareTrait;
    use TracerAwareTrait;

    public function __construct(
        private readonly EventDispatcherInterface $dispatcher,
        private readonly TemplateSnippetVisibilityService $visibility,
        private readonly TemplateSnippetWriteGateway $writer,
    ) {
    }

    public function allowDisable(?TemplateSnippetRef $ref = null): Allow
    {
        $this->logDebug("Check allow of Disable usecase for Template snippet");
        $span = $this->startSpan("Check allow of Disable usecase for Template snippet");
        try {
            $result = $this->dispatcher->dispatch(new TemplateSnippetDisableAllowDecision(Allow::allowed('disable', 'Allowed to Template snippet by default')));
            return $result->getAllow();
        } catch (Throwable $ex) {
            $span->recordException($ex);
            throw $ex;
        } finally {
            $span->end();
        }
    }
    public function disable(string $uid): TemplateSnippetDisableResult
    {
        $this->logDebug("Run Disable usecase for Template snippet");
        $span = $this->startSpan("Run Disable usecase for Template snippet");
        try {
            $ref = new TemplateSnippetRef($uid);
            $allow = $this->allowDisable($ref);
            if (!$allow->allowed) {
                throw new UnauthorizedException($allow->reason ?? 'Not allowed to Disable Template snippet');
            }
            if (!$original = $this->visibility->retrieveVisibleForUpdate($ref)) {
                throw new NotFoundException($uid);
            }
            $this->dispatcher->dispatch(new TemplateSnippetDisableCheck($original));
            $modified = $original->disable();
            $result = $this->writer->update($original, $modified);
            $output = $this->visibility->copyWithHidden($this->visibility->prepareVisibleData($result));
            return new TemplateSnippetDisableResult($output);
        } catch (Throwable $ex) {
            $span->recordException($ex);
            throw $ex;
        } finally {
            $span->end();
        }
    }
}
