<?php

/* @autogenerated */
declare(strict_types=1);

namespace Civi\Lughauth\Features\OAuth\Authentication\Infrastructure\Driver\Html;

use Civi\Lughauth\Features\OAuth\Authentication\Domain\AuthenticationResult;
use Civi\Lughauth\Features\OAuth\Authentication\Domain\StepInput;
use Civi\Lughauth\Features\OAuth\Authentication\Domain\StepName;
use Civi\Lughauth\Features\OAuth\Authentication\Domain\StepResult;
use Civi\Lughauth\Features\OAuth\Authentication\Infrastructure\Driver\Html\Forms\StepForm;
use Civi\Lughauth\Features\OAuth\Authentication\Infrastructure\Driver\Html\Forms\TermsAndGdprConsentForm;
use Civi\Lughauth\Features\OAuth\Authentication\Infrastructure\Driver\Html\Forms\ScopeConsentForm;
use Civi\Lughauth\Features\OAuth\Authentication\Infrastructure\Driver\Html\Forms\LoginForm;
use Civi\Lughauth\Features\OAuth\Authentication\Infrastructure\Driver\Html\Forms\NewMfaForm;
use Civi\Lughauth\Features\OAuth\Authentication\Infrastructure\Driver\Html\Forms\NewPassForm;
use Civi\Lughauth\Features\OAuth\Authentication\Infrastructure\Driver\Html\Forms\UseMfaForm;
use Civi\Lughauth\Features\OAuth\Authentication\Infrastructure\Driver\Html\Forms\RecoverPassForm;
use Civi\Lughauth\Features\OAuth\Authentication\Infrastructure\Driver\Html\Forms\DelegateForm;
use Civi\Lughauth\Features\OAuth\Authentication\Infrastructure\Driver\Html\Forms\RegisterUserForm;
use Civi\Lughauth\Features\OAuth\Authentication\Infrastructure\Driver\Html\Forms\WebAuthnLoginForm;
use Civi\Lughauth\Features\OAuth\Authentication\Infrastructure\Driver\Html\Forms\MagicLinkLoginForm;
use Psr\Http\Message\ResponseInterface;

/**
 * Dispatcher that maps the current authentication step name or error code to the correct StepForm.
 *
 * OidcStepRouter acts as the central hub for the multi-step interactive login flow. It
 * maintains a registry of all available StepForm implementations keyed by their StepName
 * value, and an ERROR_MAP that translates AuthenticationResult error codes to the step that
 * should handle them (e.g. ERR_MFA_REQUIRED → MFA step, ERR_CONSENT_REQUIRED → consent step).
 *
 * Resolution priority is: explicit step name from the request body → error-code mapping →
 * configured fallback step (defaults to LOGIN). This allows any part of the flow to redirect
 * to the correct form without the caller needing to know which concrete class handles it.
 *
 * The run method combines resolution with execution: when a verified CSRF token (csid) is
 * present it delegates to authenticate(), otherwise to render(). AuthorizeHtml uses this
 * class exclusively for all step dispatch.
 */
final class OidcStepRouter
{
    /** @var array<string, StepForm> */
    private array $steps;

    /**
     * Maps AuthenticationResult error codes to the StepName value that should handle them.
     *
     * When an authentication attempt fails with one of these codes, the router automatically
     * forwards to the form registered under the mapped step name rather than the login fallback.
     */
    /** @var array<string, string> */
    private const ERROR_MAP = [
        AuthenticationResult::ERR_CONSENT_REQUIRED => StepName::CONSENT->value,
        AuthenticationResult::ERR_SCOPES_CONSENT_REQUIRED => StepName::SCOPES_CONSENT->value,
        AuthenticationResult::ERR_MFA_REQUIRED => StepName::MFA->value,
        AuthenticationResult::ERR_NEW_MFA_REQUIRED => StepName::NEW_MFA->value,
        AuthenticationResult::ERR_NEW_PASSWORD_REQUIRED => StepName::NEW_PASS->value,
        AuthenticationResult::ERR_WAITING_PASSCHANGE_CODE => StepName::RECOVER_PASS->value,
        AuthenticationResult::ERR_WAITING_USER_VERIFY => StepName::REGISTER_USER->value,
        AuthenticationResult::ERR_UNKNOW_USER => StepName::LOGIN->value,
        AuthenticationResult::ERR_WRONG_CREDENTIAL => StepName::LOGIN->value,
        AuthenticationResult::ERR_NOT_ALLOWED_ACCESS => StepName::LOGIN->value,
        AuthenticationResult::ERR_MAGIC_LINK_SENT => StepName::MAGIC_LINK->value,
    ];

    public function __construct(
        TermsAndGdprConsentForm $conset,
        ScopeConsentForm $scopesConsent,
        LoginForm $login,
        NewMfaForm $mfa,
        NewPassForm $pass,
        UseMfaForm $useMfa,
        RecoverPassForm $recover,
        DelegateForm $delegate,
        RegisterUserForm $register,
        WebAuthnLoginForm $webAuthnLogin,
        MagicLinkLoginForm $magicLinkLogin,
        private readonly string $fallbackStep = StepName::LOGIN->value
    ) {
        $this->steps = [
            StepName::LOGIN->value => $login,
            StepName::CONSENT->value => $conset,
            StepName::SCOPES_CONSENT->value => $scopesConsent,
            StepName::MFA->value => $useMfa,
            StepName::NEW_MFA->value => $mfa,
            StepName::RECOVER_PASS->value => $recover,
            StepName::NEW_PASS->value => $pass,
            StepName::REGISTER_USER->value => $register,
            StepName::DELEGATED_LOGIN->value => $delegate,
            StepName::WEBAUTHN_LOGIN->value => $webAuthnLogin,
            StepName::MAGIC_LINK->value => $magicLinkLogin,
        ];
    }

    /**
     * Resolves the StepForm responsible for the given step name and/or authentication error.
     *
     * Returns the form registered under the explicit step key when present, otherwise falls
     * back to the error-code mapping, and finally to the configured fallback step. Returns
     * null only if the fallback step itself is not registered.
     */
    public function resolve(?string $step, ?AuthenticationResult $error): ?StepForm
    {
        $key = $this->normalizeStep($step);
        if ($key !== null && isset($this->steps[$key])) {
            return $this->steps[$key];
        }

        $errorKey = $error?->error;
        if ($errorKey !== null && $errorKey !== '' && isset(self::ERROR_MAP[$errorKey])) {
            $mapped = self::ERROR_MAP[$errorKey];
            return $this->steps[$mapped] ?? null;
        }

        return $this->steps[$this->fallbackStep] ?? null;
    }

    private function normalizeStep(?string $step): string|null
    {
        if ($step === null) {
            return null;
        }

        $step = trim($step);
        return $step === '' ? null : $step;
    }

    /**
     * Resolves the correct StepForm and either authenticates or renders depending on csid presence.
     *
     * When a verified CSRF token (csid) is provided, the csid is injected into the body and
     * the form's authenticate() method is called. Without a csid, the form's render() method
     * is called instead. Returns null if no form can be resolved.
     */
    public function run(StepInput $input, ResponseInterface $response, ?AuthenticationResult $error, ?string $step, ?string $csid): ?StepResult
    {
        $form = $this->resolve($step, $error);
        if (!$form) {
            return null;
        }
        if ($csid !== null) {
            $body = $input->body ?? [];
            $body['csid'] = $csid;
            $input = new StepInput(
                context: $input->context,
                authRequest: $input->authRequest,
                challenges: $input->challenges,
                body: $body,
                request: $input->request
            );

            return $form->authenticate($input);
        }

        return $form->render($input, $response, $error);
    }
}
