<?php

/* @autogenerated */
declare(strict_types=1);

namespace Civi\Lughauth\Features\Oidc\Authentication\Infrastructure\Driver\Html\Forms;

use Override;
use Psr\Http\Message\ResponseInterface;
use Civi\Lughauth\Features\Oidc\Theme\Application\DecorateHtml;
use Civi\Lughauth\Features\Oidc\Authentication\Domain\AuthenticationResult;
use Civi\Lughauth\Features\Oidc\Authentication\Domain\Exception\LoginException;
use Civi\Lughauth\Features\Oidc\Authentication\Domain\StepInput;
use Civi\Lughauth\Features\Oidc\Authentication\Domain\StepName;
use Civi\Lughauth\Features\Oidc\Authentication\Domain\StepResult;
use Civi\Lughauth\Features\Oidc\Authentication\Infrastructure\Driver\Html\Services\HtmlSecurer;
use Civi\Lughauth\Features\Oidc\Authentication\Application\AuthenticateUser;
use Civi\Lughauth\Features\Oidc\DelegateLogin\Application\DelegateLogin;
use Civi\Lughauth\Features\Oidc\User\Application\Usecase\ChangePasswordUsecase;
use Civi\Lughauth\Features\Oidc\User\Application\Usecase\RegisterUserUsecase;
use Civi\Lughauth\Features\Oidc\MagicLink\Application\Usecase\RequestMagicLink\RequestMagicLinkUsecase;
use Civi\Lughauth\Shared\Infrastructure\Translation\MessageProvider;

class LoginForm implements StepForm
{
    public function __construct(
        private readonly MessageProvider $messages,
        private readonly AuthenticateUser $authenticator,
        private readonly DecorateHtml $decorator,
        private readonly HtmlSecurer $securer,
        private readonly DelegateLogin $delegated,
        private readonly ChangePasswordUsecase $changePassword,
        private readonly RegisterUserUsecase $registerUser,
        private readonly RequestMagicLinkUsecase $magicLink,
    ) {
    }

    #[Override]
    public function render(StepInput $input, ResponseInterface $response, ?AuthenticationResult $error): StepResult
    {
        $locale = '';
        $tenant = $input->context->tenant;
        $js = $this->securer->configureScripts([
            $this->securer->focusOn("username"),
            $this->securer->addSign("sign"),
            $this->securer->cypher([['from' => 'type_password', 'to' => 'password']], 'login')
        ]);
        $translator = $this->messages->messages('forms', $locale, __DIR__ . '/../../Translations');

        $title = $translator->get("login.title");
        $help = $translator->get("login.help", ['tenant' => $tenant]);
        $errorCode = $error?->error;
        $error = $errorCode !== null && $errorCode !== ''
            ? $translator->get("login.error-format", ['error' => $translator->get('error.' . strtolower($errorCode))])
            : '';

        $username = $translator->get("login.username");
        $password = $translator->get("login.password");
        // Allow recober by exposes.

        $recoverText = $translator->get("login.recover-text", [
             "<input class=\"inline\" type=\"submit\" value=\"" . $translator->get("login.recover-label") . "\"/>"
        ]);
        $registerText = $translator->get("login.register-text", [
             "<input class=\"inline\" type=\"submit\" value=\"" . $translator->get("login.register-label") . "\"/>"
        ]);
        $magicLinkText = $translator->get("login.magic-link-text", [
             "<input class=\"inline\" type=\"submit\" value=\"" . $translator->get("login.magic-link-label") . "\"/>"
        ]);
        $enter = $translator->get("login.enter");

        $delegatedLogins = "";
        $delegatedStep = StepName::DELEGATED_LOGIN->value;
        foreach ($this->delegated->providers($tenant) as $provider) {
            $info = $provider->info();
            $delegatedLogins .= <<<HTML
                <form method="POST" id="social-form-{$info->id}" class="social-form">
                    <input type="hidden" name="step" value="{$delegatedStep}" />
                    <input type="hidden" name="delegated-provider" value="{$info->id}" />
                    <button type="submit" class="social-button">
                        <img src="{$info->logo}" alt="{$info->name}" />
                    </button>
                </form>
                HTML;
        }
        $recoverPass = "";
        if ($this->changePassword->allowRecover($tenant)) {
            $recoverStep = StepName::RECOVER_PASS->value;
            $recoverPass .= <<<HTML
                <form method="POST">
                    <input type="hidden" name="step" value="{$recoverStep}" />
                    {$recoverText}
                </form>
                HTML;
        }
        $registerUser = "";
        if ($this->registerUser->allowRegister($tenant)) {
            $registerStep = StepName::REGISTER_USER->value;
            $registerUser .= <<<HTML
                <form method="POST">
                    <input type="hidden" name="step" value="{$registerStep}" />
                    {$registerText}
                </form>
                HTML;
        }
        $magicLinkButton = "";
        if ($this->magicLink->isEnabled($tenant)) {
            $magicLinkStep = StepName::MAGIC_LINK->value;
            $magicLinkButton .= <<<HTML
                <form method="POST">
                    <input type="hidden" name="step" value="{$magicLinkStep}" />
                    {$magicLinkText}
                </form>
                HTML;
        }

        $error = $error !== '' ? '<p class="error">' . $error . '</p>' : '';
        $delegatedLogins = $delegatedLogins !== '' ? "<div class=\"social-login-buttons\">{$delegatedLogins}</div>" : '';

        $response->getBody()->write(
            $this->decorator->getFullPage(
                $input->request,
                'Login',
                $js . <<<HTML
                    <h1>{$title}</h1>
                    <p>{$help}</p>
                    {$error}
                    <form id="login" method="POST">
                        <input type="hidden" name="csid" id="sign" />
                        <input type="hidden" id="password" name="password" value="" />
                        <label> {$username}
                            <input type="text" id="username" name="username" value="" />
                        </label>
                        <label> {$password}
                            <input type="password" id="type_password" value="" />
                        </label>
                        <input class="primary-button" type="submit" value="{$enter}" />
                    </form>
                    {$recoverPass}
                    {$registerUser}
                    {$magicLinkButton}
                    {$delegatedLogins}
                HTML,
                'es',
                'index',
                $tenant
            )
        );
        return StepResult::render($response, $input->challenges);
    }

    #[Override]
    public function authenticate(StepInput $input): StepResult
    {
        $password = $this->securer->decrypt((string) ($input->body['password'] ?? '')) ?? '';
        $username = (string) ($input->body['username'] ?? '');
        $csid = (string) ($input->body['csid'] ?? '');
        $challenges = $input->challenges->withUsername($username);
        try {
            $auth = $this->authenticator->authenticate(
                $input->authRequest,
                $challenges,
                $input->context->tenant,
                $username,
                $password,
                $input->context->issuer,
                $csid,
                $input->context->state,
                $input->context->nonce
            );
            return StepResult::proceed($auth, $challenges);
        } catch (LoginException $ex) {
            throw new LoginException($ex->auth, $ex->getMessage(), $ex->getCode(), $ex, $challenges);
        }
    }
}
