<?php

/* @autogenerated */
declare(strict_types=1);

namespace Civi\Lughauth\Features\Oidc\Authentication\Infrastructure\Driver\Html\Forms;

use Psr\Http\Message\ResponseInterface;
use Civi\Lughauth\Features\Oidc\Authentication\Domain\AuthenticationResult;
use Civi\Lughauth\Features\Oidc\Authentication\Domain\StepInput;

interface StepRenderer
{
    public function render(StepInput $input, ResponseInterface $response, ?AuthenticationResult $error): ResponseInterface;
}
