<?php

/* @autogenerated */
declare(strict_types=1);

namespace Civi\Lughauth\Features\Oidc\Authentication\Infrastructure\Driver\Html\Forms;

use Override;
use Psr\Http\Message\ResponseInterface;
use Civi\Lughauth\Features\Oidc\Authentication\Domain\AuthenticationResult;
use Civi\Lughauth\Features\Oidc\User\Domain\PublicLoginAuthResponse;
use Civi\Lughauth\Features\Oidc\Authentication\Infrastructure\Driver\Html\Services\DecorateHtml;
use Civi\Lughauth\Features\Oidc\Authentication\Infrastructure\Driver\Html\Services\HtmlSecurer;
use Civi\Lughauth\Features\Oidc\Authentication\Application\AuthenticateUser;
use Civi\Lughauth\Features\Oidc\Authentication\Infrastructure\Driver\Html\Services\PublicMfa;
use Civi\Lughauth\Features\Oidc\Authentication\Domain\StepInput;
use Civi\Lughauth\Features\Oidc\Authentication\Domain\StepName;
use Civi\Lughauth\Features\Oidc\Authentication\Domain\Exception\LoginException;
use Civi\Lughauth\Shared\Infrastructure\Translation\MessageProvider;

class UseMfaForm implements StepForm
{
    public function __construct(
        private readonly MessageProvider $messages,
        private readonly AuthenticateUser $authenticator,
        private readonly PublicMfa $publicMfa,
        private readonly DecorateHtml $decorator,
        private readonly HtmlSecurer $securer
    ) {
    }

    #[Override]
    public function render(StepInput $input, ResponseInterface $response, ?AuthenticationResult $error): ResponseInterface
    {
        $locale = '';

        $js = $this->securer->configureScripts([
            $this->securer->addSign("sign"),
            $this->securer->focusOn("mfa_code")
        ]);
        $translator = $this->messages->messages('forms', $locale, __DIR__ . '/../../Translations');

        $title = $translator->get("mfa.title");
        $error = $error?->errorMessage
            ? $translator->get("mfa.error-format", [$error = $translator->get('error.' . strtolower($error?->errorMessage))])
            : false;

        $help = $translator->get("mfa.help");
        $code = $translator->get("mfa.code");
        $send = $translator->get("mfa.send");

        $backLabel = $translator->get("mfa.back-label");
        $backText = $translator->get(
            "mfa.back-text",
            ["<input class=\"inline\" type=\"submit\" value=\"" . $backLabel . "\" />"]
        );
        $error = $error ? '<p class="error">' . $error . '</p>' : '';
        $step = StepName::MFA->value;
        $response->getBody()->write($this->decorator->getFullPage(
            $input->request,
            'Mfa',
            $js . <<<HTML
                    <h1>{$title}</h1>
                    <p>{$help}</p>
                    {$error}
                    <form method="POST">
                        <input type="hidden" name="csid" id="sign" />
                        <input type="hidden" name="step" value="{$step}" />
                        <label> {$code}
                            <input type="text" name="mfa_code" id="mfa_code" value="" />
                        </label>
                        <input class="primary-button" type="submit" value="{$send}" />
                    </form>
                    <form method="POST">
                        <input type="hidden" name="step" value="" />
                        {$backText}
                    </form>
                HTML,
            $locale
        ));
        return $response;
    }

    #[Override]
    public function authenticate(StepInput $input): PublicLoginAuthResponse
    {
        $csid = (string) ($input->body['csid'] ?? '');
        $challenges = $input->challenges;

        if ($challenges->withMfa) {
            return $this->authenticator->preAuthenticate(
                $input->authRequest,
                $challenges,
                $input->context->tenant,
                $input->context->issuer,
                $csid,
                $input->context->state,
                $input->context->nonce
            );
        }

        $otp = $input->body['mfa_code'] ?? '';
        if ($this->publicMfa->verifyOtp($input->context->tenant, $challenges->username ?? '', $otp)) {
            $updated = $challenges->withMfa(true);
            return $this->authenticator->preAuthenticate(
                $input->authRequest,
                $updated,
                $input->context->tenant,
                $input->context->issuer,
                $csid,
                $input->context->state,
                $input->context->nonce
            );
        }

        throw new LoginException(auth: AuthenticationResult::mfaRequired('wrong_auth_code'));
    }
}
