<?php

/* @autogenerated */
declare(strict_types=1);

namespace Civi\Lughauth\Features\Access\UserInvitation\Domain\ValueObject;

use Civi\Lughauth\Shared\Value\Validation\ConstraintFailList;
use Civi\Lughauth\Shared\Value\Validation\ConstraintFail;

class UserInvitationMetadataJsonVO
{
    public static function empty(): UserInvitationMetadataJsonVO
    {
        return new UserInvitationMetadataJsonVO(null);
    }
    public static function from(UserInvitationMetadataJsonVO|string|null $value): UserInvitationMetadataJsonVO
    {
        return self::fromUnsafe($value);
    }
    public static function tryFrom(mixed $value, ConstraintFailList $list): ?UserInvitationMetadataJsonVO
    {
        if ($value instanceof UserInvitationMetadataJsonVO) {
            // If is a ValueObject, its already validated... nothing to append
            return $value;
        } elseif (!$value) {
            return new UserInvitationMetadataJsonVO($value);
        } elseif (is_string($value)) {
            return new UserInvitationMetadataJsonVO($value);
        } else {
            $list->add(new ConstraintFail('wrong_type', ['metadataJson'], [$value], ['string']));
            return null;
        }
    }
    private static function fromUnsafe(mixed $value): UserInvitationMetadataJsonVO
    {
        if ($value instanceof UserInvitationMetadataJsonVO) {
            // If is a ValueObject, its already validated
            return $value;
        } else {
            // If is not a ValueObject, validation is need and exception throw
            $errorsList = new ConstraintFailList();
            $candidate = self::tryFrom($value, $errorsList);
            if ($errorsList->hasErrors()) {
                throw $errorsList->asConstraintException();
            }
            \assert($candidate instanceof UserInvitationMetadataJsonVO);
            return $candidate;
        }
    }
    /**
     * private constructor to avoid build a value without all the rule validations.
     */
    private function __construct(
        private readonly ?string $metadataJson
    ) {
    }
    public function value(): ?string
    {
        return $this->metadataJson;
    }
    public function equals(?UserInvitationMetadataJsonVO $other): bool
    {
        return $this->value() == $other?->value();
    }
}
