<?php

# @autogenerated
declare(strict_types=1);

namespace Civi\Lughauth\Features\Access\TenantTermsOfUse\Application\Usecase\Delete;

use Psr\EventDispatcher\EventDispatcherInterface;
use Throwable;
use Civi\Lughauth\Shared\Security\Allow;
use Civi\Lughauth\Shared\Exception\UnauthorizedException;
use Civi\Lughauth\Shared\Exception\NotFoundException;
use Civi\Lughauth\Features\Access\TenantTermsOfUse\Domain\TenantTermsOfUseRef;
use Civi\Lughauth\Features\Access\TenantTermsOfUse\Application\Service\Visibility\TenantTermsOfUseVisibilityService;
use Civi\Lughauth\Features\Access\TenantTermsOfUse\Domain\Gateway\TenantTermsOfUseWriteGateway;
use Civi\Lughauth\Shared\Observability\LoggerAwareTrait;
use Civi\Lughauth\Shared\Observability\TracerAwareTrait;

class TenantTermsOfUseDeleteUsecase
{
    use LoggerAwareTrait;
    use TracerAwareTrait;

    public function __construct(
        private readonly EventDispatcherInterface $dispacher,
        private readonly TenantTermsOfUseVisibilityService $visibility,
        private readonly TenantTermsOfUseWriteGateway $writer
    ) {
    }

    public function allowDelete(?TenantTermsOfUseRef $ref = null): Allow
    {
        $this->logDebug("Check allow of delete usecase for Tenant terms of use");
        $span = $this->startSpan("Check allow of delete usecase for Tenant terms of use");
        try {
            $result = $this->dispacher->dispatch(new TenantTermsOfUseDeleteAllowDecision(Allow::allowed('delete', 'Allowed to delete by default'), $ref));
            return $result->allow;
        } catch (Throwable $ex) {
            $span->recordException($ex);
            throw $ex;
        } finally {
            $span->end();
        }
    }
    public function delete(string $uid): void
    {
        $this->logDebug("Run delete usecase for Tenant terms of use");
        $span = $this->startSpan("Run delete usecase for Tenant terms of use");
        try {
            $ref = new TenantTermsOfUseRef($uid);
            $allow = $this->allowDelete($ref);
            if (!$allow->allowed) {
                throw new UnauthorizedException($allow->reason);
            }
            if (!$original = $this->visibility->retrieveVisibleForUpdate($ref)) {
                throw new NotFoundException($uid);
            }
            $this->dispacher->dispatch(new TenantTermsOfUseDeleteCheck($original));
            $deleted = $original->delete();
            $this->writer->delete($deleted);
        } catch (Throwable $ex) {
            $span->recordException($ex);
            throw $ex;
        } finally {
            $span->end();
        }
    }
}
