<?php

/* @autogenerated */
declare(strict_types=1);

use PHPUnit\Framework\TestCase;
use OpenTelemetry\API\Trace\SpanContext;
use OpenTelemetry\SDK\Common\Attribute\Attributes;
use OpenTelemetry\SDK\Common\Instrumentation\InstrumentationScope;
use OpenTelemetry\SDK\Resource\ResourceInfo;
use Civi\Lughauth\Shared\Infrastructure\Management\Collector\SpanDataEnvelope;
use Civi\Lughauth\Shared\Infrastructure\Management\Collector\StatusDataEnvelope;

/**
 * Unit tests for {@see SpanDataEnvelope}.
 */
final class SpanDataEnvelopeUnitTest extends TestCase
{
    /**
     * Ensures accessor methods expose span metadata correctly.
     */
    public function testGetters(): void
    {
        /* Arrange: build a span envelope with context and attributes. */
        $context = SpanContext::create('4bf92f3577b34da6a3ce929d0e0e4736', '00f067aa0ba902b7');
        $parent = SpanContext::create('4bf92f3577b34da6a3ce929d0e0e4736', '1111111111111111');
        $attributes = Attributes::create(['k' => 'v']);
        $scope = new InstrumentationScope('test', '1.0', null, $attributes);
        $resource = ResourceInfo::create($attributes);

        $span = new SpanDataEnvelope(
            name: 'span',
            kind: 1,
            context: $context,
            parentContext: $parent,
            status: StatusDataEnvelope::ok(),
            startEpochNanos: 1,
            endEpochNanos: 2,
            attributes: $attributes,
            scope: $scope,
            resource: $resource
        );

        /* Act: access each public getter on the envelope. */
        $name = $span->getName();
        $kind = $span->getKind();
        $traceId = $span->getTraceId();
        $spanId = $span->getSpanId();
        $parentSpanId = $span->getParentSpanId();
        $endNanos = $span->getEndEpochNanos();
        $hasEnded = $span->hasEnded();
        $spanAttributes = $span->getAttributes();
        $instrumentationScope = $span->getInstrumentationScope();
        $spanResource = $span->getResource();

        /* Assert: verify getter outputs reflect the inputs. */
        $this->assertSame('span', $name);
        $this->assertSame(1, $kind);
        $this->assertSame($context->getTraceId(), $traceId);
        $this->assertSame($context->getSpanId(), $spanId);
        $this->assertSame($parent->getSpanId(), $parentSpanId);
        $this->assertSame(2, $endNanos);
        $this->assertTrue($hasEnded);
        $this->assertSame($attributes, $spanAttributes);
        $this->assertSame($scope, $instrumentationScope);
        $this->assertSame($resource, $spanResource);
    }
}
