<?php

# @autogenerated
declare(strict_types=1);

namespace Civi\Lughauth\Features\Access\TrustedClient\Domain\ValueObject;

use Civi\Lughauth\Shared\Value\Validation\ConstraintFailList;
use Civi\Lughauth\Shared\Value\Validation\ConstraintFail;

class TrustedClientM2mTokenTtlSecondsVO
{
    public static function from(TrustedClientM2mTokenTtlSecondsVO|int $value): TrustedClientM2mTokenTtlSecondsVO
    {
        return self::fromUnsafe($value);
    }
    public static function tryFrom(mixed $value, ConstraintFailList $list): ?TrustedClientM2mTokenTtlSecondsVO
    {
        if ($value instanceof TrustedClientM2mTokenTtlSecondsVO) {
            // If is a ValueObject, its already validated... nothing to append
            return $value;
        } elseif (is_integer($value)) {
            return new TrustedClientM2mTokenTtlSecondsVO($value);
        } else {
            $list->add(new ConstraintFail('wrong_type', ['m2mTokenTtlSeconds'], [$value], ['int']));
            return null;
        }
    }
    private static function fromUnsafe(mixed $value): TrustedClientM2mTokenTtlSecondsVO
    {
        if ($value instanceof TrustedClientM2mTokenTtlSecondsVO) {
            // If is a ValueObject, its already validated
            return $value;
        } else {
            // If is not a ValueObject, validation is need and exception throw
            $errorsList = new ConstraintFailList();
            $candidate = self::tryFrom($value, $errorsList);
            if ($errorsList->hasErrors()) {
                throw $errorsList->asConstraintException();
            }
            \assert($candidate instanceof TrustedClientM2mTokenTtlSecondsVO);
            return $candidate;
        }
    }
    /**
     * private constructor to avoid build a value without all the rule validations.
     */
    private function __construct(
        private readonly int $m2mTokenTtlSeconds
    ) {
    }
    public function value(): int
    {
        return $this->m2mTokenTtlSeconds;
    }
    public function equals(?TrustedClientM2mTokenTtlSecondsVO $other): bool
    {
        return $this->value() == $other?->value();
    }
}
