<?php

/* @autogenerated */
declare(strict_types=1);

require_once __DIR__ . '/FormsTestCase.php';

use DI\ContainerBuilder;
use Slim\Psr7\Factory\ServerRequestFactory;
use Civi\Lughauth\Shared\AppConfig;
use Civi\Lughauth\Shared\Context;
use Civi\Lughauth\Features\Oidc\Client\Domain\ClientData;
use Civi\Lughauth\Features\Oidc\Authentication\Domain\AuthenticationRequest;
use Civi\Lughauth\Features\Oidc\Authentication\Domain\ChallengesState;
use Civi\Lughauth\Features\Oidc\Authentication\Domain\OidcFlowContext;
use Civi\Lughauth\Features\Oidc\Authentication\Domain\StepInput;
use Civi\Lughauth\Features\Oidc\Authentication\Infrastructure\Driver\Html\Forms\LoginForm;
use Civi\Lughauth\Features\Oidc\Authentication\Infrastructure\Driver\Html\Services\DecorateHtml;
use Civi\Lughauth\Features\Oidc\Authentication\Infrastructure\Driver\Html\Services\HtmlSecurer;
use Civi\Lughauth\Features\Oidc\Authentication\Application\AuthenticateUser;
use Civi\Lughauth\Features\Oidc\DelegateLogin\Application\DelegateLogin;
use Civi\Lughauth\Features\Oidc\User\Domain\PublicLoginAuthResponse;
use Civi\Lughauth\Features\Oidc\User\Application\Usecase\ChangePasswordUsecase;
use Civi\Lughauth\Features\Oidc\User\Application\Usecase\RegisterUserUsecase;
use Civi\Lughauth\Shared\Infrastructure\Translation\MessageProvider;

/**
 * Unit tests for {@see LoginForm} step integration.
 */
final class LoginFormStepUnitTest extends FormsTestCase
{
    /**
     * Verifies authenticate() uses StepInput values.
     */
    public function testAuthenticateUsesStepInput(): void
    {
        $request = (new ServerRequestFactory())
            ->createServerRequest('POST', '/oauth/openid/tenant1/authorize')
            ->withQueryParams([
                'response_type' => 'code',
                'client_id' => 'client-123',
                'state' => 'state-xyz',
                'redirect_uri' => 'https://client.example/callback',
                'scope' => 'openid profile',
                'nonce' => 'nonce-abc',
            ]);

        $builder = new ContainerBuilder();
        $config = $this->createMock(AppConfig::class);
        $context = new Context($builder, $config);
        $flow = OidcFlowContext::fromRequest($request, 'tenant1', $context);

        $client = new ClientData('client-123', ['code'], true);
        $authRequest = new AuthenticationRequest(
            client: $client,
            scope: 'openid profile',
            redirect: 'https://client.example/callback',
            responseType: 'code',
            audiences: ['client-123']
        );

        $input = new StepInput(
            context: $flow,
            authRequest: $authRequest,
            challenges: new ChallengesState(),
            body: [
                'username' => 'user@example.com',
                'password' => 'enc-pass',
                'csid' => 'csid-123'
            ],
            request: $request
        );

        $authResponse = $this->createMock(PublicLoginAuthResponse::class);

        $securer = $this->createMock(HtmlSecurer::class);
        $securer->expects($this->once())
            ->method('decrypt')
            ->with('enc-pass')
            ->willReturn('plain-pass');

        $authenticator = $this->createMock(AuthenticateUser::class);
        $authenticator->expects($this->once())
            ->method('authenticate')
            ->with(
                $authRequest,
                $this->isInstanceOf(ChallengesState::class),
                'tenant1',
                'user@example.com',
                'plain-pass',
                'https://example.com/openid/tenant1',
                'csid-123',
                'state-xyz',
                'nonce-abc'
            )
            ->willReturn($authResponse);

        $form = new LoginForm(
            $this->createMock(MessageProvider::class),
            $authenticator,
            $this->createMock(DecorateHtml::class),
            $securer,
            $this->createMock(DelegateLogin::class),
            $this->createMock(ChangePasswordUsecase::class),
            $this->createMock(RegisterUserUsecase::class)
        );

        $result = $form->authenticate($input);

        $this->assertSame($authResponse, $result);
    }
}
