<?php

/* @autogenerated */
declare(strict_types=1);

namespace Civi\Lughauth\Features\Oidc\User\Application\Listener;

use Civi\Lughauth\Features\Access\User\Domain\Event\UserCreateEvent;
use Civi\Lughauth\Features\Notification\Message\Domain\Message;
use Civi\Lughauth\Features\Notification\Message\Application\Usecase\SendMessage;
use Throwable;

class NotifyCreated
{
    public function __construct(private readonly SendMessage $sender)
    {

    }
    public function __invoke(UserCreateEvent $auth)
    {
        $message = new Message(
            targetName: 'Ruben Civeira',
            targetAddress: 'rubenciveira@gmail.com',
            subject: 'Se ha credo el usuario ' . $auth->payload->getName(),
            txtContent: 'Como estas',
            htmlContent: '<h1>Como estas</h1>'
        );
        $this->sender->send($message);
    }
}
