<?php

# @autogenerated
declare(strict_types=1);

namespace Civi\Lughauth\Features\Access\Master\User\Application\Service\Visibility;

use Civi\Lughauth\Features\Access\Master\User\Domain\Gateway\UserFilter;

class UserRestrictFilterToVisibility
{
    public function __construct(
        public UserFilter $userFilter
    ) {
    }
    public function with(UserFilter $userFilter)
    {
        $this->userFilter = $userFilter;
    }
}
