<?php

/* @autogenerated */
declare(strict_types=1);

use PHPUnit\Framework\TestCase;
use Civi\Lughauth\Shared\Security\FieldsAccess;

final class FieldsAccessUnitTest extends TestCase
{
    public function testWithAddsFields(): void
    {
        $access = new class (['id']) extends FieldsAccess {
            public function accessMode(): string
            {
                return 'read';
            }

            public function resourceName(): string
            {
                return 'users';
            }
        };

        $access->with('name', 'email');

        $this->assertSame(['id', 'name', 'email'], $access->fields);
        $this->assertSame('read', $access->accessMode());
        $this->assertSame('users', $access->resourceName());
    }

    public function testWithAllAddsFieldsArray(): void
    {
        $access = new class (['id']) extends FieldsAccess {
            public function accessMode(): string
            {
                return 'write';
            }

            public function resourceName(): string
            {
                return 'roles';
            }
        };

        $access->withAll(['createdAt', 'updatedAt']);

        $this->assertSame(['id', 'createdAt', 'updatedAt'], $access->fields);
        $this->assertSame('write', $access->accessMode());
        $this->assertSame('roles', $access->resourceName());
    }
}
