<?php

# @autogenerated
declare(strict_types=1);

use PHPUnit\Framework\TestCase;
use Civi\Lughauth\Shared\Exception\ConstraintException;
use Civi\Lughauth\Shared\Value\Validation\ConstraintFailList;
use Civi\Lughauth\Features\Access\TenantConfig\Domain\ValueObject\TenantConfigDynamicRegistrationPolicyVO;
use Civi\Lughauth\Features\Access\TenantConfig\Domain\TenantConfigDynamicRegistrationPolicyOptions;

final class TenantConfigDynamicRegistrationPolicyVOUnitTest extends TestCase
{
    public function test_asignation_keep_value(): void
    {
        $value = TenantConfigDynamicRegistrationPolicyOptions::OPEN;
        $ref = TenantConfigDynamicRegistrationPolicyVO::from($value);
        $this->assertEquals(TenantConfigDynamicRegistrationPolicyOptions::OPEN, $ref->value());
        $other = TenantConfigDynamicRegistrationPolicyVO::tryFrom($ref, new ConstraintFailList());
        $this->assertSame($other, $ref);
        $more = TenantConfigDynamicRegistrationPolicyVO::from($ref);
        $this->assertSame($more, $ref);
    }
    public function test_asignation_invalid_type(): void
    {
        $errors = new ConstraintFailList();
        $other = TenantConfigDynamicRegistrationPolicyVO::tryFrom('1', $errors);
        $this->assertNull($other);
        $this->assertTrue($errors->hasErrors());
    }
    public function test_optimist_asignation_invalid_type(): void
    {
        $this->expectException(ConstraintException::class);
        $method = new ReflectionMethod(TenantConfigDynamicRegistrationPolicyVO::class, 'fromUnsafe');
        $method->invoke(null, [11, "bad"]);
    }
    public function test_equals(): void
    {
        $one = TenantConfigDynamicRegistrationPolicyVO::from(TenantConfigDynamicRegistrationPolicyOptions::OPEN);
        $same = TenantConfigDynamicRegistrationPolicyVO::from(TenantConfigDynamicRegistrationPolicyOptions::OPEN);
        $other = TenantConfigDynamicRegistrationPolicyVO::from(TenantConfigDynamicRegistrationPolicyOptions::TOKEN_REQUIRED);
        $withEmpty = $one->equals(null);
        $withSame = $one->equals($same);
        $withOther = $one->equals($other);

        $this->assertFalse($withEmpty);
        $this->assertTrue($withSame);
        $this->assertFalse($withOther);
    }
    public function test_empty(): void
    {
        $ref = TenantConfigDynamicRegistrationPolicyVO::empty();
        $this->assertNull($ref->value());
    }
    public function test_try_from_empty(): void
    {
        $ref = TenantConfigDynamicRegistrationPolicyVO::tryFrom(null, new ConstraintFailList());
        $this->assertNull($ref->value());
    }
}
