<?php

/* @autogenerated */
declare(strict_types=1);

namespace Civi\Lughauth\Features\Document\Snippet\Domain\Gateway;

use Closure;
use Civi\Lughauth\Features\Access\Tenant\Domain\TenantRef;
use Civi\Lughauth\Features\Document\Snippet\Domain\Snippet;
use Civi\Lughauth\Features\Document\Snippet\Domain\SnippetRef;

interface SnippetWriteGateway
{
    public function create(Snippet $entity, ?Closure $verify = null): Snippet;
    public function update(SnippetRef $ref, Snippet $entity): Snippet;
    public function delete(Snippet $entity): bool;
    public function resolveForUpdate(SnippetRef $ref): ?Snippet;
    public function listForUpdate(?SnippetFilter $filter = null, ?SnippetCursor $cursor = null): SnippetSlide;
    public function retrieveForUpdate(SnippetFilter $filter): ?Snippet;
    public function existsForUpdate(SnippetFilter $filter): bool;
    public function countForUpdate(?SnippetFilter $filter = null): int;
    public function findOneForUpdateByCodeAndTenant(string $code, ?TenantRef $tenant): ?Snippet;
}
