<?php

/* @autogenerated */
declare(strict_types=1);

namespace Civi\Lughauth\Features\OAuth\Authentication\Application;

use Civi\Lughauth\Features\OAuth\Session\Domain\Gateway\SessionStoreGateway;
use Civi\Lughauth\Features\OAuth\Session\Domain\SessionInfo;

class SessionManager
{
    public function __construct(
        private readonly SessionStoreGateway $sessionStore
    ) {
    }

    public function removeSession(string $code): void
    {
        $this->sessionStore->deleteSession($code);
    }

    public function loadSession(string $code, string $nonce, string $state): ?SessionInfo
    {
        return $this->sessionStore->loadSession($code);
    }
}
