<?php

/* @autogenerated */
declare(strict_types=1);

namespace Civi\Lughauth\Features\Oidc\Key\Infrastructure\Driver\Rest;

use Psr\Http\Message\ResponseInterface;
use Psr\Http\Message\ServerRequestInterface;
use Civi\Lughauth\Features\Oidc\Key\Domain\KeysManagerService;

class JwksController
{
    public function __construct(private readonly KeysManagerService $tokenHandler)
    {
    }

    public function get(ServerRequestInterface $request, ResponseInterface $response, array $args): ResponseInterface
    {
        $tenant = $args['tenant'];
        $data = $this->tokenHandler->keysAsJwks($tenant);
        $response->getBody()->write(json_encode($data));
        return $response->withHeader('Content-Type', 'application/json');
    }
}
