<?php

# @autogenerated
declare(strict_types=1);

namespace Civi\Lughauth\Features\Access\UserIdentity\Infrastructure\Driver;

use Override;
use Slim\Routing\RouteCollectorProxy;
use Civi\Lughauth\Features\Access\UserIdentity\Infrastructure\Driver\Rest\UserIdentityAllowController;
use Civi\Lughauth\Features\Access\UserIdentity\Infrastructure\Driver\Rest\UserIdentityListController;
use Civi\Lughauth\Features\Access\UserIdentity\Infrastructure\Driver\Rest\UserIdentityCreateController;
use Civi\Lughauth\Features\Access\UserIdentity\Infrastructure\Driver\Rest\UserIdentityRetrieveController;
use Civi\Lughauth\Features\Access\UserIdentity\Infrastructure\Driver\Rest\UserIdentityUpdateController;
use Civi\Lughauth\Features\Access\UserIdentity\Infrastructure\Driver\Rest\UserIdentityDeleteController;
use Civi\Lughauth\Shared\Infrastructure\MicroPlugin;
use Civi\Lughauth\Shared\Event\EventListenersRegistrarInterface;
use Civi\Lughauth\Features\Access\UserIdentity\Application\Service\Visibility\UserIdentityFilterProposal;
use Civi\Lughauth\Features\Access\UserIdentity\Application\Policy\Filter\TenantAccesible;
use Civi\Lughauth\Features\Access\UserIdentity\Application\Policy\Allow\Create\IsAutenticatedCreateAllow;
use Civi\Lughauth\Features\Access\UserIdentity\Application\Usecase\Create\UserIdentityCreateAllowProposal;
use Civi\Lughauth\Features\Access\UserIdentity\Application\Policy\Allow\Update\IsAutenticatedUpdateAllow;
use Civi\Lughauth\Features\Access\UserIdentity\Application\Usecase\Update\UserIdentityUpdateAllowProposal;
use Civi\Lughauth\Features\Access\UserIdentity\Application\Policy\Allow\Retrieve\IsAutenticatedRetrieveAllow;
use Civi\Lughauth\Features\Access\UserIdentity\Application\Usecase\Retrieve\UserIdentityRetrieveAllowProposal;
use Civi\Lughauth\Features\Access\UserIdentity\Application\Policy\Allow\List\IsAutenticatedListAllow;
use Civi\Lughauth\Features\Access\UserIdentity\Application\Usecase\List\UserIdentityListAllowProposal;
use Civi\Lughauth\Features\Access\UserIdentity\Application\Policy\Allow\Delete\IsAutenticatedDeleteAllow;
use Civi\Lughauth\Features\Access\UserIdentity\Application\Usecase\Delete\UserIdentityDeleteAllowProposal;
use Civi\Lughauth\Features\Access\UserIdentity\Application\Usecase\Create\UserIdentityCreateAllowDecision;
use Civi\Lughauth\Features\Access\UserIdentity\Application\Usecase\Update\UserIdentityUpdateAllowDecision;
use Civi\Lughauth\Features\Access\UserIdentity\Application\Usecase\Retrieve\UserIdentityRetrieveAllowDecision;
use Civi\Lughauth\Features\Access\UserIdentity\Application\Usecase\List\UserIdentityListAllowDecision;
use Civi\Lughauth\Features\Access\UserIdentity\Application\Usecase\Delete\UserIdentityDeleteAllowDecision;

class UserIdentityPlugin extends MicroPlugin
{
    #[Override]
    public function registerRoutes(RouteCollectorProxy $app)
    {
        $app->group('/api/access/identity', [$this, 'setRoutesForUserIdentity']);
        $app->group('/api/me/acl/access/identity', [$this, 'setRoutesForUserIdentityAcl']);
        $app->group('/api/access/user-identities', [$this, 'setRoutesForUserIdentity']);
        $app->group('/api/me/acl/access/user-identities', [$this, 'setRoutesForUserIdentityAcl']);
    }
    #[Override]
    public function registerEvents(EventListenersRegistrarInterface $bus)
    {
        $bus->registerListener(UserIdentityFilterProposal::class, TenantAccesible::class);
        $bus->registerListener(UserIdentityUpdateAllowProposal::class, IsAutenticatedUpdateAllow::class);
        $bus->registerListener(UserIdentityRetrieveAllowProposal::class, IsAutenticatedRetrieveAllow::class);
        $bus->registerListener(UserIdentityListAllowProposal::class, IsAutenticatedListAllow::class);
        $bus->registerListener(UserIdentityDeleteAllowProposal::class, IsAutenticatedDeleteAllow::class);
        $bus->registerListener(UserIdentityCreateAllowDecision::class, IsAutenticatedCreateAllow::class);
        $bus->registerListener(UserIdentityUpdateAllowDecision::class, IsAutenticatedUpdateAllow::class);
        $bus->registerListener(UserIdentityRetrieveAllowDecision::class, IsAutenticatedRetrieveAllow::class);
        $bus->registerListener(UserIdentityListAllowDecision::class, IsAutenticatedListAllow::class);
        $bus->registerListener(UserIdentityDeleteAllowDecision::class, IsAutenticatedDeleteAllow::class);
    }
    public function setRoutesForUserIdentityAcl(RouteCollectorProxy $userIdentityGroup)
    {
        $userIdentityGroup->get('', [UserIdentityAllowController::class, 'genericAllow']);
        $userIdentityGroup->get('/{uid}', [UserIdentityAllowController::class, 'contextualAllow']);
    }
    public function setRoutesForUserIdentity(RouteCollectorProxy $userIdentityGroup)
    {
        $userIdentityGroup->get('', [UserIdentityListController::class, 'list']);
        $userIdentityGroup->post('', [UserIdentityCreateController::class, 'create']);
        $userIdentityGroup->get('/{uid}', [UserIdentityRetrieveController::class, 'retrieve']);
        $userIdentityGroup->put('/{uid}', [UserIdentityUpdateController::class, 'update']);
        $userIdentityGroup->delete('/{uid}', [UserIdentityDeleteController::class, 'delete']);
        $userIdentityGroup->delete('', [UserIdentityDeleteController::class, 'deleteAllForQuery']);
        $userIdentityGroup->get('/~/delete-status/{uid}', [UserIdentityDeleteController::class, 'checkDeleteAllForQueryStatus']);
    }
}
