<?php

/* @autogenerated */
declare(strict_types=1);

namespace Civi\Lughauth\Features\Access\TrustedClient\Domain\ValueObject\Holder;

use Civi\Lughauth\Shared\Value\Validation\ConstraintFailList;
use Civi\Lughauth\Features\Access\TrustedClient\Domain\ValueObject\TrustedClientVersionVO;

trait TrustedClientVersionAttributeHolder
{
    protected TrustedClientVersionVO|int|null $version = null;
    protected bool $versionAssigned = false;

    public function getVersionOrCurrent(?TrustedClientVersionVO $version): ?TrustedClientVersionVO
    {
        return $this->versionAssigned ? ($this->version === null ? null : TrustedClientVersionVO::from($this->version)) : $version;
    }
    public function versionTryBuildInitial(ConstraintFailList $error): ?TrustedClientVersionVO
    {
        return  TrustedClientVersionVO::tryFrom($this->versionAssigned ? $this->version : null, $error);
    }
    public function version(TrustedClientVersionVO|int|null $version): static
    {
        $this->version = $version;
        $this->versionAssigned = true;
        return $this;
    }
    public function getVersion(): ?int
    {
        return $this->version instanceof TrustedClientVersionVO ? $this->version->value() : $this->version;
    }
    public function isVersionAssigned(): bool
    {
        return $this->versionAssigned;
    }
    public function writeVersionTo(mixed $att): void
    {
        if ($this->versionAssigned) {
            $att->version($this->version);
        }
    }
    public function readVersionFrom(mixed $att): void
    {
        if ($att->isVersionAssigned()) {
            $version = $att->getVersion();
            $this->version($version);
        }
    }
    public function unsetVersion(): static
    {
        $this->versionAssigned = false;
        return $this;
    }
    protected function withDefaultVersion(): void
    {
    }
    protected function withAssertedVersionRules(self $value, ConstraintFailList $errorsList): void
    {
        if ($value->versionAssigned = $this->versionAssigned) {
            $value->version = TrustedClientVersionVO::tryFrom($this->version, $errorsList);
        }
    }
}
