<?php

# @autogenerated
declare(strict_types=1);

namespace Civi\Lughauth\Features\Access\ScopeAttributePermission\Domain\ValueObject\Accesor;

use Civi\Lughauth\Features\Access\ScopeAttributePermission\Domain\ValueObject\ScopeAttributePermissionReadVO;

trait ScopeAttributePermissionReadAccesor
{
    private ScopeAttributePermissionReadVO $_read;
    public function getRead(): bool
    {
        return $this->_read->value();
    }
    public function read(): ScopeAttributePermissionReadVO
    {
        return $this->_read;
    }
    public function isReadChanged(?self $original = null): bool
    {
        return $this->_read->value() !== ($original ? $original->_read->value() : null);
    }
    public function withRead(ScopeAttributePermissionReadVO|bool $read): self
    {
        $copy = clone $this;
        $copy->_read = ScopeAttributePermissionReadVO::from($read);
        return $copy;
    }
}
