<?php

/* @autogenerated */
declare(strict_types=1);

namespace Civi\Lughauth\Features\Access\PlatformIdentity\Domain\ValueObject;

use Civi\Lughauth\Features\Access\Role\Domain\RoleRef;
use Civi\Lughauth\Shared\Value\Validation\ConstraintFailList;
use Civi\Lughauth\Shared\Value\Validation\ConstraintFail;

class PlatformIdentityRolesRoleVO
{
    public static function from(PlatformIdentityRolesRoleVO|RoleRef $value): PlatformIdentityRolesRoleVO
    {
        return self::fromUnsafe($value);
    }
    public static function tryFrom(mixed $value, ConstraintFailList $list): ?PlatformIdentityRolesRoleVO
    {
        if ($value instanceof PlatformIdentityRolesRoleVO) {
            // If is a ValueObject, its already validated... nothing to append
            return $value;
        } elseif (is_a($value, RoleRef::class)) {
            return new PlatformIdentityRolesRoleVO($value);
        } else {
            $list->add(new ConstraintFail('wrong_type', ['role'], [$value], ['RoleRef']));
            return null;
        }
    }
    private static function fromUnsafe(mixed $value): PlatformIdentityRolesRoleVO
    {
        if ($value instanceof PlatformIdentityRolesRoleVO) {
            // If is a ValueObject, its already validated
            return $value;
        } else {
            // If is not a ValueObject, validation is need and exception throw
            $errorsList = new ConstraintFailList();
            $candidate = self::tryFrom($value, $errorsList);
            if ($errorsList->hasErrors()) {
                throw $errorsList->asConstraintException();
            }
            \assert($candidate instanceof PlatformIdentityRolesRoleVO);
            return $candidate;
        }
    }
    /**
     * private constructor to avoid build a value without all the rule validations.
     */
    private function __construct(
        private readonly RoleRef $role
    ) {
    }
    public function value(): RoleRef
    {
        return $this->role;
    }
    public function equals(?PlatformIdentityRolesRoleVO $other): bool
    {
        return $this->value()->uid() == $other?->value()?->uid();
    }
}
