<?php

# @autogenerated
declare(strict_types=1);

use PHPUnit\Framework\TestCase;
use Civi\Lughauth\Shared\Value\Validation\ConstraintFailList;
use Civi\Lughauth\Features\Access\TenantLoginProvider\Domain\ValueObject\TenantLoginProviderSourceVO;

final class TenantLoginProviderSourceVOUnitTest extends TestCase
{
    public function test_asignation_keep_value(): void
    {
        $value = 'GOOGLE';
        $ref = TenantLoginProviderSourceVO::from($value);
        $this->assertEquals('GOOGLE', $ref->value());
        $other = TenantLoginProviderSourceVO::tryFrom($ref, new ConstraintFailList());
        $this->assertSame($other, $ref);
        $more = TenantLoginProviderSourceVO::from($ref);
        $this->assertSame($more, $ref);
    }
    public function test_asignation_invalid_type(): void
    {
        $errors = new ConstraintFailList();
        $other = TenantLoginProviderSourceVO::tryFrom('1', $errors);
        $this->assertNull($other);
        $this->assertTrue($errors->hasErrors());
    }
}
