<?php

# @autogenerated
declare(strict_types=1);

namespace Civi\Lughauth\Features\Access\Master\TrustedClient\Domain\ValueObject\Accesor;

use Civi\Lughauth\Features\Access\Master\TrustedClient\Domain\ValueObject\TrustedClientAllowedRedirectsVO;
use Civi\Lughauth\Features\Access\Master\TrustedClient\Domain\ValueObject\TrustedClientAllowedRedirectsListRef;

trait TrustedClientAllowedRedirectsAccesor
{
    private TrustedClientAllowedRedirectsVO $_allowedRedirects;
    public function getAllowedRedirects(): ?TrustedClientAllowedRedirectsListRef
    {
        return $this->_allowedRedirects->value();
    }
    public function allowedRedirects(): TrustedClientAllowedRedirectsVO
    {
        return $this->_allowedRedirects;
    }
    public function isAllowedRedirectsChanged(?self $original = null): bool
    {
        return $this->_allowedRedirects->value() !== ($original ? $original->_allowedRedirects->value() : null);
    }
    public function withAllowedRedirects(TrustedClientAllowedRedirectsVO|TrustedClientAllowedRedirectsListRef| array |null $allowedRedirects): self
    {
        $copy = clone $this;
        $copy->_allowedRedirects = TrustedClientAllowedRedirectsVO::from($allowedRedirects);
        return $copy;
    }
}
