<?php

# @autogenerated
declare(strict_types=1);

namespace Civi\Lughauth\Features\Access\ClientIdentity\Infrastructure\Connector\Pdo;

use Throwable;
use Closure;
use Civi\Lughauth\Shared\Infrastructure\Sql\SqlParam;
use Civi\Lughauth\Shared\Infrastructure\Sql\SqlTemplate;
use Civi\Lughauth\Shared\Exception\NotFoundException;
use Civi\Lughauth\Shared\Exception\NotUniqueException;
use Civi\Lughauth\Shared\Exception\ConstraintException;
use Civi\Lughauth\Shared\Exception\OptimistLockException;
use Civi\Lughauth\Shared\Exception\NotEmptyChildsException;
use Civi\Lughauth\Features\Access\ClientIdentity\Domain\Gateway\ClientIdentityFilter;
use Civi\Lughauth\Features\Access\ClientIdentity\Domain\Gateway\ClientIdentityCursor;
use Civi\Lughauth\Features\Access\ClientIdentity\Domain\ClientIdentity;
use Civi\Lughauth\Features\Access\ClientIdentity\Domain\ClientIdentityRef;
use Civi\Lughauth\Shared\Observability\LoggerAwareTrait;
use Civi\Lughauth\Shared\Observability\TracerAwareTrait;
use Civi\Lughauth\Features\Access\User\Domain\UserRef;
use Civi\Lughauth\Features\Access\RelyingParty\Domain\RelyingPartyRef;
use Civi\Lughauth\Features\Access\TrustedClient\Domain\TrustedClientRef;

class ClientIdentityPdoConnector
{
    use LoggerAwareTrait;
    use TracerAwareTrait;

    public function __construct(
        private readonly SqlTemplate $db,
    ) {
    }
    public function list(?ClientIdentityFilter $filter = null, ?ClientIdentityCursor $sort = null): array
    {
        $this->logDebug("List query for Client identity");
        $span = $this->startSpan("List query for Client identity");
        try {
            $sqlFilter = $this->filter($filter, $sort, false);
            return $this->query($sqlFilter['query'], $sqlFilter['params']);
        } catch (Throwable $ex) {
            $span->recordException($ex);
            throw $ex;
        } finally {
            $span->end();
        }
    }
    public function listForUpdate(?ClientIdentityFilter $filter = null, ?ClientIdentityCursor $sort = null): array
    {
        $this->logDebug("List query for update of Client identity");
        $span = $this->startSpan("List query for update of Client identity");
        try {
            $sqlFilter = $this->filter($filter, $sort, false);
            return $this->queryForUpdate($sqlFilter['query'], $sqlFilter['params']);
        } catch (Throwable $ex) {
            $span->recordException($ex);
            throw $ex;
        } finally {
            $span->end();
        }
    }
    private function query(string $query, ?array $params = []): array
    {
        return $this->theQuery(false, $query, $params);
    }
    private function rawQuery(string $query, ?array $params = []): array
    {
        return $this->theRawQuery(false, $query, $params);
    }
    private function queryForUpdate(string $query, ?array $params = []): array
    {
        return $this->theQuery(true, $query, $params);
    }
    private function rawQueryForUpdate(string $query, ?array $params = []): array
    {
        return $this->theRawQuery(true, $query, $params);
    }
    private function theQuery(bool $forUpdate, string $query, ?array $params = []): array
    {
        $this->logDebug("Make query for entities for Client identity");
        $span = $this->startSpan("Make query for entities for Client identity");
        try {
            return $forUpdate ? $this->db->queryForUpdate($query, $params, fn (array $row): ClientIdentity => $this->mapper($row)) : $this->db->query($query, $params, fn (array $row): ClientIdentity => $this->mapper($row));
        } catch (Throwable $ex) {
            $span->recordException($ex);
            throw $ex;
        } finally {
            $span->end();
        }
    }
    private function theRawQuery(bool $forUpdate, string $query, ?array $params = []): array
    {
        $this->logDebug("Make raw query for Client identity");
        $span = $this->startSpan("Make raw query for Client identity");
        try {
            return $forUpdate ? $this->db->queryForUpdate($query, $params, fn (array $row): array => $row) : $this->db->query($query, $params, fn (array $row): array => $row);
        } catch (Throwable $ex) {
            $span->recordException($ex);
            throw $ex;
        } finally {
            $span->end();
        }
    }
    public function retrieve(ClientIdentityFilter $filter): ?ClientIdentity
    {
        $this->logDebug("Retrieve query for Client identity");
        $span = $this->startSpan("Retrieve query for Client identity");
        try {
            $sqlFilter = $this->filter($filter, null, false);
            return $this->db->findOne($sqlFilter['query'], $sqlFilter['params'], fn (array $row): ClientIdentity => $this->mapper($row));
        } catch (Throwable $ex) {
            $span->recordException($ex);
            throw $ex;
        } finally {
            $span->end();
        }
    }
    public function retrieveForUpdate(ClientIdentityFilter $filter): ?ClientIdentity
    {
        $this->logDebug("Retrieve query for update of Client identity");
        $span = $this->startSpan("Retrieve query for update of Client identity");
        try {
            $sqlFilter = $this->filter($filter, null, false);
            return $this->db->findOneForUpdate($sqlFilter['query'], $sqlFilter['params'], fn (array $row): ClientIdentity => $this->mapper($row));
        } catch (Throwable $ex) {
            $span->recordException($ex);
            throw $ex;
        } finally {
            $span->end();
        }
    }
    public function create(ClientIdentity $entity, ?Closure $verify = null): ClientIdentity
    {
        $this->logDebug("Execute insert sql query for Client identity");
        $span = $this->startSpan("Execute insert sql query for Client identity");
        try {
            try {
                $this->db->execute('INSERT INTO "access_client_identity" ( "uid", "user", "relying_party", "trusted_client", "roles", "version") VALUES ( :uid, :user, :relyingParty, :trustedClient, :roles, :version)', [
                     new SqlParam(name: 'uid', value: $entity->uid(), type: SqlParam::STR),
                     new SqlParam(name: 'user', value: $entity->getUser()->uid(), type: SqlParam::STR),
                     new SqlParam(name: 'relyingParty', value: $entity->getRelyingParty()?->uid(), type: SqlParam::STR),
                     new SqlParam(name: 'trustedClient', value: $entity->getTrustedClient()?->uid(), type: SqlParam::STR),
                     new SqlParam(name: 'roles', value: $entity->getRoles(), type: SqlParam::TEXT),
                     new SqlParam(name: 'version', value: 0, type: SqlParam::INT)
                ]);
            } catch (NotUniqueException $ex) {
                $this->checkDuplicates($entity, true);
                throw $ex;
            }
            $created = $entity->withVersion(0);
            if ($verify && !$verify($created)) {
                $this->db->execute('DELETE FROM "access_client_identity" where "uid" = :uid', [
                  new SqlParam(name: 'uid', value: $entity->uid(), type: SqlParam::STR)
                ]);
                throw new NotFoundException('Insertion of not visible values');
            }
            return $created;
        } catch (Throwable $ex) {
            $span->recordException($ex);
            throw $ex;
        } finally {
            $span->end();
        }
    }
    public function update(ClientIdentity $update): ?ClientIdentity
    {
        $this->logDebug("Execute update sql query for Client identity");
        $span = $this->startSpan("Execute update sql query for Client identity");
        try {
            try {
                $result = $this->db->execute('UPDATE "access_client_identity" SET "user" = :user , "relying_party" = :relyingParty , "trusted_client" = :trustedClient , "roles" = :roles , "version" = :version WHERE "uid" = :uid and "version" = :_lock_version', [
                     new SqlParam(name: 'uid', value: $update->uid(), type: SqlParam::STR),
                     new SqlParam(name: 'user', value: $update->getUser()->uid(), type: SqlParam::STR),
                     new SqlParam(name: 'relyingParty', value: $update->getRelyingParty()?->uid(), type: SqlParam::STR),
                     new SqlParam(name: 'trustedClient', value: $update->getTrustedClient()?->uid(), type: SqlParam::STR),
                     new SqlParam(name: 'roles', value: $update->getRoles(), type: SqlParam::TEXT),
                     new SqlParam(name: 'version', value: ($update->getVersion() ?? 0) + 1, type: SqlParam::INT),
                     new SqlParam(name: '_lock_version', value: $update->getVersion(), type: SqlParam::INT)
                ]);
                if (!$result && $this->db->exists('select "uid" from "access_client_identity" where "uid" = :uid', ['uid' => $update->uid() ])) {
                    throw new OptimistLockException($update->uid() ?? 'no-id', "version: " . ($update->getVersion() ?? 0));
                } elseif (!$result) {
                    throw new NotFoundException($update->uid() ?? 'no-id');
                }
            } catch (NotUniqueException $ex) {
                $this->checkDuplicates($update, false);
                throw $ex;
            }
            return $update->withVersion(($update->getVersion() ?? 0) + 1);
        } catch (Throwable $ex) {
            $span->recordException($ex);
            throw $ex;
        } finally {
            $span->end();
        }
    }
    public function delete(ClientIdentityRef $ref): bool
    {
        $this->logDebug("Execute delete sql query for Client identity");
        $span = $this->startSpan("Execute delete sql query for Client identity");
        try {
            try {
                return $this->db->execute('DELETE FROM "access_client_identity" where "uid" = :uid', [new SqlParam(name: 'uid', value: $ref->uid(), type:SqlParam::STR)]);
            } catch (NotEmptyChildsException $ex) {
                throw ConstraintException::ofError('not-empty', ['uid'], [$ref->uid()]);
            }
        } catch (Throwable $ex) {
            $span->recordException($ex);
            throw $ex;
        } finally {
            $span->end();
        }
    }
    public function exists(ClientIdentityFilter $filter): bool
    {
        $this->logDebug("Execute exists sql query for Client identity");
        $span = $this->startSpan("Execute exists sql query for Client identity");
        try {
            $sqlFilter = $this->filter($filter, null, false);
            return $this->db->exists($sqlFilter['query'], $sqlFilter['params']);
        } catch (Throwable $ex) {
            $span->recordException($ex);
            throw $ex;
        } finally {
            $span->end();
        }
    }
    public function existsForUpdate(ClientIdentityFilter $filter): bool
    {
        $this->logDebug("Execute exists sql query for update of Client identity");
        $span = $this->startSpan("Execute update sql query for update of Client identity");
        try {
            $sqlFilter = $this->filter($filter, null, false);
            return $this->db->existsForUpdate($sqlFilter['query'], $sqlFilter['params']);
        } catch (Throwable $ex) {
            $span->recordException($ex);
            throw $ex;
        } finally {
            $span->end();
        }
    }
    public function count(?ClientIdentityFilter $filter = null): int
    {
        $this->logDebug("Execute count sql query for Client identity");
        $span = $this->startSpan("Execute count sql query for Client identity");
        try {
            $sqlFilter = $this->filter($filter, null, true);
            return $this->db->findOne($sqlFilter['query'], $sqlFilter['params'], fn (array $row): int => (int) $row['count']);
        } catch (Throwable $ex) {
            $span->recordException($ex);
            throw $ex;
        } finally {
            $span->end();
        }
    }
    public function countForUpdate(?ClientIdentityFilter $filter = null): int
    {
        $this->logDebug("Execute count sql query for update of Client identity");
        $span = $this->startSpan("Execute count sql query for update of Client identity");
        try {
            $sqlFilter = $this->filter($filter, null, true);
            return $this->db->findOneForUpdate($sqlFilter['query'], $sqlFilter['params'], fn (array $row) => (int) $row['count']);
        } catch (Throwable $ex) {
            $span->recordException($ex);
            throw $ex;
        } finally {
            $span->end();
        }
    }
    private function checkDuplicates(ClientIdentity $entity, bool $creation): void
    {
        $this->logDebug("Query to check duplicates for Client identity");
        $span = $this->startSpan("Query to check duplicates for Client identity");
        try {
            $values = ['uid' => $entity->uid()];
            if ($creation &&  $this->db->exists('SELECT  "uid" from "access_client_identity" where "uid" = :uid', $values)) {
                throw ConstraintException::ofError('not-unique', array_keys($values), array_values($values));
            }
        } catch (Throwable $ex) {
            $span->recordException($ex);
            throw $ex;
        } finally {
            $span->end();
        }
    }
    private function filter(?ClientIdentityFilter $filter, ?ClientIdentityCursor $sort, bool $count): array
    {
        $this->logDebug("Build query filter of Client identity");
        $span = $this->startSpan("Build query filter of Client identity");
        try {
            $join = '';
            $query = '';
            $params = [];
            $order = '';
            $limit = '';
            if ($filter) {
                $filterUids = $filter->uids();
                if (null !== $filterUids && count($filterUids) > 1) {
                    $query .= ' and "access_client_identity"."uid" in (:uids)';
                    $params[] = new SqlParam(name:'uids', value: $filterUids, type: SqlParam::STR);
                } elseif (null !== $filterUids) {
                    $query .= ' and "access_client_identity"."uid" = :uid';
                    $params[] = new SqlParam(name:'uid', value: $filterUids[0], type: SqlParam::STR);
                }
                $filterSearch = $filter->search();
                if (null !== $filterSearch) {
                    $query .= ' and ( "access_client_identity"."uid" like :search)';
                    $params[] = new SqlParam(name:'search', value: '%'. $filterSearch . '%', type: SqlParam::STR);
                }
                $filterForAllAudiences = $filter->forAllAudiences();
                if (null !== $filterForAllAudiences) {
                    $query .= ' and ("relying_party" is null and "trusted_client" is null)';
                }
                $filterUser = $filter->user();
                if (null !== $filterUser) {
                    $query .= ' and "access_client_identity"."user" = :user ';
                    $params[] = new SqlParam(name: 'user', value: $filterUser->uid(), type: SqlParam::STR);
                }
                $filterUsers = $filter->users();
                if (null !== $filterUsers) {
                    $query .= ' and "access_client_identity"."user" in (:users)  ';
                    $params[] = new SqlParam(name: 'users', value: $filterUsers, type: SqlParam::STR);
                }
                $filterRelyingParty = $filter->relyingParty();
                if (null !== $filterRelyingParty) {
                    $query .= ' and "access_client_identity"."relying_party" = :relyingParty ';
                    $params[] = new SqlParam(name: 'relyingParty', value: $filterRelyingParty->uid(), type: SqlParam::STR);
                }
                $filterRelyingPartys = $filter->relyingPartys();
                if (null !== $filterRelyingPartys) {
                    $query .= ' and "access_client_identity"."relying_party" in (:relyingPartys)  ';
                    $params[] = new SqlParam(name: 'relyingPartys', value: $filterRelyingPartys, type: SqlParam::STR);
                }
                $filterTrustedClient = $filter->trustedClient();
                if (null !== $filterTrustedClient) {
                    $query .= ' and "access_client_identity"."trusted_client" = :trustedClient ';
                    $params[] = new SqlParam(name: 'trustedClient', value: $filterTrustedClient->uid(), type: SqlParam::STR);
                }
                $filterTrustedClients = $filter->trustedClients();
                if (null !== $filterTrustedClients) {
                    $query .= ' and "access_client_identity"."trusted_client" in (:trustedClients)  ';
                    $params[] = new SqlParam(name: 'trustedClients', value: $filterTrustedClients, type: SqlParam::STR);
                }
                $filterUserTenantTenantAccesible = $filter->userTenantTenantAccesible();
                if (null !== $filterUserTenantTenantAccesible) {
                    $join .= ' LEFT JOIN "access_user" as "userTenantTenantAccesibleUser" ON "userTenantTenantAccesibleUser"."uid" = "access_client_identity"."user" LEFT JOIN "access_tenant" as "userTenantTenantAccesibleTenant" ON "userTenantTenantAccesibleTenant"."uid" = "userTenantTenantAccesibleUser"."tenant"';
                    $query .= ' and "userTenantTenantAccesibleTenant"."uid" = :userTenantTenantAccesible';
                    $params[] = new SqlParam(name: 'userTenantTenantAccesible', value: $filterUserTenantTenantAccesible, type: SqlParam::STR);
                }
            }
            if ($sort) {
                $sortLimit = $sort->limit();
                if ($sortLimit) {
                    $limit = ' LIMIT ' . $this->db->escapeValue($sortLimit, SqlParam::INT);
                }
                $sortSinceUid = $sort->sinceUid();
                if (null !== $sortSinceUid) {
                    $query .= ' and  "uid" < :sinceUid';
                    $params[] = new SqlParam(name: 'sinceUid', value: $sortSinceUid, type: SqlParam::STR);
                }
                $order = ', "access_client_identity"."uid" desc';
            }
            return [
              'query' => 'SELECT '.($count ? ' count("access_client_identity".*) as count ' : '"access_client_identity".*').' FROM "access_client_identity"'
                . $join
                . ($query ? ' WHERE ' . substr($query, 4) : '')
                . ($order ? ' ORDER BY ' . substr($order, 2) : '') . $limit,
              'params' => $params];
        } catch (Throwable $ex) {
            $span->recordException($ex);
            throw $ex;
        } finally {
            $span->end();
        }
    }
    private function mapper(array $row): ClientIdentity
    {
        $this->logDebug("Mapping from sql to entity for Client identity");
        $span = $this->startSpan("Mapping from sql to entity for Client identity");
        try {
            $uid = $row['uid'] ?? null;
            if (null === $uid) {
                throw ConstraintException::ofError('not-null', ['uid'], [null]);
            }
            $rawUser = $row['user'] ?? null;
            if (null === $rawUser) {
                throw ConstraintException::ofError('not-null', ['user'], [null]);
            }
            $user = new UserRef(uid: $rawUser);
            $relyingParty = isset($row['relying_party']) ? new RelyingPartyRef(uid: $row['relying_party']) : null;
            $trustedClient = isset($row['trusted_client']) ? new TrustedClientRef(uid: $row['trusted_client']) : null;
            $roles = $row['roles'] ?? null;
            $version = $row['version'] ?? null;
            return new ClientIdentity(
                uid: $uid,
                user: $user,
                relyingParty: $relyingParty,
                trustedClient: $trustedClient,
                roles: $roles,
                version: $version,
            );
        } catch (Throwable $ex) {
            $span->recordException($ex);
            throw $ex;
        } finally {
            $span->end();
        }
    }
}
