<?php

/* @autogenerated */
declare(strict_types=1);

namespace Civi\Lughauth\Features\Access\TrustedClient\Domain\ValueObject\Accessor;

use Civi\Lughauth\Features\Access\TrustedClient\Domain\ValueObject\TrustedClientBackChannelLogoutUriVO;

trait TrustedClientBackChannelLogoutUriAccessor
{
    private ?TrustedClientBackChannelLogoutUriVO $_backChannelLogoutUri = null;
    public function getBackChannelLogoutUri(): ?string
    {
        return $this->_backChannelLogoutUri?->value();
    }
    public function backChannelLogoutUri(): ?TrustedClientBackChannelLogoutUriVO
    {
        return $this->_backChannelLogoutUri;
    }
    public function isBackChannelLogoutUriChanged(?self $original = null): bool
    {
        return null !== $this->_backChannelLogoutUri && !$this->_backChannelLogoutUri->equals($original?->_backChannelLogoutUri);
    }
    public function withBackChannelLogoutUri(TrustedClientBackChannelLogoutUriVO|string|null $backChannelLogoutUri): self
    {
        $copy = clone $this;
        $copy->_backChannelLogoutUri = TrustedClientBackChannelLogoutUriVO::from($backChannelLogoutUri);
        return $copy;
    }
}
