<?php

/* @autogenerated */
declare(strict_types=1);

namespace Civi\Lughauth\Features\Access\TrustedClient\Domain\ValueObject\Accessor;

use Civi\Lughauth\Features\Access\TrustedClient\Domain\ValueObject\TrustedClientAllowedRedirectsVersionVO;

trait TrustedClientAllowedRedirectsVersionAccessor
{
    private ?TrustedClientAllowedRedirectsVersionVO $_version = null;
    public function getVersion(): ?int
    {
        return $this->_version?->value();
    }
    public function version(): ?TrustedClientAllowedRedirectsVersionVO
    {
        return $this->_version;
    }
    public function isVersionChanged(?self $original = null): bool
    {
        return null !== $this->_version && !$this->_version->equals($original?->_version);
    }
    public function withVersion(TrustedClientAllowedRedirectsVersionVO|int|null $version): self
    {
        $copy = clone $this;
        $copy->_version = TrustedClientAllowedRedirectsVersionVO::from($version);
        return $copy;
    }
}
