<?php

/* @autogenerated */
declare(strict_types=1);

namespace Civi\Lughauth\Features\Document\TemplateAsset\Domain\Event;

use Override;
use Civi\Lughauth\Features\Document\TemplateAsset\Domain\TemplateAsset;

class TemplateAssetEnableEvent extends TemplateAssetUpdateEvent
{
    public function __construct(
        TemplateAsset $payload,
        TemplateAsset $original
    ) {
        parent::__construct($payload, $original);
    }
    #[Override]
    public function eventType(): string
    {
        return 'template-asset.enable';
    }
    #[Override]
    public function schemaVersion(): string
    {
        return 'v1';
    }
    #[Override]
    public function payload(): array
    {
        return $this->payload->asPublicJson();
    }
    #[Override]
    public function original(): array
    {
        return $this->original->asPublicJson();
    }
}
