<?php

/* @autogenerated */
declare(strict_types=1);

namespace Civi\Lughauth\Features\Oidc\Profile\Domain\Gateway;

use Civi\Lughauth\Features\Oidc\Profile\Domain\MfaSetup;

interface MfaGateway
{
    public function isEnabled(string $userUid, string $tenant): bool;

    public function buildSetup(string $userUid, string $tenant): MfaSetup;

    public function enable(string $userUid, string $tenant, string $seed, string $otp): void;

    public function disable(string $userUid, string $tenant): void;
}
