<?php

# @autogenerated
declare(strict_types=1);
namespace Civi\Lughauth\Features\Document\TemplateAsset\Domain\ValueObject;

use Civi\Lughauth\Shared\Value\Validation\ConstraintFailList;
use Civi\Lughauth\Shared\Value\Validation\ConstraintFail;
use Civi\Lughauth\Shared\Value\Validation\Rule\Length;

class TemplateAssetUidVO
{
  public static function from(TemplateAssetUidVO|string $value): TemplateAssetUidVO
  {
    return self::fromUnsafe($value);
  }
  public static function tryFrom(mixed $value, ConstraintFailList $list): ?TemplateAssetUidVO
  {
    if ( $value instanceof TemplateAssetUidVO ) {
      // If is a ValueObject, its already validated... nothing to append
      return $value;
    } else if( is_string($value)) {
      // If is a ValueObject, we need to append all the errors for the context
      $valid = true;
      foreach (self::rules() as $rule) {
        if ($fail = $rule->check($value)) {
          $list->add(ConstraintFail::fromRuleFail('uid', $fail));
          $valid = false;
        }
      }
      return $valid ? new TemplateAssetUidVO($value) : null;
    } else {
      $list->add(new ConstraintFail('wrong_type', ['uid'], [$value], ['string']));
      return null;
    }
  }
  public static function rules(): array
  {
    return [
      new Length(min: null, max: 250),
    ];
  }
  private static function fromUnsafe(mixed $value): TemplateAssetUidVO
  {
    if ($value instanceof TemplateAssetUidVO) {
      // If is a ValueObject, its already validated
      return $value;
    } else {
      // If is not a ValueObject, validation is need and exception throw
      $errorsList = new ConstraintFailList();
      $candidate = self::tryFrom($value, $errorsList);
      if ($errorsList->hasErrors()) {
        throw $errorsList->asConstraintException();
      }
      \assert($candidate instanceof TemplateAssetUidVO);
      return $candidate;
    }
  }
  /**
   * private constructor to avoid build a value without all the rule validations.
   */
  private function __construct(
    private readonly string $uid
  ) {
  }
  public function value(): string
  {
    return $this->uid;
  }
  public function equals(?TemplateAssetUidVO $other): bool
  {
    return $this->value() == $other?->value();
  }
}
