<?php

# @autogenerated
declare(strict_types=1);

namespace Civi\Lughauth\Features\Access\TenantPartySecurity\Domain;

use Civi\Lughauth\Features\Access\TenantPartySecurity\Domain\ValueObject\TenantPartySecurityUidVO;

class TenantPartySecurityRef
{
    private readonly TenantPartySecurityUidVO $_uid;
    public ?TenantPartySecurity $_private_resolve = null;
    public function __construct(TenantPartySecurityUidVO|string $uid)
    {
        $this->_uid = TenantPartySecurityUidVO::from($uid);
    }
    public function uid(): ?string
    {
        return $this->_uid->value();
    }
}
