<?php

# @autogenerated
declare(strict_types=1);

namespace Civi\Lughauth\Features\Access\TenantLoginProvider\Infrastructure\Driver\Rest;

use Psr\Http\Message\ResponseInterface;
use Psr\Http\Message\ServerRequestInterface;
use OpenApi\Attributes as OA;
use Throwable;
use Civi\Lughauth\Shared\Observability\LoggerAwareTrait;
use Civi\Lughauth\Shared\Observability\TracerAwareTrait;
use Civi\Lughauth\Shared\Infrastructure\Sql\SqlTemplate;
use Civi\Lughauth\Features\Access\TenantLoginProvider\Application\Usecase\Create\TenantLoginProviderCreateUsecase;
use Civi\Lughauth\Features\Access\TenantLoginProvider\Domain\ValueObject\TenantLoginProviderUidVO;
use Civi\Lughauth\Features\Access\TenantLoginProvider\Domain\ValueObject\TenantLoginProviderTenantVO;
use Civi\Lughauth\Features\Access\Tenant\Domain\TenantRef;
use Civi\Lughauth\Features\Access\TenantLoginProvider\Domain\ValueObject\TenantLoginProviderNameVO;
use Civi\Lughauth\Features\Access\TenantLoginProvider\Domain\ValueObject\TenantLoginProviderSourceVO;
use Civi\Lughauth\Features\Access\TenantLoginProvider\Domain\ValueObject\TenantLoginProviderDirectAccessVO;
use Civi\Lughauth\Features\Access\TenantLoginProvider\Domain\ValueObject\TenantLoginProviderPublicKeyVO;
use Civi\Lughauth\Features\Access\TenantLoginProvider\Domain\ValueObject\TenantLoginProviderPrivateKeyVO;
use Civi\Lughauth\Features\Access\TenantLoginProvider\Domain\ValueObject\TenantLoginProviderCertificateVO;
use Civi\Lughauth\Features\Access\TenantLoginProvider\Domain\ValueObject\TenantLoginProviderMetadataVO;
use Civi\Lughauth\Shared\Context;
use Civi\Lughauth\Features\Access\TenantLoginProvider\Domain\ValueObject\TenantLoginProviderUsersEnabledByDefaultVO;
use Civi\Lughauth\Features\Access\TenantLoginProvider\Domain\ValueObject\TenantLoginProviderVersionVO;
use Civi\Lughauth\Shared\Value\Validation\ConstraintFailList;
use Civi\Lughauth\Features\Access\TenantLoginProvider\Application\Usecase\Create\TenantLoginProviderCreateParams;
use Civi\Lughauth\Features\Access\TenantLoginProvider\Application\Usecase\Create\TenantLoginProviderCreateResult;

class TenantLoginProviderCreateController
{
    use LoggerAwareTrait;
    use TracerAwareTrait;

    public function __construct(
        private readonly SqlTemplate $sql,
        private readonly TenantLoginProviderCreateUsecase $createUsecase,
        private readonly Context $context,
    ) {
    }
    #[OA\Post(
        path: "/api/access/login-providers",
        tags: ["Tenant login provider"],
        description:"Create",
        requestBody: new OA\RequestBody(content: new OA\JsonContent(type: "object", ref:"#/components/schemas/TenantLoginProviderApiDTO")),
        responses: [
              new OA\Response(response: 201, description: "Ok", content: new OA\JsonContent(type: "object", ref:"#/components/schemas/TenantLoginProviderApiDTO")),
              new OA\Response(response: 422, description: "Constraint error"),
          ]
    )]
    public function create(ServerRequestInterface $request, ResponseInterface $response, array $args): ResponseInterface
    {
        $this->logDebug("Create Tenant login provider");
        $span = $this->startSpan("Create Tenant login provider");
        $this->sql->begin();
        try {
            $value = $this->readTenantLoginProvider($request);
            $result = $this->createUsecase->create($value);
            $this->sql->commit();
            $value = $this->mapTenantLoginProvider($result);
            $response->getBody()->write(json_encode($value));
            return $response->withStatus(201)
              ->withHeader('Content-Type', 'application/json');
        } catch (Throwable $ex) {
            $span->recordException($ex);
            throw $ex;
        } finally {
            $this->sql->close();
            $span->end();
        }
    }

    private function readTenantLoginProvider(ServerRequestInterface $request): TenantLoginProviderCreateParams
    {
        $this->logDebug("Read entity for Tenant login provider");
        $span = $this->startSpan("Read entity for Tenant login provider");
        try {
            $body = $request->getParsedBody();
            $errorsList = new ConstraintFailList();
            $value = new TenantLoginProviderCreateParams();
            $value->uid(TenantLoginProviderUidVO::tryFrom($body['uid'] ?? null, $errorsList));
            if (in_array('tenant', array_keys($body))) {
                $value->tenant(TenantLoginProviderTenantVO::tryFrom(isset($body['tenant']['$ref']) ? new TenantRef($body['tenant']['$ref']) : null, $errorsList));
            }
            $value->name(TenantLoginProviderNameVO::tryFrom($body['name'] ?? null, $errorsList));
            $value->source(TenantLoginProviderSourceVO::tryFrom(isset($body['source']) ? strtoupper($body['source']) : null, $errorsList));
            $value->directAccess(TenantLoginProviderDirectAccessVO::tryFrom($body['directAccess'] ?? null, $errorsList));
            $value->publicKey(TenantLoginProviderPublicKeyVO::tryFrom($body['publicKey'] ?? null, $errorsList));
            $value->privateKey(TenantLoginProviderPrivateKeyVO::tryFrom($body['privateKey'] ?? null, $errorsList));
            $value->certificate(TenantLoginProviderCertificateVO::tryFrom($body['certificate'] ?? null, $errorsList));
            $metadata = $body['metadata'] ?? null;
            $preffixMetadata = $this->context->getBaseUrl() . '/api/access/login-providers/-/temp-metadata?temp=';
            if ($metadata && strpos($metadata, $preffixMetadata) === 0) {
                $value->metadata(TenantLoginProviderMetadataVO::tryFromTemporal(base64_decode(substr($metadata, strlen($preffixMetadata))), $errorsList));
            }
            $value->usersEnabledByDefault(TenantLoginProviderUsersEnabledByDefaultVO::tryFrom($body['usersEnabledByDefault'] ?? null, $errorsList));
            $value->version(TenantLoginProviderVersionVO::tryFrom($body['version'] ?? null, $errorsList));
            if ($errorsList->hasErrors()) {
                throw $errorsList->asConstraintException();
            }
            return $value;
        } catch (Throwable $ex) {
            $span->recordException($ex);
            throw $ex;
        } finally {
            $span->end();
        }
    }
    private function mapTenantLoginProvider(TenantLoginProviderCreateResult $value): TenantLoginProviderApiDTO
    {
        $this->logDebug("Map entity to output dto for Tenant login provider");
        $span = $this->startSpan("Map entity to output dto for Tenant login provider");
        try {
            $tenant = $value->getTenant();
            $dto = new TenantLoginProviderApiDTO();
            $dto->uid = $value->getUid();
            $dto->tenant = $tenant ? ['$ref' => $tenant->uid()] : null;
            $dto->name = $value->getName();
            $dto->source = $value->getSource();
            $dto->directAccess = $value->getDirectAccess();
            $dto->publicKey = $value->getPublicKey();
            $dto->privateKey = $value->getPrivateKey();
            $dto->certificate = $value->getCertificate();
            if ($value->getMetadata()) {
                $dto->metadata = $this->context->getBaseUrl() . '/api/access/login-providers/' . $value->getUid() . '/metadata';
            }
            $dto->usersEnabledByDefault = $value->getUsersEnabledByDefault();
            $dto->version = $value->getVersion();
            return $dto;
        } catch (Throwable $ex) {
            $span->recordException($ex);
            throw $ex;
        } finally {
            $span->end();
        }
    }
}
