<?php

/* @autogenerated */
declare(strict_types=1);

namespace Civi\Lughauth\Features\Oidc\UserInvitation\Domain\Gateway;

use Civi\Lughauth\Features\Oidc\UserInvitation\Domain\UserInvitationSession;

interface UserInvitationSessionGateway
{
    public function createSession(
        string $userUid,
        string $email,
        string $tenantUid,
        string $tenantName,
        string $clientId,
    ): ?UserInvitationSession;
}
