<?php

/* @autogenerated */
declare(strict_types=1);

namespace Civi\Lughauth\Features\Notification\Message\Domain\ValueObject;

use Exception;
use DateTimeImmutable;
use Civi\Lughauth\Shared\Value\Validation\ConstraintFailList;
use Civi\Lughauth\Shared\Value\Validation\ConstraintFail;

class MessageLockAtVO
{
    public static function empty(): MessageLockAtVO
    {
        return new MessageLockAtVO(null);
    }
    public static function from(MessageLockAtVO|\DateTimeImmutable|null $value): MessageLockAtVO
    {
        return self::fromUnsafe($value);
    }
    public static function tryFrom(mixed $value, ConstraintFailList $list): ?MessageLockAtVO
    {
        if ($value instanceof MessageLockAtVO) {
            // If is a ValueObject, its already validated... nothing to append
            return $value;
        } elseif (!$value) {
            return new MessageLockAtVO($value);
        } elseif (is_string($value)) {
            if ($typed = self::readFromString($value)) {
                return self::tryFrom($typed, $list);
            } else {
                $list->add(new ConstraintFail('wrong_format', ['lockAt'], [$value], ['\DateTimeImmutable']));
                return null;
            }
        } elseif (is_a($value, \DateTimeImmutable::class)) {
            return new MessageLockAtVO($value);
        } else {
            $list->add(new ConstraintFail('wrong_type', ['lockAt'], [$value], ['\DateTimeImmutable']));
            return null;
        }
    }
    private static function readFromString(string $dateString): ?DateTimeImmutable
    {
        // Expresión regular para ISO 8601 (con milisegundos y UTC)
        $iso8601Pattern = '/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\.\d{3}Z$/';
        // Validar que la cadena coincida con el formato ISO 8601
        if (preg_match($iso8601Pattern, $dateString)) {
            try {
                return new DateTimeImmutable($dateString);
            } catch (Exception $e) {
                return null; // Retorna null si no es una fecha válida
            }
        } else {
            return null; // Retorna null si el formato no coincide con ISO 8601
        }
    }
    private static function fromUnsafe(mixed $value): MessageLockAtVO
    {
        if ($value instanceof MessageLockAtVO) {
            // If is a ValueObject, its already validated
            return $value;
        } else {
            // If is not a ValueObject, validation is need and exception throw
            $errorsList = new ConstraintFailList();
            $candidate = self::tryFrom($value, $errorsList);
            if ($errorsList->hasErrors()) {
                throw $errorsList->asConstraintException();
            }
            \assert($candidate instanceof MessageLockAtVO);
            return $candidate;
        }
    }
    /**
     * private constructor to avoid build a value without all the rule validations.
     */
    private function __construct(
        private readonly ?\DateTimeImmutable $lockAt
    ) {
    }
    public function value(): ?\DateTimeImmutable
    {
        return $this->lockAt;
    }
    public function equals(?MessageLockAtVO $other): bool
    {
        return $this->value() == $other?->value();
    }
}
