<?php

# @autogenerated
declare(strict_types=1);

namespace Civi\Lughauth\Features\Access\TrustedClient\Application\Usecase\Create;

use Psr\EventDispatcher\EventDispatcherInterface;
use Throwable;
use Civi\Lughauth\Shared\Security\Allow;
use Civi\Lughauth\Shared\Exception\UnauthorizedException;
use Civi\Lughauth\Features\Access\TrustedClient\Application\Service\Visibility\TrustedClientVisibilityService;
use Civi\Lughauth\Features\Access\TrustedClient\Domain\TrustedClient;
use Civi\Lughauth\Features\Access\TrustedClient\Domain\Gateway\TrustedClientWriteGateway;
use Civi\Lughauth\Shared\Observability\LoggerAwareTrait;
use Civi\Lughauth\Shared\Observability\TracerAwareTrait;

class TrustedClientCreateUsecase
{
    use LoggerAwareTrait;
    use TracerAwareTrait;

    public function __construct(
        private readonly EventDispatcherInterface $dispacher,
        private readonly TrustedClientVisibilityService $visibility,
        private readonly TrustedClientWriteGateway $writer
    ) {
    }

    public function allowCreate(): Allow
    {
        $this->logDebug("Check allow of create usecase for Trusted client");
        $span = $this->startSpan("Check allow of create usecase for Trusted client");
        try {
            $result = $this->dispacher->dispatch(new TrustedClientCreateAllowDecision(Allow::allowed('create', 'Allowed to create by default')));
            return $result->getAllow();
        } catch (Throwable $ex) {
            $span->recordException($ex);
            throw $ex;
        } finally {
            $span->end();
        }
    }
    public function create(TrustedClientCreateParams $params): TrustedClientCreateResult
    {
        $this->logDebug("Run create usecase for Trusted client");
        $span = $this->startSpan("Run create usecase for Trusted client");
        try {
            $allow = $this->allowCreate();
            if (!$allow->allowed) {
                throw new UnauthorizedException($allow->reason);
            }
            $this->dispacher->dispatch(new TrustedClientCreateCheck($params));
            $enriched = $this->dispacher->dispatch(new TrustedClientCreateEnrich($params, $params->toAttributes()));
            $attributes = $enriched->getResult();
            $input = $this->visibility->copyWithFixed($attributes);
            $entity = TrustedClient::create($input);
            $result = $this->writer->create(
                $entity,
                fn ($created) =>
                            $this->visibility->checkVisibility($created)
            );
            $output = $this->visibility->copyWithHidden($this->visibility->prepareVisibleData($result));
            return new TrustedClientCreateResult($output);
        } catch (Throwable $ex) {
            $span->recordException($ex);
            throw $ex;
        } finally {
            $span->end();
        }
    }
}
