<?php

/* @autogenerated */
declare(strict_types=1);

use PHPUnit\Framework\TestCase;
use Civi\Lughauth\Features\Access\UserWebauthnCredential\Domain\UserWebauthnCredentialRef;

final class UserWebauthnCredentialRefUnitTest extends TestCase
{
    public function test(): void
    {
        $uid = 'uid';
        $ref = new UserWebauthnCredentialRef(uid: $uid);
        $this->assertSame($uid, $ref->uid());
    }
}
