<?php

# @autogenerated
declare(strict_types=1);

namespace Civi\Lughauth\Features\Document\TemplateSnippet\Application\Policy\Allow\Enable;

use Throwable;
use Civi\Lughauth\Features\Document\TemplateSnippet\Application\Usecase\Enable\TemplateSnippetEnableAllowDecision;
use Civi\Lughauth\Shared\Context;
use Civi\Lughauth\Shared\Observability\LoggerAwareTrait;
use Civi\Lughauth\Shared\Observability\TracerAwareTrait;

class IsAuthenticatedEnableAllow
{
    use LoggerAwareTrait;
    use TracerAwareTrait;

    public function __construct(private readonly Context $context)
    {
    }
    public function __invoke(TemplateSnippetEnableAllowDecision $proposal): TemplateSnippetEnableAllowDecision
    {
        $this->logDebug("Check IsAuthenticatedEnableAllow Template snippet");
        $span = $this->startSpan("Check IsAuthenticatedEnableAllow Template snippet");
        try {
            $userContext = $this->context->getIdentity();
            if ($proposal->isAllowed()) {
                if (! !$userContext->anonymous) {
                    $proposal->deny('Disabled if not IsAuthenticatedEnable');
                }
            }
            return $proposal;
        } catch (Throwable $ex) {
            $span->recordException($ex);
            throw $ex;
        } finally {
            $span->end();
        }
    }
}
