<?php

/* @autogenerated */
declare(strict_types=1);

namespace Civi\Lughauth\Features\Document\Template\Domain\ValueObject\Accessor;

use Civi\Lughauth\Features\Document\Template\Domain\ValueObject\TemplateVersionVO;

trait TemplateVersionAccessor
{
    private ?TemplateVersionVO $_version = null;
    public function getVersion(): ?int
    {
        return $this->_version?->value();
    }
    public function version(): ?TemplateVersionVO
    {
        return $this->_version;
    }
    public function isVersionChanged(?self $original = null): bool
    {
        return null !== $this->_version && !$this->_version->equals($original?->_version);
    }
    public function withVersion(TemplateVersionVO|int|null $version): self
    {
        $copy = clone $this;
        $copy->_version = TemplateVersionVO::from($version);
        return $copy;
    }
}
