<?php

# @autogenerated
declare(strict_types=1);

namespace Civi\Lughauth\Features\Access\TenantLoginProvider\Application\Usecase\Enable;

use Civi\Lughauth\Features\Access\TenantLoginProvider\Domain\ValueObject\Holder\TenantLoginProviderUidAttributeHolder;
use Civi\Lughauth\Features\Access\TenantLoginProvider\Domain\ValueObject\Holder\TenantLoginProviderTenantAttributeHolder;
use Civi\Lughauth\Features\Access\TenantLoginProvider\Domain\ValueObject\Holder\TenantLoginProviderNameAttributeHolder;
use Civi\Lughauth\Features\Access\TenantLoginProvider\Domain\ValueObject\Holder\TenantLoginProviderSourceAttributeHolder;
use Civi\Lughauth\Features\Access\TenantLoginProvider\Domain\ValueObject\Holder\TenantLoginProviderDisabledAttributeHolder;
use Civi\Lughauth\Features\Access\TenantLoginProvider\Domain\ValueObject\Holder\TenantLoginProviderDirectAccessAttributeHolder;
use Civi\Lughauth\Features\Access\TenantLoginProvider\Domain\ValueObject\Holder\TenantLoginProviderPublicKeyAttributeHolder;
use Civi\Lughauth\Features\Access\TenantLoginProvider\Domain\ValueObject\Holder\TenantLoginProviderPrivateKeyAttributeHolder;
use Civi\Lughauth\Features\Access\TenantLoginProvider\Domain\ValueObject\Holder\TenantLoginProviderCertificateAttributeHolder;
use Civi\Lughauth\Features\Access\TenantLoginProvider\Domain\ValueObject\Holder\TenantLoginProviderMetadataAttributeHolder;
use Civi\Lughauth\Features\Access\TenantLoginProvider\Domain\ValueObject\Holder\TenantLoginProviderUsersEnabledByDefaultAttributeHolder;
use Civi\Lughauth\Features\Access\TenantLoginProvider\Domain\ValueObject\Holder\TenantLoginProviderVersionAttributeHolder;
use Civi\Lughauth\Features\Access\TenantLoginProvider\Domain\TenantLoginProviderAttributes;

class TenantLoginProviderEnableResult
{
    use TenantLoginProviderUidAttributeHolder;
    use TenantLoginProviderTenantAttributeHolder;
    use TenantLoginProviderNameAttributeHolder;
    use TenantLoginProviderSourceAttributeHolder;
    use TenantLoginProviderDisabledAttributeHolder;
    use TenantLoginProviderDirectAccessAttributeHolder;
    use TenantLoginProviderPublicKeyAttributeHolder;
    use TenantLoginProviderPrivateKeyAttributeHolder;
    use TenantLoginProviderCertificateAttributeHolder;
    use TenantLoginProviderMetadataAttributeHolder;
    use TenantLoginProviderUsersEnabledByDefaultAttributeHolder;
    use TenantLoginProviderVersionAttributeHolder;

    private const UNSETS = [
      'uid' => 'unsetUid',
      'tenant' => 'unsetTenant',
      'name' => 'unsetName',
      'source' => 'unsetSource',
      'disabled' => 'unsetDisabled',
      'directAccess' => 'unsetDirectAccess',
      'publicKey' => 'unsetPublicKey',
      'privateKey' => 'unsetPrivateKey',
      'certificate' => 'unsetCertificate',
      'metadata' => 'unsetMetadata',
      'usersEnabledByDefault' => 'unsetUsersEnabledByDefault',
      'version' => 'unsetVersion',
    ];

    public function __construct(TenantLoginProviderAttributes|null $att = null)
    {
        $this->uid($att->uid);
        $this->tenant($att->tenant);
        $this->name($att->name);
        $this->source($att->source);
        $this->disabled($att->disabled);
        $this->directAccess($att->directAccess);
        $this->publicKey($att->publicKey);
        $this->privateKey($att->privateKey);
        $this->certificate($att->certificate);
        $this->metadata($att->metadata);
        $this->usersEnabledByDefault($att->usersEnabledByDefault);
        $this->version($att->version);
    }
    public function toAttributes(): TenantLoginProviderAttributes
    {
        $att = new TenantLoginProviderAttributes();
        $att->uid($this->uid);
        $att->tenant($this->tenant);
        $att->name($this->name);
        $att->source($this->source);
        $att->disabled($this->disabled);
        $att->directAccess($this->directAccess);
        $att->publicKey($this->publicKey);
        $att->privateKey($this->privateKey);
        $att->certificate($this->certificate);
        $att->metadata($this->metadata);
        $att->usersEnabledByDefault($this->usersEnabledByDefault);
        $att->version($this->version);
        return $att;
    }
    public function unset($field)
    {
        if (isset(self::UNSETS[$field])) {
            call_user_func([$this, self::UNSETS[$field]]);
        }
    }
    public function withDefaults(): TenantLoginProviderEnableResult
    {
        $this->withDefaultUid();
        $this->withDefaultTenant();
        $this->withDefaultName();
        $this->withDefaultSource();
        $this->withDefaultDisabled();
        $this->withDefaultDirectAccess();
        $this->withDefaultPublicKey();
        $this->withDefaultPrivateKey();
        $this->withDefaultCertificate();
        $this->withDefaultMetadata();
        $this->withDefaultUsersEnabledByDefault();
        $this->withDefaultVersion();
        return $this;
    }
}
