<?php

/* @autogenerated */
declare(strict_types=1);

namespace Civi\Lughauth\Features\OAuth\Common\Application\Usecase\Install;

use Civi\Lughauth\Shared\Value\Random;
use Civi\Lughauth\Features\Document\Template\Domain\Gateway\TemplateWriteGateway;
use Civi\Lughauth\Features\Document\Template\Domain\Template;
use Civi\Lughauth\Features\Document\Template\Domain\TemplateAttributes;
use Civi\Lughauth\Features\Document\Template\Domain\TemplateChannelOptions;
use Civi\Lughauth\Features\Document\TemplateVersion\Domain\Gateway\TemplateVersionWriteGateway;
use Civi\Lughauth\Features\Document\TemplateVersion\Domain\TemplateVersion;
use Civi\Lughauth\Features\Document\TemplateVersion\Domain\TemplateVersionAttributes;

/**
 * Installation step that seeds the "auth.delegate" mail template used to notify users of
 * a new sign-in via a delegate (federated) identity provider.
 *
 * This class is invoked once during the initial system installation by InstallUsecase. It
 * creates a Template entity with code "auth.delegate" bound to the "corporate-mail" theme
 * and appends a TemplateVersion containing an HTML email body with Handlebars placeholders
 * for the provider name ({{provider.name}}), login date ({{login.date}}), and IP address
 * ({{login.ip}}).
 *
 * The template is enabled immediately after creation so it is ready for the notification
 * subsystem to dispatch as soon as a delegate login event is recorded.
 */
class InstallDelegateLoginTemplate
{
    public function __construct(
        private readonly TemplateWriteGateway $templates,
        private readonly TemplateVersionWriteGateway $versions,
    ) {
    }

    /**
     * Creates and enables the "auth.delegate" mail template along with its first version
     * containing the delegate login notification email body.
     */
    public function install(): void
    {
        $tpl = new TemplateAttributes();
        $tpl->uid(Random::comb());
        $tpl->code('auth.delegate');
        $tpl->channel(TemplateChannelOptions::MAIL);
        $tpl->theme('corporate-mail');
        $tpl->enabled(true);
        $created = $this->templates->create(Template::create($tpl));
        $this->templates->update($created, $created->enable());

        $body = <<<'BODY'
<p>Hello {{user.name}},</p>
<p>A new sign-in to your account was detected via <strong>{{provider.name}}</strong>.</p>
<table style="margin:16px 0;font-size:14px;color:#374151;">
  <tr><td style="padding:4px 12px 4px 0;color:#6b7280;">Date</td><td>{{login.date}}</td></tr>
  <tr><td style="padding:4px 12px 4px 0;color:#6b7280;">IP address</td><td>{{login.ip}}</td></tr>
</table>
<p style="font-size:13px;color:#6b7280;">
  If this was not you, please secure your account immediately.
</p>
BODY;

        $ver = new TemplateVersionAttributes();
        $ver->uid(Random::comb());
        $ver->template($created);
        $ver->subject('New sign-in via {{provider.name}}');
        $ver->contentHtml($body);
        $this->versions->create(TemplateVersion::create($ver));
    }
}
