<?php

# @autogenerated
declare(strict_types=1);

namespace Civi\Lughauth\Features\Access\SecurityDomain\Application\Usecase\Enable;

use Psr\EventDispatcher\EventDispatcherInterface;
use Throwable;
use Civi\Lughauth\Shared\Security\Allow;
use Civi\Lughauth\Shared\Exception\UnauthorizedException;
use Civi\Lughauth\Shared\Exception\NotFoundException;
use Civi\Lughauth\Features\Access\SecurityDomain\Domain\SecurityDomainRef;
use Civi\Lughauth\Features\Access\SecurityDomain\Domain\SecurityDomainAttributes;
use Civi\Lughauth\Features\Access\SecurityDomain\Application\Service\Visibility\SecurityDomainVisibilityService;
use Civi\Lughauth\Features\Access\SecurityDomain\Domain\Gateway\SecurityDomainWriteGateway;
use Civi\Lughauth\Shared\Observability\LoggerAwareTrait;
use Civi\Lughauth\Shared\Observability\TracerAwareTrait;

class SecurityDomainEnableUsecase
{
    use LoggerAwareTrait;
    use TracerAwareTrait;

    public function __construct(
        private readonly EventDispatcherInterface $dispacher,
        private readonly SecurityDomainVisibilityService $visibility,
        private readonly SecurityDomainWriteGateway $writer
    ) {
    }

    public function allowEnable(?SecurityDomainRef $ref = null): Allow
    {
        $this->logDebug("Check allow of Enable usecase for Security domain");
        $span = $this->startSpan("Check allow of Enable usecase for Security domain");
        try {
            $result = $this->dispacher->dispatch(new SecurityDomainEnableAllowProposal(Allow::allowed('enable', 'Allowed to Security domain by default'), $ref));
            return $result->allow;
        } catch (Throwable $ex) {
            $span->recordException($ex);
            throw $ex;
        } finally {
            $span->end();
        }
    }
    public function enable(string $uid): SecurityDomainAttributes
    {
        $this->logDebug("Run Enable usecase for Security domain");
        $span = $this->startSpan("Run Enable usecase for Security domain");
        try {
            $ref = new SecurityDomainRef($uid);
            $allow = $this->allowEnable($ref);
            if (!$allow->allowed) {
                throw new UnauthorizedException($allow->reason);
            }
            $input = $this->dispacher->dispatch(new SecurityDomainEnableInputProposal($ref));
            if (!$original = $this->visibility->retrieveVisibleForUpdate($input->ref)) {
                throw new NotFoundException($uid);
            }
            $modified = $original->enable();
            $result = $this->writer->update($original, $modified);
            $output = $this->visibility->copyWithHidden($result->toAttributes());
            return $this->dispacher->dispatch(new SecurityDomainEnableOutputProposal($output))->attributes;
        } catch (Throwable $ex) {
            $span->recordException($ex);
            throw $ex;
        } finally {
            $span->end();
        }
    }
}
