<?php

# @autogenerated
declare(strict_types=1);

namespace Civi\Lughauth\Features\Access\TenantTermsOfUse\Application\Service\Visibility;

use Civi\Lughauth\Features\Access\TenantTermsOfUse\Domain\TenantTermsOfUseAttributes;
use Civi\Lughauth\Features\Access\TenantTermsOfUse\Domain\TenantTermsOfUse;

class TenantTermsOfUseExposeProposal
{
    public function __construct(
        public readonly TenantTermsOfUse $tenantTermsOfUse,
        private TenantTermsOfUseAttributes $tenantTermsOfUseAttributes
    ) {
    }
    public function getAttributes(): TenantTermsOfUseAttributes
    {
        return $this->tenantTermsOfUseAttributes;
    }
    public function with(TenantTermsOfUseAttributes $tenantTermsOfUseAttributes)
    {
        $this->tenantTermsOfUseAttributes = $tenantTermsOfUseAttributes;
    }
}
