<?php

# @autogenerated
declare(strict_types=1);

namespace Civi\Lughauth\Features\Access\TenantTermsOfUse\Application\Service\Visibility;

use Psr\EventDispatcher\EventDispatcherInterface;
use Throwable;
use Civi\Lughauth\Features\Access\Tenant\Application\Service\Visibility\TenantVisibilityService;
use Civi\Lughauth\Shared\Exception\NotFoundException;
use Civi\Lughauth\Features\Access\TenantTermsOfUse\Domain\TenantTermsOfUseRef;
use Civi\Lughauth\Features\Access\TenantTermsOfUse\Domain\TenantTermsOfUseAttributes;
use Civi\Lughauth\Features\Access\TenantTermsOfUse\Domain\TenantTermsOfUse;
use Civi\Lughauth\Features\Access\TenantTermsOfUse\Domain\Gateway\TenantTermsOfUseFilter;
use Civi\Lughauth\Features\Access\TenantTermsOfUse\Domain\Gateway\TenantTermsOfUseCursor;
use Civi\Lughauth\Features\Access\TenantTermsOfUse\Domain\Gateway\TenantTermsOfUseReadGateway;
use Civi\Lughauth\Features\Access\TenantTermsOfUse\Domain\Gateway\TenantTermsOfUseSlide;
use Civi\Lughauth\Features\Access\TenantTermsOfUse\Domain\Gateway\TenantTermsOfUseWriteGateway;
use Civi\Lughauth\Shared\Observability\LoggerAwareTrait;
use Civi\Lughauth\Shared\Observability\TracerAwareTrait;

class TenantTermsOfUseVisibilityService
{
    use LoggerAwareTrait;
    use TracerAwareTrait;

    public function __construct(
        private readonly EventDispatcherInterface $dispacher,
        private readonly TenantTermsOfUseReadGateway $readGateway,
        private readonly TenantTermsOfUseWriteGateway $writeGateway,
        private readonly TenantVisibilityService $tenantVisibilityService
    ) {
    }

    public function prepareVisibleData(TenantTermsOfUse $content): TenantTermsOfUseAttributes
    {
        $this->logDebug("Prepare hidratation to visible data for Tenant terms of use");
        $span = $this->startSpan("Prepare hidratation to visible data for Tenant terms of use");
        try {
            $attributes = $content->toAttributes();
            $result = $this->dispacher->dispatch(new TenantTermsOfUseExposeProposal($content, $attributes));
            return $result->getAttributes();
        } catch (Throwable $ex) {
            $span->recordException($ex);
            throw $ex;
        } finally {
            $span->end();
        }
    }
    public function copyWithFixed(TenantTermsOfUseAttributes $attributes, ?TenantTermsOfUse $original = null): TenantTermsOfUseAttributes
    {
        $this->logDebug("Copy with fixed for Tenant terms of use");
        $span = $this->startSpan("Copy with fixed for  Tenant terms of use");
        try {
            $visible = $this->visiblesReferences($attributes);
            $fixed = $this->fieldsToFix($original);
            foreach ($fixed as $field) {
                $visible->unset($field);
            }
            $result = $this->dispacher->dispatch(new TenantTermsOfUsePresetProposal($attributes, $original));
            return $result->attributes;
        } catch (Throwable $ex) {
            $span->recordException($ex);
            throw $ex;
        } finally {
            $span->end();
        }
    }

    public function copyWithHidden(TenantTermsOfUseAttributes $attributes, ?TenantTermsOfUse $original = null): TenantTermsOfUseAttributes
    {
        $this->logDebug("Copy with hidden for Tenant terms of use");
        $span = $this->startSpan("Copy with hidden for  Tenant terms of use");
        try {
            $hidden = $this->fieldsToHide($original);
            foreach ($hidden as $field) {
                $attributes->unset($field);
            }
            return $attributes;
        } catch (Throwable $ex) {
            $span->recordException($ex);
            throw $ex;
        } finally {
            $span->end();
        }
    }

    public function checkVisibility(\Iterator|string|TenantTermsOfUseRef $value): bool
    {
        $this->logDebug("Check visibility of an iterator for Tenant terms of use");
        $span = $this->startSpan("Check visibility of an iterator for  Tenant terms of use");
        try {
            if (is_a($value, \Iterator::class)) {
                $ids = [];
                foreach ($value as $val) {
                    $ids[] = $val->uid();
                }
                $filter = new TenantTermsOfUseFilter(uids: $ids);
                return count($ids) == $this->countVisibles($filter);
            } elseif (is_a($value, TenantTermsOfUseRef::class)) {
                return !!$this->retrieveVisibleForUpdate($value);
            } else {
                return !!$this->retrieveVisibleForUpdate(new TenantTermsOfUseRef($value));
            }
        } catch (Throwable $ex) {
            $span->recordException($ex);
            throw $ex;
        } finally {
            $span->end();
        }
    }
    public function listVisibles(TenantTermsOfUseFilter $filter, ?TenantTermsOfUseCursor $cursor = null): TenantTermsOfUseSlide
    {
        $this->logDebug("List visibles for Tenant terms of use");
        $span = $this->startSpan("List visibles for  Tenant terms of use");
        try {
            $visibleFilter = $this->applyPreVisibilityFilter($filter);
            $result = $this->readGateway->list($visibleFilter, $cursor);
            return $result->slide(function ($item) {
                return $this->evaluatePostVisibility($item);
            });
        } catch (Throwable $ex) {
            $span->recordException($ex);
            throw $ex;
        } finally {
            $span->end();
        }
    }
    public function countVisibles(TenantTermsOfUseFilter $filter): int
    {
        $this->logDebug("Count visibles for Tenant terms of use");
        $span = $this->startSpan("Count visibles for  Tenant terms of use");
        try {
            $visibleFilter = $this->applyPreVisibilityFilter($filter);
            return $this->readGateway->count($visibleFilter);
        } catch (Throwable $ex) {
            $span->recordException($ex);
            throw $ex;
        } finally {
            $span->end();
        }
    }
    public function listVisiblesForUpdate(TenantTermsOfUseFilter $filter, ?TenantTermsOfUseCursor $cursor = null): TenantTermsOfUseSlide
    {
        $this->logDebug("List visibles for update for Tenant terms of use");
        $span = $this->startSpan("List visibles for update for  Tenant terms of use");
        try {
            $visibleFilter = $this->applyPreVisibilityFilter($filter);
            $result = $this->writeGateway->listForUpdate($visibleFilter, $cursor);
            return $result->slide(function ($item) {
                return $this->evaluatePostVisibility($item);
            });
        } catch (Throwable $ex) {
            $span->recordException($ex);
            throw $ex;
        } finally {
            $span->end();
        }
    }
    public function countVisiblesForUpdate(TenantTermsOfUseFilter $filter): int
    {
        $this->logDebug("Count visibles for update for Tenant terms of use");
        $span = $this->startSpan("Count visibles for update for  Tenant terms of use");
        try {
            $visibleFilter = $this->applyPreVisibilityFilter($filter);
            return $this->writeGateway->countForUpdate($visibleFilter);
        } catch (Throwable $ex) {
            $span->recordException($ex);
            throw $ex;
        } finally {
            $span->end();
        }
    }
    public function retrieveVisible(TenantTermsOfUseRef $ref): ?TenantTermsOfUse
    {
        $this->logDebug("Retrieve visible for Tenant terms of use");
        $span = $this->startSpan("Retrieve visible for  Tenant terms of use");
        try {
            $filter = new TenantTermsOfUseFilter(uids: [$ref->uid()]);
            $visibleFilter = $this->applyPreVisibilityFilter($filter);
            if ($readed = $this->readGateway->retrieve($visibleFilter)) {
                return $this->evaluatePostVisibility($readed) ? $readed : null;
            } else {
                return null;
            }
        } catch (Throwable $ex) {
            $span->recordException($ex);
            throw $ex;
        } finally {
            $span->end();
        }
    }
    public function retrieveVisibleForUpdate(TenantTermsOfUseRef $ref): ?TenantTermsOfUse
    {
        $this->logDebug("Retrieve visible for update for Tenant terms of use");
        $span = $this->startSpan("Retrieve visible for update for  Tenant terms of use");
        try {
            $filter = new TenantTermsOfUseFilter(uids: [$ref->uid()]);
            $visibleFilter = $this->applyPreVisibilityFilter($filter);
            if ($readed = $this->writeGateway->retrieveForUpdate($visibleFilter)) {
                return $this->evaluatePostVisibility($readed) ? $readed : null;
            } else {
                return null;
            }
        } catch (Throwable $ex) {
            $span->recordException($ex);
            throw $ex;
        } finally {
            $span->end();
        }
    }
    public function fieldsToFix(?TenantTermsOfUseRef $ref = null): array
    {
        $this->logDebug("Check fields to fix for Tenant terms of use");
        $span = $this->startSpan("Check fields for fix for Tenant terms of use");
        try {
            $result = $this->dispacher->dispatch(new TenantTermsOfUseFixedFieldsProposal(TenantTermsOfUse::calculatedFields(), $ref));
            return array_merge($this->fieldsToHide($ref), $result->fields);
        } catch (Throwable $ex) {
            $span->recordException($ex);
            throw $ex;
        } finally {
            $span->end();
        }
    }

    public function fieldsToHide(?TenantTermsOfUseRef $ref = null): array
    {
        $this->logDebug("Check fields to hide for Tenant terms of use");
        $span = $this->startSpan("Check fields to hide for  Tenant terms of use");
        try {
            $result = $this->dispacher->dispatch(new TenantTermsOfUseHideFieldsProposal([], $ref));
            return $result->fields;
        } catch (Throwable $ex) {
            $span->recordException($ex);
            throw $ex;
        } finally {
            $span->end();
        }
    }

    private function visiblesReferences(TenantTermsOfUseAttributes $attributes): TenantTermsOfUseAttributes
    {
        $this->logDebug("Check visibility of parent references for Tenant terms of use");
        $span = $this->startSpan("Check visibility of parent references for  Tenant terms of use");
        try {
            if ($attributes->getTenant() && !$this->tenantVisibilityService->checkVisibility($attributes->getTenant())) {
                throw new NotFoundException("Unknow Tenant " . $attributes->getTenant());
            }
            return $attributes;
        } catch (Throwable $ex) {
            $span->recordException($ex);
            throw $ex;
        } finally {
            $span->end();
        }
    }
    private function applyPreVisibilityFilter(TenantTermsOfUseFilter $filter)
    {
        $this->logDebug("Compose visibility filter for Tenant terms of use");
        $span = $this->startSpan("Compose visibility filter for  Tenant terms of use");
        try {
            $result = $this->dispacher->dispatch(new TenantTermsOfUseFilterProposal($filter));
            return $result->tenantTermsOfUseFilter;
        } catch (Throwable $ex) {
            $span->recordException($ex);
            throw $ex;
        } finally {
            $span->end();
        }
    }
    private function evaluatePostVisibility(TenantTermsOfUse $value): bool
    {
        $this->logDebug("Check if item is visible for Tenant terms of use");
        $span = $this->startSpan("Check if item is visible for  Tenant terms of use");
        try {
            $result = $this->dispacher->dispatch(new TenantTermsOfUseVisibilityProposal(true, $value));
            return $result->visible;
        } catch (Throwable $ex) {
            $span->recordException($ex);
            throw $ex;
        } finally {
            $span->end();
        }
    }
}
