<?php

# @autogenerated
declare(strict_types=1);

namespace Civi\Lughauth\Features\Access\TenantTermsOfUse\Application\Service\Visibility;

use Civi\Lughauth\Features\Access\TenantTermsOfUse\Domain\TenantTermsOfUse;

class TenantTermsOfUseVisibilityCheck
{
    public function __construct(
        public bool $visible,
        public readonly TenantTermsOfUse $tenantTermsOfUse
    ) {
    }
    public function deny()
    {
        $this->visible = false;
    }
}
