<?php

/* @autogenerated */
declare(strict_types=1);

namespace Civi\Lughauth\Features\Oidc\MagicLink\Domain\Gateway;

interface MagicLinkEnabledGateway
{
    public function isEnabled(string $tenantName): bool;
}
