<?php

/* @autogenerated */
declare(strict_types=1);

namespace Civi\Lughauth\Features\Oidc\UserInvitation\Infrastructure\Driver\Html;

use Psr\Http\Message\ResponseInterface;
use Psr\Http\Message\ServerRequestInterface;
use Civi\Lughauth\Features\Oidc\Theme\Application\DecorateHtml;
use Civi\Lughauth\Features\Oidc\UserInvitation\Application\Usecase\Accept\InvitationAcceptParams;
use Civi\Lughauth\Features\Oidc\UserInvitation\Application\Usecase\Accept\InvitationAcceptUsecase;

class InvitationAcceptHtml
{
    public function __construct(
        private readonly InvitationAcceptUsecase $usecase,
        private readonly DecorateHtml $decorator,
    ) {
    }

    public function form(ServerRequestInterface $request, ResponseInterface $response, array $args): ResponseInterface
    {
        $tenant      = $args['tenant'];
        $query       = $request->getQueryParams();
        $rawToken    = (string) ($query['token'] ?? '');
        $clientId    = (string) ($query['client_id'] ?? '');
        $redirectUri = (string) ($query['redirect_uri'] ?? '');

        if ($rawToken === '') {
            return $this->renderError($request, $response, $tenant, 'Invalid invitation link.');
        }

        $html = $this->buildForm($rawToken, $tenant, $clientId, $redirectUri);
        $response->getBody()->write(
            $this->decorator->getFullPage($request, 'Accept invitation', $html, 'en', 'index', $tenant)
        );
        return $response;
    }

    public function accept(ServerRequestInterface $request, ResponseInterface $response, array $args): ResponseInterface
    {
        $tenant = $args['tenant'];
        $body   = (array) ($request->getParsedBody() ?? []);

        $rawToken    = (string) ($body['token'] ?? '');
        $password    = (string) ($body['password'] ?? '');
        $clientId    = (string) ($body['client_id'] ?? '');
        $redirectUri = (string) ($body['redirect_uri'] ?? '');

        if ($rawToken === '' || $password === '') {
            return $this->renderError($request, $response, $tenant, 'Token and password are required.');
        }

        try {
            $params = new InvitationAcceptParams(
                rawToken: $rawToken,
                tenantName: $tenant,
                password: $password,
                clientId: $clientId,
                redirectUri: $redirectUri,
            );
            $redirectUrl = $this->usecase->accept($params);
            return $response->withStatus(302)->withHeader('Location', $redirectUrl);
        } catch (\DomainException $e) {
            return $this->renderError($request, $response, $tenant, $e->getMessage());
        }
    }

    private function buildForm(string $rawToken, string $tenant, string $clientId, string $redirectUri): string
    {
        $token       = htmlspecialchars($rawToken);
        $clientIdVal = htmlspecialchars($clientId);
        $redirectVal = htmlspecialchars($redirectUri);
        $action      = './accept';
        return <<<HTML
            <h1>Accept invitation</h1>
            <p>Create your password to activate your account.</p>
            <form method="POST" action="{$action}">
                <input type="hidden" name="token" value="{$token}" />
                <input type="hidden" name="client_id" value="{$clientIdVal}" />
                <input type="hidden" name="redirect_uri" value="{$redirectVal}" />
                <label>Password
                    <input type="password" name="password" required autocomplete="new-password" />
                </label>
                <label>Confirm password
                    <input type="password" name="password_confirm" required autocomplete="new-password" />
                </label>
                <input class="primary-button" type="submit" value="Activate account" />
            </form>
            HTML;
    }

    private function renderError(ServerRequestInterface $request, ResponseInterface $response, string $tenant, string $message): ResponseInterface
    {
        $html = '<h1>Invitation</h1><p class="error">' . htmlspecialchars($message) . '</p>';
        $response->getBody()->write(
            $this->decorator->getFullPage($request, 'Invitation', $html, 'en', 'index', $tenant)
        );
        return $response->withStatus(400);
    }
}
