<?php

/* @autogenerated */
declare(strict_types=1);

use PHPUnit\Framework\TestCase;
use Civi\Lughauth\Shared\Infrastructure\Event\QueueSource;

final class QueueSourceUnitTest extends TestCase
{
    public function testPropertiesStored(): void
    {
        $source = new QueueSource('dsn', 'user.*', 'exchange', 'queue', false, 10, 5, 2);

        $this->assertSame('dsn', $source->dsn);
        $this->assertSame('user.*', $source->routingKeyMask);
        $this->assertSame('exchange', $source->exchangeName);
        $this->assertSame('queue', $source->defaultQueueName);
        $this->assertFalse($source->declareQueue);
        $this->assertSame(10, $source->maxMessages);
        $this->assertSame(5, $source->maxSeconds);
        $this->assertSame(2, $source->prefetch);
    }
}
