<?php

/* @autogenerated */
declare(strict_types=1);

namespace Civi\Lughauth\Features\Oidc\User\Domain\Gateway;

interface ChangePasswordRepository
{
    public function requestForChange(string $url, string $tenant, string $username): void;

    public function allowRecover(string $tenant): bool;

    public function validateChangeRequest(string $tenant, string $code, string $newPass): ?string;

    public function forceUpdatePassword(string $tenant, string $username, string $oldPass, string $newPass): bool;
}
