<?php

/* @autogenerated */
declare(strict_types=1);

namespace Civi\Lughauth\Features\Oidc\User\Domain\Gateway;

interface RegisterUserRepository
{
    public function allowRegister(string $tenant): bool;

    public function getRegisterConsent(string $tenant): ?string;

    public function requestForRegister(string $url, string $tenant, string $email, string $password);

    public function verifyRegister(string $tenant, string $code): ?string;
}
