<?php

# @autogenerated
declare(strict_types=1);

namespace Civi\Lughauth\Features\Access\UserAccessTemporalCode\Domain\ValueObject;

use Civi\Lughauth\Shared\Value\Validation\ConstraintFailList;
use Civi\Lughauth\Shared\Value\Validation\ConstraintFail;
use Civi\Lughauth\Shared\Value\Validation\Rule\Length;

class UserAccessTemporalCodeRegisterUrlVO
{
    public static function empty(): UserAccessTemporalCodeRegisterUrlVO
    {
        return new UserAccessTemporalCodeRegisterUrlVO(null);
    }
    public static function from(UserAccessTemporalCodeRegisterUrlVO|string|null $value): UserAccessTemporalCodeRegisterUrlVO
    {
        if (is_a($value, UserAccessTemporalCodeRegisterUrlVO::class)) {
            // If is a ValueObject, its already validated
            return $value;
        } else {
            // If is not a ValueObject, validation is need and exception throw
            $errorsList = new ConstraintFailList();
            $candidate = self::tryFrom($value, $errorsList);
            if ($errorsList->hasErrors()) {
                throw $errorsList->asConstraintException();
            }
            return $candidate;
        }
    }
    public static function tryFrom(mixed $value, ConstraintFailList $list): ?UserAccessTemporalCodeRegisterUrlVO
    {
        if (is_a($value, UserAccessTemporalCodeRegisterUrlVO::class)) {
            // If is a ValueObject, its already validated... nothing to append
            return $value;
        } elseif (!$value) {
            return new UserAccessTemporalCodeRegisterUrlVO($value);
        } elseif (is_string($value)) {
            // If is a ValueObject, we need to append all the errors for the context
            $valid = true;
            foreach (self::rules() as $rule) {
                if ($fail = $rule->check($value)) {
                    $list->add(ConstraintFail::fromRuleFail('registerUrl', $fail));
                    $valid = false;
                }
            }
            return $valid ? new UserAccessTemporalCodeRegisterUrlVO($value) : null;
        } else {
            $list->add(new ConstraintFail('wrong_type', ['registerUrl'], [$value], ['string']));
            return null;
        }
    }
    public static function rules(): array
    {
        return [
          new Length(min: null, max: 250),
        ];
    }
    /**
     * private constructor to avoid build a value without all the rule validations.
     */
    private function __construct(
        private readonly ?string $registerUrl
    ) {
    }
    public function value(): ?string
    {
        return $this->registerUrl;
    }
}
