<?php

# @autogenerated
declare(strict_types=1);

namespace Civi\Lughauth\Features\Access\Master\RelyingParty\Domain\Formula;

use Civi\Lughauth\Features\Access\Master\RelyingParty\Domain\RelyingParty;
use Civi\Lughauth\Features\Access\Master\RelyingParty\Domain\ValueObject\RelyingPartyEnabledVO;

class EnabledCalculator
{
    public static function calculateEnabled(?RelyingParty $original = null): ?RelyingPartyEnabledVO
    {
        return $original ? $original->enabled() : RelyingPartyEnabledVO::from(false);
    }
}
