<?php

# @autogenerated
declare(strict_types=1);

namespace Civi\Lughauth\Features\Oidc\Authentication\Domain;

use Psr\Http\Message\ServerRequestInterface;
use Civi\Lughauth\Shared\Context;

final class OidcFlowContext
{
    public function __construct(
        public readonly string $tenant,
        public readonly string $clientId,
        public readonly string $redirect,
        public readonly string $scope,
        public readonly string $responseType,
        public readonly string $state,
        public readonly string $nonce,
        public readonly array $audiences,
        public readonly string $prompt,
        public readonly string $locale,
        public readonly string $baseUrl,
        public readonly string $issuer,
        public readonly ?string $sessionId,
        public readonly ?string $preSessionId,
        public readonly ?string $codeChallenge,
        public readonly ?string $codeChallengeMethod,
    ) {
    }

    public static function fromRequest(ServerRequestInterface $request, string $tenant, Context $context): self
    {
        $query = $request->getQueryParams();
        $cookies = $request->getCookieParams();
        $acceptLanguage = $request->getHeader('accept-language');

        $baseUrl = $context->getBaseUrl();
        $issuer = $baseUrl . '/openid/' . $tenant;
        $audiences = self::normalizeAudiences($query['audience'] ?? null);

        return new self(
            tenant: $tenant,
            clientId: (string) ($query['client_id'] ?? ''),
            redirect: (string) ($query['redirect_uri'] ?? ''),
            scope: (string) ($query['scope'] ?? ''),
            responseType: (string) ($query['response_type'] ?? ''),
            state: (string) ($query['state'] ?? ''),
            nonce: (string) ($query['nonce'] ?? ''),
            audiences: $audiences,
            prompt: (string) ($query['prompt'] ?? ''),
            locale: $acceptLanguage[0] ?? '',
            baseUrl: $baseUrl,
            issuer: $issuer,
            sessionId: $cookies['AUTH_SESSION_ID_' . strtoupper($tenant)] ?? null,
            preSessionId: $cookies['PRE_SESSION_ID'] ?? null,
            codeChallenge: isset($query['code_challenge']) && $query['code_challenge'] !== '' ? (string) $query['code_challenge'] : null,
            codeChallengeMethod: isset($query['code_challenge_method']) && $query['code_challenge_method'] !== '' ? (string) $query['code_challenge_method'] : null,
        );
    }

    /**
     * @return string[]
     *
     * @psalm-return list<non-empty-string>
     */
    private static function normalizeAudiences(mixed $audience): array
    {
        if (is_array($audience)) {
            $raw = $audience;
        } elseif (is_string($audience)) {
            $raw = $audience === '' ? [] : explode(',', $audience);
        } else {
            $raw = [];
        }

        $items = array_map(static fn ($value): string => trim((string) $value), $raw);
        $items = array_filter($items, static fn (string $value): bool => $value !== '');

        return array_values(array_unique($items));
    }
}
