<?php

# @autogenerated
declare(strict_types=1);

namespace Civi\Lughauth\Features\Document\TemplateSnippet\Domain\ValueObject;

use Civi\Lughauth\Shared\Value\Validation\ConstraintFailList;
use Civi\Lughauth\Shared\Value\Validation\ConstraintFail;

class TemplateSnippetVersionVO
{
    public static function empty(): TemplateSnippetVersionVO
    {
        return new TemplateSnippetVersionVO(null);
    }
    public static function from(TemplateSnippetVersionVO|int|null $value): TemplateSnippetVersionVO
    {
        return self::fromUnsafe($value);
    }
    public static function tryFrom(mixed $value, ConstraintFailList $list): ?TemplateSnippetVersionVO
    {
        if ($value instanceof TemplateSnippetVersionVO) {
            // If is a ValueObject, its already validated... nothing to append
            return $value;
        } elseif (!$value) {
            return new TemplateSnippetVersionVO($value);
        } elseif (is_integer($value)) {
            return new TemplateSnippetVersionVO($value);
        } else {
            $list->add(new ConstraintFail('wrong_type', ['version'], [$value], ['int']));
            return null;
        }
    }
    private static function fromUnsafe(mixed $value): TemplateSnippetVersionVO
    {
        if ($value instanceof TemplateSnippetVersionVO) {
            // If is a ValueObject, its already validated
            return $value;
        } else {
            // If is not a ValueObject, validation is need and exception throw
            $errorsList = new ConstraintFailList();
            $candidate = self::tryFrom($value, $errorsList);
            if ($errorsList->hasErrors()) {
                throw $errorsList->asConstraintException();
            }
            \assert($candidate instanceof TemplateSnippetVersionVO);
            return $candidate;
        }
    }
    /**
     * private constructor to avoid build a value without all the rule validations.
     */
    private function __construct(
        private readonly ?int $version
    ) {
    }
    public function value(): ?int
    {
        return $this->version;
    }
    public function equals(?TemplateSnippetVersionVO $other): bool
    {
        return $this->value() == $other?->value();
    }
}
