<?php

# @autogenerated
declare(strict_types=1);

namespace Civi\Lughauth\Features\Access\UserConsentedScopes\Infrastructure\Driven;

use Override;
use Throwable;
use Civi\Lughauth\Features\Access\UserConsentedScopes\Infrastructure\Connector\Pdo\UserConsentedScopesPdoConnector;
use Civi\Lughauth\Features\Access\UserConsentedScopes\Domain\Gateway\UserConsentedScopesReadGateway;
use Civi\Lughauth\Features\Access\UserConsentedScopes\Domain\Gateway\UserConsentedScopesSlide;
use Civi\Lughauth\Features\Access\UserConsentedScopes\Domain\Gateway\UserConsentedScopesFilter;
use Civi\Lughauth\Features\Access\UserConsentedScopes\Domain\Gateway\UserConsentedScopesCursor;
use Civi\Lughauth\Features\Access\UserConsentedScopes\Domain\UserConsentedScopesRef;
use Civi\Lughauth\Features\Access\UserConsentedScopes\Domain\UserConsentedScopes;
use Civi\Lughauth\Shared\Observability\LoggerAwareTrait;
use Civi\Lughauth\Shared\Observability\TracerAwareTrait;

class UserConsentedScopesReadRepositoryAdapter implements UserConsentedScopesReadGateway
{
    use LoggerAwareTrait;
    use TracerAwareTrait;

    public function __construct(
        private readonly UserConsentedScopesPdoConnector $conn,
    ) {
    }
    #[Override]
    public function resolve(UserConsentedScopesRef $ref): ?UserConsentedScopes
    {
        if ($ref instanceof UserConsentedScopes) {
            return $ref;
        } elseif (!$ref->_private_resolve) {
            $ref->_private_resolve = $this->conn->retrieve(new UserConsentedScopesFilter(uids: [ $ref->uid() ]));
        }
        return $ref->_private_resolve;
    }
    #[Override]
    public function list(?UserConsentedScopesFilter $filter = null, ?UserConsentedScopesCursor $cursor = null): UserConsentedScopesSlide
    {
        $this->logDebug("List for User consented scopes on adapter ");
        $span = $this->startSpan("List for User consented scopes on adapter");
        try {
            $values = $this->conn->list($filter, $cursor);
            $last = end($values);
            return new UserConsentedScopesSlide(function (UserConsentedScopesFilter $slide, ?UserConsentedScopesCursor $next) use ($filter) {
                return $this->list($filter, $next);
            }, new UserConsentedScopesCursor($cursor?->limit() ?? 100, false !== $last ? $last->uid() : null), $values);
        } catch (Throwable $ex) {
            $span->recordException($ex);
            throw $ex;
        } finally {
            $span->end();
        }
    }
    #[Override]
    public function retrieve(UserConsentedScopesFilter $filter): ?UserConsentedScopes
    {
        $this->logDebug("Retrieve for User consented scopes on adapter ");
        $span = $this->startSpan("Retrieve for User consented scopes on adapter");
        try {
            return $this->conn->retrieve($filter);
        } catch (Throwable $ex) {
            $span->recordException($ex);
            throw $ex;
        } finally {
            $span->end();
        }
    }
    #[Override]
    public function exists(UserConsentedScopesFilter $filter): bool
    {
        $this->logDebug("Exists for User consented scopes on adapter ");
        $span = $this->startSpan("Exists for User consented scopes on adapter");
        try {
            return $this->conn->exists($filter);
        } catch (Throwable $ex) {
            $span->recordException($ex);
            throw $ex;
        } finally {
            $span->end();
        }
    }
    #[Override]
    public function count(?UserConsentedScopesFilter $filter = null): int
    {
        $this->logDebug("Count for User consented scopes on adapter ");
        $span = $this->startSpan("Count for User consented scopes on adapter");
        try {
            return $this->conn->count($filter);
        } catch (Throwable $ex) {
            $span->recordException($ex);
            throw $ex;
        } finally {
            $span->end();
        }
    }
    #[Override]
    public function findOneByUid(string $uid): ?UserConsentedScopes
    {
        $this->logDebug("Find on by uid for User consented scopes on adapter");
        $span = $this->startSpan("Find on by uid for User consented scopes on adapter");
        try {
            return $this->conn->retrieve(new UserConsentedScopesFilter(uids: [$uid]));
        } catch (Throwable $ex) {
            $span->recordException($ex);
            throw $ex;
        } finally {
            $span->end();
        }
    }
}
