<?php

/* @autogenerated */
declare(strict_types=1);

namespace Civi\Lughauth\Features\Access\UserConsentedScopes\Infrastructure\Driven;

use Psr\EventDispatcher\EventDispatcherInterface;
use Closure;
use Override;
use Throwable;
use Civi\Lughauth\Features\Access\UserConsentedScopes\Domain\Gateway\UserConsentedScopesWriteGateway;
use Civi\Lughauth\Features\Access\UserConsentedScopes\Infrastructure\Connector\Pdo\UserConsentedScopesPdoConnector;
use Civi\Lughauth\Features\Access\UserConsentedScopes\Domain\Gateway\UserConsentedScopesSlide;
use Civi\Lughauth\Features\Access\UserConsentedScopes\Domain\Gateway\UserConsentedScopesCursor;
use Civi\Lughauth\Features\Access\UserConsentedScopes\Domain\Gateway\UserConsentedScopesFilter;
use Civi\Lughauth\Features\Access\UserConsentedScopes\Domain\UserConsentedScopesRef;
use Civi\Lughauth\Features\Access\UserConsentedScopes\Domain\UserConsentedScopes;
use Civi\Lughauth\Shared\Observability\LoggerAwareTrait;
use Civi\Lughauth\Shared\Observability\TracerAwareTrait;
use Civi\Lughauth\Shared\Infrastructure\EntityChangelog\EntityChangelogService;

class UserConsentedScopesWriteRepositoryAdapter implements UserConsentedScopesWriteGateway
{
    use LoggerAwareTrait;
    use TracerAwareTrait;

    public function __construct(
        private readonly UserConsentedScopesPdoConnector $conn,
        private readonly EventDispatcherInterface $dispatcher,
        private readonly EntityChangelogService $changelog,
    ) {
    }
    #[Override]
    public function resolveForUpdate(UserConsentedScopesRef $ref): ?UserConsentedScopes
    {
        return $this->conn->retrieveForUpdate(new UserConsentedScopesFilter(uids: [ $ref->uid() ]));
    }
    #[Override]
    public function listForUpdate(?UserConsentedScopesFilter $filter = null, ?UserConsentedScopesCursor $cursor = null): UserConsentedScopesSlide
    {
        $this->logDebug("List for update of User consented scopes on adapter ");
        $span = $this->startSpan("List for update of User consented scopes on adapter");
        try {
            $values = $this->conn->listForUpdate($filter, $cursor);
            $last = end($values);
            return new UserConsentedScopesSlide(function (UserConsentedScopesSlide $slide, ?UserConsentedScopesCursor$next) use ($filter) {
                return $this->listForUpdate($filter, $next);
            }, new UserConsentedScopesCursor($cursor?->limit() ?? 100, false !== $last ? $last->uid() : null), $values);
        } catch (Throwable $ex) {
            $span->recordException($ex);
            throw $ex;
        } finally {
            $span->end();
        }
    }
    #[Override]
    public function retrieveForUpdate(UserConsentedScopesFilter $filter): ?UserConsentedScopes
    {
        $this->logDebug("Retrieve for update of User consented scopes on adapter ");
        $span = $this->startSpan("Retrieve for update of User consented scopes on adapter");
        try {
            return $this->conn->retrieveForUpdate($filter);
        } catch (Throwable $ex) {
            $span->recordException($ex);
            throw $ex;
        } finally {
            $span->end();
        }
    }
    #[Override]
    public function existsForUpdate(UserConsentedScopesFilter $filter): bool
    {
        $this->logDebug("Exists for update of User consented scopes on adapter ");
        $span = $this->startSpan("Exists for update of User consented scopes on adapter");
        try {
            return $this->conn->existsForUpdate($filter);
        } catch (Throwable $ex) {
            $span->recordException($ex);
            throw $ex;
        } finally {
            $span->end();
        }
    }
    #[Override]
    public function countForUpdate(?UserConsentedScopesFilter $filter = null): int
    {
        $this->logDebug("Count for update of User consented scopes on adapter ");
        $span = $this->startSpan("Count for update of User consented scopes on adapter");
        try {
            return $this->conn->countForUpdate($filter);
        } catch (Throwable $ex) {
            $span->recordException($ex);
            throw $ex;
        } finally {
            $span->end();
        }
    }
    #[Override]
    public function create(UserConsentedScopes $entity, ?Closure $verify = null): UserConsentedScopes
    {
        $this->logDebug("Count for User consented scopes on adapter ");
        $span = $this->startSpan("Count for User consented scopes on adapter");
        try {
            $created = $this->conn->create($entity, $verify);
            $this->dispatch($entity);
            $this->changelog->recordChange('user-consented-scopes', $entity->uid() ?? 'no-id', $entity->asPublicJson());
            return $created;
        } catch (Throwable $ex) {
            $span->recordException($ex);
            throw $ex;
        } finally {
            $span->end();
        }
    }
    #[Override]
    public function update(UserConsentedScopesRef $ref, UserConsentedScopes $entity): UserConsentedScopes
    {
        $this->logDebug("Count for User consented scopes on adapter ");
        $span = $this->startSpan("Count for User consented scopes on adapter");
        try {
            $updated = $this->conn->update($entity);
            $this->dispatch($entity);
            $this->changelog->recordChange('user-consented-scopes', $entity->uid() ?? 'no-id', $entity->asPublicJson());
            return $updated;
        } catch (Throwable $ex) {
            $span->recordException($ex);
            throw $ex;
        } finally {
            $span->end();
        }
    }
    #[Override]
    public function delete(UserConsentedScopes $entity): bool
    {
        $this->logDebug("Count for User consented scopes on adapter ");
        $span = $this->startSpan("Count for User consented scopes on adapter");
        try {
            $result = $this->conn->delete($entity);
            $this->dispatch($entity);
            $this->changelog->recordDeletion('user-consented-scopes', $entity->uid() ?? 'no-id', $entity->asPublicJson());
            return $result;
        } catch (Throwable $ex) {
            $span->recordException($ex);
            throw $ex;
        } finally {
            $span->end();
        }
    }
    #[Override]
    public function findOneForUpdateByUid(string $uid): ?UserConsentedScopes
    {
        $this->logDebug("Find on by uid for User consented scopes on adapter");
        $span = $this->startSpan("Find on by uid for User consented scopes on adapter");
        try {
            return $this->conn->retrieveForUpdate(new UserConsentedScopesFilter(uids: [$uid]));
        } catch (Throwable $ex) {
            $span->recordException($ex);
            throw $ex;
        } finally {
            $span->end();
        }
    }
    private function dispatch(UserConsentedScopes $entity): void
    {
        $this->logDebug("Count for User consented scopes on adapter ");
        $span = $this->startSpan("Count for User consented scopes on adapter");
        try {
            foreach ($entity->getTheEvents() as $event) {
                $this->dispatcher->dispatch($event);
            }
        } catch (Throwable $ex) {
            $span->recordException($ex);
            throw $ex;
        } finally {
            $span->end();
        }
    }
}
