<?php

/* @autogenerated */
declare(strict_types=1);

namespace Civi\Lughauth\Features\Document\Snippet\Domain\Event;

use Override;
use Civi\Lughauth\Features\Document\Snippet\Domain\Snippet;
use Civi\Lughauth\Shared\Event\PublicEvent;

class SnippetCreateEvent extends SnippetEvent implements PublicEvent
{
    public function __construct(
        Snippet $payload
    ) {
        parent::__construct($payload);
    }
    #[Override]
    public function eventType(): string
    {
        return 'snippet.create';
    }
    #[Override]
    public function schemaVersion(): string
    {
        return 'v1';
    }
    #[Override]
    public function payload(): array
    {
        return $this->payload->asPublicJson();
    }
    #[Override]
    public function original(): array
    {
        return [];
    }
}
