<?php

/* @autogenerated */
declare(strict_types=1);

use PHPUnit\Framework\TestCase;
use Civi\Lughauth\Features\OAuth\Authentication\Domain\AuthenticationRequest;
use Civi\Lughauth\Features\OAuth\Authentication\Domain\AuthenticationResult;
use Civi\Lughauth\Features\OAuth\Authentication\Domain\ChallengesState;
use Civi\Lughauth\Features\OAuth\Authentication\Application\TokenGranter\ResolverForClientCredentials;
use Civi\Lughauth\Features\OAuth\Authentication\Application\TokenGranter\ResolverForPassword;
use Civi\Lughauth\Features\OAuth\Authentication\Application\TokenGranter\ResolverForRefresh;
use Civi\Lughauth\Features\OAuth\Authentication\Application\TokenGranter\ResolverForDevice;
use Civi\Lughauth\Features\OAuth\Authentication\Domain\Exception\OAuthTokenException;
use Civi\Lughauth\Features\OAuth\Client\Domain\ClientData;
use Civi\Lughauth\Features\OAuth\Device\Application\DeviceAuthorizationService;
use Civi\Lughauth\Features\OAuth\Device\Domain\DeviceAuthorizationGrantType;
use Civi\Lughauth\Features\OAuth\Device\Domain\Gateway\DeviceAuthorizationGateway;
use Civi\Lughauth\Features\OAuth\Device\Domain\Exception\DeviceAuthorizationException;
use Civi\Lughauth\Features\OAuth\TokenSecurity\Domain\Gateway\TokenSigner;
use Civi\Lughauth\Features\OAuth\TokenSecurity\Domain\Gateway\TokenRevocationGateway;
use Civi\Lughauth\Features\OAuth\User\Application\Usecase\LoginUsecase;

final class ResolversUnitTest extends TestCase
{
    // --- ResolverForClientCredentials ---

    public function test_client_credentials_can_handle_correct_grant(): void
    {
        $r = new ResolverForClientCredentials();
        $this->assertTrue($r->canHandle('client_credentials', []));
        $this->assertFalse($r->canHandle('password', []));
    }

    public function test_client_credentials_grants_all_allowed_scopes_when_no_scope_requested(): void
    {
        $resolver = new ResolverForClientCredentials();
        $client = new ClientData('svc', ['client_credentials'], true, ['api:read', 'api:write'], 3600);
        $req = new AuthenticationRequest($client, '', '');

        $result = $resolver->authenticate('tenant', $req, []);

        $this->assertTrue($result->valid);
        $this->assertStringContainsString('api:read', $result->scope);
        $this->assertStringContainsString('api:write', $result->scope);
    }

    public function test_client_credentials_intersects_scopes(): void
    {
        $resolver = new ResolverForClientCredentials();
        $client = new ClientData('svc', ['client_credentials'], true, ['api:read', 'api:write'], 3600);
        $req = new AuthenticationRequest($client, '', '');

        $result = $resolver->authenticate('tenant', $req, ['scope' => 'api:read']);

        $this->assertTrue($result->valid);
        $this->assertSame('api:read', $result->scope);
    }

    public function test_client_credentials_throws_invalid_scope_when_no_overlap(): void
    {
        $this->expectException(OAuthTokenException::class);
        $resolver = new ResolverForClientCredentials();
        $client = new ClientData('svc', ['client_credentials'], true, ['api:read'], 3600);
        $req = new AuthenticationRequest($client, '', '');

        $resolver->authenticate('tenant', $req, ['scope' => 'api:write']);
    }

    // --- ResolverForPassword ---

    public function test_password_can_handle_correct_grant(): void
    {
        $r = new ResolverForPassword($this->makeLoginUsecase());
        $this->assertTrue($r->canHandle('password', []));
        $this->assertFalse($r->canHandle('client_credentials', []));
    }

    public function test_password_delegates_to_login_usecase(): void
    {
        $authResult = new AuthenticationResult(valid: true, id: 'user-1', tenant: 'tenant');
        $login = $this->makeLoginUsecase(result: $authResult);
        $resolver = new ResolverForPassword($login);
        $client = new ClientData('c', ['password'], true);
        $req = new AuthenticationRequest($client, '', '');

        $result = $resolver->authenticate('tenant', $req, ['username' => 'alice', 'password' => 'pass']);

        $this->assertSame('user-1', $result->id);
    }

    // --- ResolverForRefresh ---

    public function test_refresh_can_handle_correct_grant(): void
    {
        $r = new ResolverForRefresh($this->makeLoginUsecase(), $this->makeSigner(), $this->makeRevocation());
        $this->assertTrue($r->canHandle('refresh_token', []));
        $this->assertFalse($r->canHandle('password', []));
    }

    public function test_refresh_returns_wrong_credentials_when_no_keypass(): void
    {
        $signer = $this->makeSigner(payload: ['sub' => 'u1']);
        $resolver = new ResolverForRefresh($this->makeLoginUsecase(), $signer, $this->makeRevocation());
        $client = new ClientData('c', ['refresh_token'], true);
        $req = new AuthenticationRequest($client, '', '');

        $result = $resolver->authenticate('tenant', $req, ['refresh_token' => 'some-token']);

        $this->assertFalse($result->valid);
    }

    public function test_refresh_returns_wrong_credentials_when_jti_revoked(): void
    {
        $signer = $this->makeSigner(payload: ['keypass' => 'user@x.com', 'jti' => 'jti-123']);
        $revocation = $this->makeRevocation(revoked: true);
        $resolver = new ResolverForRefresh($this->makeLoginUsecase(), $signer, $revocation);
        $client = new ClientData('c', ['refresh_token'], true);
        $req = new AuthenticationRequest($client, '', '');

        $result = $resolver->authenticate('tenant', $req, ['refresh_token' => 'some-token']);

        $this->assertFalse($result->valid);
    }

    // --- ResolverForDevice ---

    public function test_device_can_handle_correct_grant(): void
    {
        $gateway = $this->makeDeviceGateway();
        $service = new DeviceAuthorizationService($gateway);
        $r = new ResolverForDevice($service);
        $this->assertTrue($r->canHandle(DeviceAuthorizationGrantType::DEVICE_CODE, []));
        $this->assertFalse($r->canHandle('password', []));
    }

    public function test_device_throws_when_device_code_missing(): void
    {
        $this->expectException(DeviceAuthorizationException::class);
        $gateway = $this->makeDeviceGateway();
        $service = new DeviceAuthorizationService($gateway);
        $resolver = new ResolverForDevice($service);
        $client = new ClientData('c', [DeviceAuthorizationGrantType::DEVICE_CODE], true);
        $req = new AuthenticationRequest($client, '', '');

        $resolver->authenticate('tenant', $req, []);
    }

    // --- helpers ---

    private function makeLoginUsecase(?AuthenticationResult $result = null): LoginUsecase
    {
        return new class ($result) extends LoginUsecase {
            public function __construct(private ?AuthenticationResult $r = null)
            {
            }
            public function validatedUserData(string $t, string $u, string $p, AuthenticationRequest $r): AuthenticationResult
            {
                return $this->r ?? new AuthenticationResult(valid: true, id: 'u1', tenant: $t);
            }
            public function fillPreLoadById(string $t, AuthenticationRequest $r, ChallengesState $c): AuthenticationResult
            {
                return $this->r ?? new AuthenticationResult(valid: true, id: 'u1');
            }
        };
    }

    private function makeSigner(?array $payload = null): TokenSigner
    {
        return new class ($payload) implements TokenSigner {
            public function __construct(private ?array $payload)
            {
            }
            public function sign(string $t, array $d, \DateInterval $e): string
            {
                return 'tok';
            }
            public function keysAsJwks(string $t): \Jose\Component\Core\JWKSet
            {
                return new \Jose\Component\Core\JWKSet([]);
            }
            public function signKeypass(string $t, array $d, \DateInterval $e): string
            {
                return '';
            }
            public function verifyTokenPayload(string $t, string $tok): ?array
            {
                return $this->payload;
            }
            public function verifiedKeypass(string $t, string $tok): mixed
            {
                return null;
            }
            public function parseSignedPayload(string $t, string $tok): ?array
            {
                return null;
            }
        };
    }

    private function makeRevocation(bool $revoked = false): TokenRevocationGateway
    {
        return new class ($revoked) implements TokenRevocationGateway {
            public function __construct(private bool $revoked)
            {
            }
            public function revokeJti(string $j, string $t, string $type, \DateTimeImmutable $e): void
            {
            }
            public function isRevoked(string $j, string $t): bool
            {
                return $this->revoked;
            }
            public function cleanup(): void
            {
            }
        };
    }

    private function makeDeviceGateway(): DeviceAuthorizationGateway
    {
        return new class () implements DeviceAuthorizationGateway {
            public function create(\Civi\Lughauth\Features\OAuth\Device\Domain\DeviceAuthorization $a): void
            {
            }
            public function findByDeviceCode(string $c): ?\Civi\Lughauth\Features\OAuth\Device\Domain\DeviceAuthorization
            {
                return null;
            }
            public function findByUserCode(string $t, string $c): ?\Civi\Lughauth\Features\OAuth\Device\Domain\DeviceAuthorization
            {
                return null;
            }
            public function approve(string $c, AuthenticationResult $a): bool
            {
                return false;
            }
            public function deny(string $c): bool
            {
                return false;
            }
            public function touchPoll(string $c, \DateTimeImmutable $n): void
            {
            }
            public function consume(string $c): void
            {
            }
        };
    }
}
