<?php

# @autogenerated
declare(strict_types=1);

namespace Civi\Lughauth\Features\Access\UserIdentity\Domain\Event;

use Override;
use Civi\Lughauth\Features\Access\UserIdentity\Domain\UserIdentity;
use Civi\Lughauth\Shared\Event\PublicEvent;

class UserIdentityCreateEvent extends UserIdentityEvent implements PublicEvent
{
    public function __construct(
        UserIdentity $payload
    ) {
        parent::__construct($payload);
    }
    #[Override]
    public function eventType(): string
    {
        return 'user-identity.create';
    }
    #[Override]
    public function schemaVersion(): string
    {
        return 'v1';
    }
    #[Override]
    public function payload(): array
    {
        return $this->payload->asPublicJson();
    }
    #[Override]
    public function original(): array
    {
        return [];
    }
}
