<?php

# @autogenerated
declare(strict_types=1);
namespace Civi\Lughauth\Features\Document\TemplateVariable\Domain\ValueObject;

use Civi\Lughauth\Shared\Value\Validation\ConstraintFailList;
use Civi\Lughauth\Shared\Value\Validation\ConstraintFail;

class TemplateVariableVersionVO
{
  public static function empty(): TemplateVariableVersionVO
  {
      return new TemplateVariableVersionVO(null);
  }
  public static function from(TemplateVariableVersionVO|int|null $value): TemplateVariableVersionVO
  {
    return self::fromUnsafe($value);
  }
  public static function tryFrom(mixed $value, ConstraintFailList $list): ?TemplateVariableVersionVO
  {
    if ( $value instanceof TemplateVariableVersionVO ) {
      // If is a ValueObject, its already validated... nothing to append
      return $value;
    } else if( !$value ) {
      return new TemplateVariableVersionVO($value);
    } else if( is_integer($value)) {
      return new TemplateVariableVersionVO($value);
    } else {
      $list->add(new ConstraintFail('wrong_type', ['version'], [$value], ['int']));
      return null;
    }
  }
  private static function fromUnsafe(mixed $value): TemplateVariableVersionVO
  {
    if ($value instanceof TemplateVariableVersionVO) {
      // If is a ValueObject, its already validated
      return $value;
    } else {
      // If is not a ValueObject, validation is need and exception throw
      $errorsList = new ConstraintFailList();
      $candidate = self::tryFrom($value, $errorsList);
      if ($errorsList->hasErrors()) {
        throw $errorsList->asConstraintException();
      }
      \assert($candidate instanceof TemplateVariableVersionVO);
      return $candidate;
    }
  }
  /**
   * private constructor to avoid build a value without all the rule validations.
   */
  private function __construct(
    private readonly ?int $version
  ) {
  }
  public function value(): ?int
  {
    return $this->version;
  }
  public function equals(?TemplateVariableVersionVO $other): bool
  {
    return $this->value() == $other?->value();
  }
}
