<?php

# @autogenerated
declare(strict_types=1);

use Civi\Lughauth\Features\Access\TrustedClient\Domain\ValueObject\Holder\TrustedClientAllowedScopesM2mAttributeHolder;
use Civi\Lughauth\Shared\Value\Validation\ConstraintFailList;
use PHPUnit\Framework\TestCase;

/**
 * Unit tests for the TrustedClientAllowedScopesM2mAttributeHolder trait.
 *
 * Covers assignment, retrieval, default fallback,
 * transfer between holders, validation rules, and unset operations.
 */
class TrustedClientAllowedScopesM2mAttributeHolderUnitTest extends TestCase
{
    /**
     * Asserts that the code attribute is not assigned by default
     * and that getAllowedScopesM2m returns null on a freshly created holder.
     */
    public function testAllowedScopesM2mNotAssignedByDefault(): void
    {
        // Arrange
        $holder = new ImplWithTrustedClientAllowedScopesM2mAttributeHolderUnitTest();

        // Assert
        $this->assertFalse($holder->isAllowedScopesM2mAssigned());
        $this->assertNull($holder->getAllowedScopesM2m());
    }
}
class ImplWithTrustedClientAllowedScopesM2mAttributeHolderUnitTest
{
    use TrustedClientAllowedScopesM2mAttributeHolder;
    public function assertRules(ConstraintFailList $errorsList): self
    {
        $result = new self();
        $this->withAssertedAllowedScopesM2mRules($result, $errorsList);
        return $result;
    }

    public function applyDefaults(): void
    {
        $this->withDefaultAllowedScopesM2m();
    }
}
