<?php

# @autogenerated
declare(strict_types=1);

use PHPUnit\Framework\TestCase;
use Civi\Lughauth\Shared\Exception\ConstraintException;
use Civi\Lughauth\Shared\Value\Validation\ConstraintFailList;
use Civi\Lughauth\Features\Access\UserGrantedClientScopes\Domain\ValueObject\UserGrantedClientScopesVersionVO;

final class UserGrantedClientScopesVersionVOUnitTest extends TestCase
{
    public function test_asignation_keep_value(): void
    {
        $value = 1;
        $ref = UserGrantedClientScopesVersionVO::from($value);
        $this->assertEquals(1, $ref->value());
        $other = UserGrantedClientScopesVersionVO::tryFrom($ref, new ConstraintFailList());
        $this->assertSame($other, $ref);
        $more = UserGrantedClientScopesVersionVO::from($ref);
        $this->assertSame($more, $ref);
    }
    public function test_asignation_invalid_type(): void
    {
        $errors = new ConstraintFailList();
        $other = UserGrantedClientScopesVersionVO::tryFrom('1', $errors);
        $this->assertNull($other);
        $this->assertTrue($errors->hasErrors());
    }
    public function test_optimist_asignation_invalid_type(): void
    {
        $this->expectException(ConstraintException::class);
        $method = new ReflectionMethod(UserGrantedClientScopesVersionVO::class, 'fromUnsafe');
        $method->invoke(null, [11, "bad"]);
    }
    public function test_equals(): void
    {
        $one = UserGrantedClientScopesVersionVO::from(1);
        $same = UserGrantedClientScopesVersionVO::from(1);
        $other = UserGrantedClientScopesVersionVO::from(2);
        $withEmpty = $one->equals(null);
        $withSame = $one->equals($same);
        $withOther = $one->equals($other);

        $this->assertFalse($withEmpty);
        $this->assertTrue($withSame);
        $this->assertFalse($withOther);
    }
    public function test_empty(): void
    {
        $ref = UserGrantedClientScopesVersionVO::empty();
        $this->assertNull($ref->value());
    }
    public function test_try_from_empty(): void
    {
        $ref = UserGrantedClientScopesVersionVO::tryFrom(null, new ConstraintFailList());
        $this->assertNull($ref->value());
    }
}
