<?php

/* @autogenerated */
declare(strict_types=1);

use Civi\Lughauth\Features\Access\UserProfile\Domain\ValueObject\Holder\UserProfileNicknameAttributeHolder;
use Civi\Lughauth\Shared\Value\Validation\ConstraintFailList;
use PHPUnit\Framework\TestCase;

/**
 * Unit tests for the UserProfileNicknameAttributeHolder trait.
 *
 * Covers assignment, retrieval, default fallback,
 * transfer between holders, validation rules, and unset operations.
 */
class UserProfileNicknameAttributeHolderUnitTest extends TestCase
{
    /**
     * Asserts that the code attribute is not assigned by default
     * and that getNickname returns null on a freshly created holder.
     */
    public function testNicknameNotAssignedByDefault(): void
    {
        // Arrange
        $holder = new ImplWithUserProfileNicknameAttributeHolderUnitTest();

        // Assert
        $this->assertFalse($holder->isNicknameAssigned());
        $this->assertNull($holder->getNickname());
    }
}
class ImplWithUserProfileNicknameAttributeHolderUnitTest
{
    use UserProfileNicknameAttributeHolder;
    public function assertRules(ConstraintFailList $errorsList): self
    {
        $result = new self();
        $this->withAssertedNicknameRules($result, $errorsList);
        return $result;
    }

    public function applyDefaults(): void
    {
        $this->withDefaultNickname();
    }
}
