<?php

# @autogenerated
declare(strict_types=1);

namespace Civi\Lughauth\Features\Access\SecurityDomain\Infrastructure\Driver;

use Override;
use Slim\Routing\RouteCollectorProxy;
use Civi\Lughauth\Features\Access\SecurityDomain\Infrastructure\Driver\Rest\SecurityDomainAllowController;
use Civi\Lughauth\Features\Access\SecurityDomain\Infrastructure\Driver\Rest\SecurityDomainListController;
use Civi\Lughauth\Features\Access\SecurityDomain\Infrastructure\Driver\Rest\SecurityDomainCreateController;
use Civi\Lughauth\Features\Access\SecurityDomain\Infrastructure\Driver\Rest\SecurityDomainRetrieveController;
use Civi\Lughauth\Features\Access\SecurityDomain\Infrastructure\Driver\Rest\SecurityDomainUpdateController;
use Civi\Lughauth\Features\Access\SecurityDomain\Infrastructure\Driver\Rest\SecurityDomainDeleteController;
use Civi\Lughauth\Features\Access\SecurityDomain\Infrastructure\Driver\Rest\SecurityDomainEnableController;
use Civi\Lughauth\Features\Access\SecurityDomain\Infrastructure\Driver\Rest\SecurityDomainDisableController;
use Civi\Lughauth\Shared\Infrastructure\MicroPlugin;
use Civi\Lughauth\Shared\Event\EventListenersRegistrarInterface;
use Civi\Lughauth\Features\Access\SecurityDomain\Application\Policy\Allow\Create\IsAutenticatedCreateAllow;
use Civi\Lughauth\Features\Access\SecurityDomain\Application\Policy\Allow\Update\IsAutenticatedUpdateAllow;
use Civi\Lughauth\Features\Access\SecurityDomain\Application\Policy\Allow\Retrieve\IsAutenticatedRetrieveAllow;
use Civi\Lughauth\Features\Access\SecurityDomain\Application\Policy\Allow\List\IsAutenticatedListAllow;
use Civi\Lughauth\Features\Access\SecurityDomain\Application\Policy\Allow\Delete\IsAutenticatedDeleteAllow;
use Civi\Lughauth\Features\Access\SecurityDomain\Application\Policy\Allow\Enable\IsAutenticatedEnableAllow;
use Civi\Lughauth\Features\Access\SecurityDomain\Application\Policy\Allow\Disable\IsAutenticatedDisableAllow;
use Civi\Lughauth\Features\Access\SecurityDomain\Application\Usecase\Create\SecurityDomainCreateAllowDecision;
use Civi\Lughauth\Features\Access\SecurityDomain\Application\Usecase\Update\SecurityDomainUpdateAllowDecision;
use Civi\Lughauth\Features\Access\SecurityDomain\Application\Usecase\Retrieve\SecurityDomainRetrieveAllowDecision;
use Civi\Lughauth\Features\Access\SecurityDomain\Application\Usecase\List\SecurityDomainListAllowDecision;
use Civi\Lughauth\Features\Access\SecurityDomain\Application\Usecase\Delete\SecurityDomainDeleteAllowDecision;
use Civi\Lughauth\Features\Access\SecurityDomain\Application\Usecase\Enable\SecurityDomainEnableAllowDecision;
use Civi\Lughauth\Features\Access\SecurityDomain\Application\Usecase\Disable\SecurityDomainDisableAllowDecision;

class SecurityDomainPlugin extends MicroPlugin
{
    #[Override]
    public function registerRoutes(RouteCollectorProxy $app)
    {
        $app->group('/api/access/security-domains', [$this, 'setRoutesForSecurityDomain']);
        $app->group('/api/me/acl/access/security-domains', [$this, 'setRoutesForSecurityDomainAcl']);
    }
    #[Override]
    public function registerEvents(EventListenersRegistrarInterface $bus)
    {
        $bus->registerListener(SecurityDomainCreateAllowDecision::class, IsAutenticatedCreateAllow::class);
        $bus->registerListener(SecurityDomainUpdateAllowDecision::class, IsAutenticatedUpdateAllow::class);
        $bus->registerListener(SecurityDomainRetrieveAllowDecision::class, IsAutenticatedRetrieveAllow::class);
        $bus->registerListener(SecurityDomainListAllowDecision::class, IsAutenticatedListAllow::class);
        $bus->registerListener(SecurityDomainDeleteAllowDecision::class, IsAutenticatedDeleteAllow::class);
        $bus->registerListener(SecurityDomainEnableAllowDecision::class, IsAutenticatedEnableAllow::class);
        $bus->registerListener(SecurityDomainDisableAllowDecision::class, IsAutenticatedDisableAllow::class);
    }
    public function setRoutesForSecurityDomainAcl(RouteCollectorProxy $securityDomainGroup)
    {
        $securityDomainGroup->get('', [SecurityDomainAllowController::class, 'genericAllow']);
        $securityDomainGroup->get('/{uid}', [SecurityDomainAllowController::class, 'contextualAllow']);
    }
    public function setRoutesForSecurityDomain(RouteCollectorProxy $securityDomainGroup)
    {
        $securityDomainGroup->get('', [SecurityDomainListController::class, 'list']);
        $securityDomainGroup->post('', [SecurityDomainCreateController::class, 'create']);
        $securityDomainGroup->get('/{uid}', [SecurityDomainRetrieveController::class, 'retrieve']);
        $securityDomainGroup->put('/{uid}', [SecurityDomainUpdateController::class, 'update']);
        $securityDomainGroup->delete('/{uid}', [SecurityDomainDeleteController::class, 'delete']);
        $securityDomainGroup->delete('', [SecurityDomainDeleteController::class, 'deleteAllForQuery']);
        $securityDomainGroup->get('/~/delete-status/{uid}', [SecurityDomainDeleteController::class, 'checkDeleteAllForQueryStatus']);
        $securityDomainGroup->patch('/~/enable', [SecurityDomainEnableController::class, 'enableAllForQuery']);
        $securityDomainGroup->patch('/{uid}/enable', [SecurityDomainEnableController::class, 'enable']);
        $securityDomainGroup->get('/~/enable-status/{uid}', [SecurityDomainEnableController::class, 'checkEnableAllForQueryStatus']);
        $securityDomainGroup->patch('/~/disable', [SecurityDomainDisableController::class, 'disableAllForQuery']);
        $securityDomainGroup->patch('/{uid}/disable', [SecurityDomainDisableController::class, 'disable']);
        $securityDomainGroup->get('/~/disable-status/{uid}', [SecurityDomainDisableController::class, 'checkDisableAllForQueryStatus']);
    }
}
