<?php

/* @autogenerated */
declare(strict_types=1);

namespace Civi\Lughauth\Features\Access\UserPersonalApiKey\Domain\Formula;

use Civi\Lughauth\Features\Access\UserPersonalApiKey\Domain\UserPersonalApiKey;
use Civi\Lughauth\Features\Access\UserPersonalApiKey\Domain\ValueObject\UserPersonalApiKeyLastUsedAtVO;

class LastUsedAtCalculator
{
    public static function calculateLastUsedAt(?UserPersonalApiKey $original = null): ?UserPersonalApiKeyLastUsedAtVO
    {
        return $original ? $original->lastUsedAt() : UserPersonalApiKeyLastUsedAtVO::from(null);
    }
}
