<?php

# @autogenerated
declare(strict_types=1);

use Civi\Lughauth\Features\Access\UserAccessTemporalCode\Domain\UserAccessTemporalCode;
use Civi\Lughauth\Features\Access\User\Domain\UserRef;
use Civi\Lughauth\Features\Access\UserAccessTemporalCode\Domain\ValueObject\UserAccessTemporalCodeUserVO;
use Civi\Lughauth\Features\Access\UserAccessTemporalCode\Domain\ValueObject\UserAccessTemporalCodeTempSecondFactorSeedVO;
use Civi\Lughauth\Features\Access\UserAccessTemporalCode\Domain\ValueObject\UserAccessTemporalCodeTempSecondFactorSeedExpirationVO;
use Civi\Lughauth\Features\Access\UserAccessTemporalCode\Domain\ValueObject\UserAccessTemporalCodeFailedLoginAttemptsVO;
use Civi\Lughauth\Features\Access\UserAccessTemporalCode\Domain\ValueObject\UserAccessTemporalCodeRecoveryCodeVO;
use Civi\Lughauth\Features\Access\UserAccessTemporalCode\Domain\ValueObject\UserAccessTemporalCodeRecoveryCodeExpirationVO;
use Civi\Lughauth\Features\Access\UserAccessTemporalCode\Domain\ValueObject\UserAccessTemporalCodeVersionVO;
use Civi\Lughauth\Features\Access\UserAccessTemporalCode\Domain\UserAccessTemporalCodeAttributes;
use PHPUnit\Framework\TestCase;

final class UserAccessTemporalCodeAttributesUnitTest extends TestCase
{
    public function test(): void
    {
        $value = new UserAccessTemporalCodeAttributes();
        $userOneValue = $this->getMockBuilder(UserRef::class)->setConstructorArgs(['one'])->getMock();
        $userOtherValue = $this->getMockBuilder(UserRef::class)->setConstructorArgs(['other'])->getMock();
        $copy = $value->user($userOneValue);
        $this->assertSame($value, $copy);
        $this->assertEquals($this->getMockBuilder(UserRef::class)->setConstructorArgs(['one'])->getMock(), $value->getUser());
        $this->assertNotEquals($this->getMockBuilder(UserRef::class)->setConstructorArgs(['other'])->getMock(), $value->getUser());
        $this->assertEquals($this->getMockBuilder(UserRef::class)->setConstructorArgs(['one'])->getMock(), $value->getUserOrDefault(UserAccessTemporalCodeUserVO::from($userOtherValue))->value());
        $this->assertNotEquals($this->getMockBuilder(UserRef::class)->setConstructorArgs(['other'])->getMock(), $value->getUserOrDefault(UserAccessTemporalCodeUserVO::from($userOtherValue))->value());
        $value->unsetUser();
        $this->assertEquals($this->getMockBuilder(UserRef::class)->setConstructorArgs(['other'])->getMock(), $value->getUserOrDefault(UserAccessTemporalCodeUserVO::from($userOtherValue))->value());
        $this->assertNotEquals($this->getMockBuilder(UserRef::class)->setConstructorArgs(['one'])->getMock(), $value->getUserOrDefault(UserAccessTemporalCodeUserVO::from($userOtherValue))->value());
        $tempSecondFactorSeedOneValue = 'cyphered://cypher';
        $tempSecondFactorSeedOtherValue = 'cyphered://ocyphered';
        $copy = $value->tempSecondFactorSeed($tempSecondFactorSeedOneValue);
        $this->assertSame($value, $copy);
        $this->assertEquals('cyphered://cypher', $value->getTempSecondFactorSeed());
        $this->assertNotEquals('cyphered://ocyphered', $value->getTempSecondFactorSeed());
        $this->assertEquals('****er', $value->getTempSecondFactorSeedOrDefault(UserAccessTemporalCodeTempSecondFactorSeedVO::from($tempSecondFactorSeedOtherValue))->value());
        $this->assertNotEquals('****ed', $value->getTempSecondFactorSeedOrDefault(UserAccessTemporalCodeTempSecondFactorSeedVO::from($tempSecondFactorSeedOtherValue))->value());
        $value->unsetTempSecondFactorSeed();
        $this->assertEquals('****ed', $value->getTempSecondFactorSeedOrDefault(UserAccessTemporalCodeTempSecondFactorSeedVO::from($tempSecondFactorSeedOtherValue))->value());
        $this->assertNotEquals('****er', $value->getTempSecondFactorSeedOrDefault(UserAccessTemporalCodeTempSecondFactorSeedVO::from($tempSecondFactorSeedOtherValue))->value());
        $tempSecondFactorSeedExpirationOneValue = (new \DateTimeImmutable('1980-08-20T14:32:45.123Z'));
        $tempSecondFactorSeedExpirationOtherValue = (new \DateTimeImmutable('1981-09-06T14:32:45.123Z'));
        $copy = $value->tempSecondFactorSeedExpiration($tempSecondFactorSeedExpirationOneValue);
        $this->assertSame($value, $copy);
        $this->assertEquals((new \DateTimeImmutable('1980-08-20T14:32:45.123Z')), $value->getTempSecondFactorSeedExpiration());
        $this->assertNotEquals((new \DateTimeImmutable('1981-09-06T14:32:45.123Z')), $value->getTempSecondFactorSeedExpiration());
        $this->assertEquals((new \DateTimeImmutable('1980-08-20T14:32:45.123Z')), $value->getTempSecondFactorSeedExpirationOrDefault(UserAccessTemporalCodeTempSecondFactorSeedExpirationVO::from($tempSecondFactorSeedExpirationOtherValue))->value());
        $this->assertNotEquals((new \DateTimeImmutable('1981-09-06T14:32:45.123Z')), $value->getTempSecondFactorSeedExpirationOrDefault(UserAccessTemporalCodeTempSecondFactorSeedExpirationVO::from($tempSecondFactorSeedExpirationOtherValue))->value());
        $value->unsetTempSecondFactorSeedExpiration();
        $this->assertEquals((new \DateTimeImmutable('1981-09-06T14:32:45.123Z')), $value->getTempSecondFactorSeedExpirationOrDefault(UserAccessTemporalCodeTempSecondFactorSeedExpirationVO::from($tempSecondFactorSeedExpirationOtherValue))->value());
        $this->assertNotEquals((new \DateTimeImmutable('1980-08-20T14:32:45.123Z')), $value->getTempSecondFactorSeedExpirationOrDefault(UserAccessTemporalCodeTempSecondFactorSeedExpirationVO::from($tempSecondFactorSeedExpirationOtherValue))->value());
        $failedLoginAttemptsOneValue = 1;
        $failedLoginAttemptsOtherValue = 2;
        $copy = $value->failedLoginAttempts($failedLoginAttemptsOneValue);
        $this->assertSame($value, $copy);
        $this->assertEquals(1, $value->getFailedLoginAttempts());
        $this->assertNotEquals(2, $value->getFailedLoginAttempts());
        $this->assertEquals(1, $value->getFailedLoginAttemptsOrDefault(UserAccessTemporalCodeFailedLoginAttemptsVO::from($failedLoginAttemptsOtherValue))->value());
        $this->assertNotEquals(2, $value->getFailedLoginAttemptsOrDefault(UserAccessTemporalCodeFailedLoginAttemptsVO::from($failedLoginAttemptsOtherValue))->value());
        $value->unsetFailedLoginAttempts();
        $this->assertEquals(2, $value->getFailedLoginAttemptsOrDefault(UserAccessTemporalCodeFailedLoginAttemptsVO::from($failedLoginAttemptsOtherValue))->value());
        $this->assertNotEquals(1, $value->getFailedLoginAttemptsOrDefault(UserAccessTemporalCodeFailedLoginAttemptsVO::from($failedLoginAttemptsOtherValue))->value());
        $recoveryCodeOneValue = 'one';
        $recoveryCodeOtherValue = 'other';
        $copy = $value->recoveryCode($recoveryCodeOneValue);
        $this->assertSame($value, $copy);
        $this->assertEquals('one', $value->getRecoveryCode());
        $this->assertNotEquals('other', $value->getRecoveryCode());
        $this->assertEquals('one', $value->getRecoveryCodeOrDefault(UserAccessTemporalCodeRecoveryCodeVO::from($recoveryCodeOtherValue))->value());
        $this->assertNotEquals('other', $value->getRecoveryCodeOrDefault(UserAccessTemporalCodeRecoveryCodeVO::from($recoveryCodeOtherValue))->value());
        $value->unsetRecoveryCode();
        $this->assertEquals('other', $value->getRecoveryCodeOrDefault(UserAccessTemporalCodeRecoveryCodeVO::from($recoveryCodeOtherValue))->value());
        $this->assertNotEquals('one', $value->getRecoveryCodeOrDefault(UserAccessTemporalCodeRecoveryCodeVO::from($recoveryCodeOtherValue))->value());
        $recoveryCodeExpirationOneValue = (new \DateTimeImmutable('1980-08-20T14:32:45.123Z'));
        $recoveryCodeExpirationOtherValue = (new \DateTimeImmutable('1981-09-06T14:32:45.123Z'));
        $copy = $value->recoveryCodeExpiration($recoveryCodeExpirationOneValue);
        $this->assertSame($value, $copy);
        $this->assertEquals((new \DateTimeImmutable('1980-08-20T14:32:45.123Z')), $value->getRecoveryCodeExpiration());
        $this->assertNotEquals((new \DateTimeImmutable('1981-09-06T14:32:45.123Z')), $value->getRecoveryCodeExpiration());
        $this->assertEquals((new \DateTimeImmutable('1980-08-20T14:32:45.123Z')), $value->getRecoveryCodeExpirationOrDefault(UserAccessTemporalCodeRecoveryCodeExpirationVO::from($recoveryCodeExpirationOtherValue))->value());
        $this->assertNotEquals((new \DateTimeImmutable('1981-09-06T14:32:45.123Z')), $value->getRecoveryCodeExpirationOrDefault(UserAccessTemporalCodeRecoveryCodeExpirationVO::from($recoveryCodeExpirationOtherValue))->value());
        $value->unsetRecoveryCodeExpiration();
        $this->assertEquals((new \DateTimeImmutable('1981-09-06T14:32:45.123Z')), $value->getRecoveryCodeExpirationOrDefault(UserAccessTemporalCodeRecoveryCodeExpirationVO::from($recoveryCodeExpirationOtherValue))->value());
        $this->assertNotEquals((new \DateTimeImmutable('1980-08-20T14:32:45.123Z')), $value->getRecoveryCodeExpirationOrDefault(UserAccessTemporalCodeRecoveryCodeExpirationVO::from($recoveryCodeExpirationOtherValue))->value());
        $versionOneValue = 1;
        $versionOtherValue = 2;
        $copy = $value->version($versionOneValue);
        $this->assertSame($value, $copy);
        $this->assertEquals(1, $value->getVersion());
        $this->assertNotEquals(2, $value->getVersion());
        $this->assertEquals(1, $value->getVersionOrDefault(UserAccessTemporalCodeVersionVO::from($versionOtherValue))->value());
        $this->assertNotEquals(2, $value->getVersionOrDefault(UserAccessTemporalCodeVersionVO::from($versionOtherValue))->value());
        $value->unsetVersion();
        $this->assertEquals(2, $value->getVersionOrDefault(UserAccessTemporalCodeVersionVO::from($versionOtherValue))->value());
        $this->assertNotEquals(1, $value->getVersionOrDefault(UserAccessTemporalCodeVersionVO::from($versionOtherValue))->value());
        $this->assertSame($value, $copy);
    }
}
