<?php

/* @autogenerated */
declare(strict_types=1);

use PHPUnit\Framework\TestCase;
use Civi\Lughauth\Shared\Exception\ConstraintException;
use Civi\Lughauth\Shared\Value\Validation\ConstraintFailList;
use Civi\Lughauth\Features\Access\TenantConfig\Domain\ValueObject\TenantConfigMagicLinkEnabledVO;

final class TenantConfigMagicLinkEnabledVOUnitTest extends TestCase
{
    public function test_asignation_keep_value(): void
    {
        $value = true;
        $ref = TenantConfigMagicLinkEnabledVO::from($value);
        $this->assertEquals(true, $ref->value());
        $other = TenantConfigMagicLinkEnabledVO::tryFrom($ref, new ConstraintFailList());
        $this->assertSame($other, $ref);
        $more = TenantConfigMagicLinkEnabledVO::from($ref);
        $this->assertSame($more, $ref);
    }
    public function test_asignation_invalid_type(): void
    {
        $errors = new ConstraintFailList();
        $other = TenantConfigMagicLinkEnabledVO::tryFrom('1', $errors);
        $this->assertNull($other);
        $this->assertTrue($errors->hasErrors());
    }
    public function test_optimist_asignation_invalid_type(): void
    {
        $this->expectException(ConstraintException::class);
        $method = new ReflectionMethod(TenantConfigMagicLinkEnabledVO::class, 'fromUnsafe');
        $method->invoke(null, [11, "bad"]);
    }
    public function test_equals(): void
    {
        $one = TenantConfigMagicLinkEnabledVO::from(true);
        $same = TenantConfigMagicLinkEnabledVO::from(true);
        $other = TenantConfigMagicLinkEnabledVO::from(false);
        $withEmpty = $one->equals(null);
        $withSame = $one->equals($same);
        $withOther = $one->equals($other);

        $this->assertFalse($withEmpty);
        $this->assertTrue($withSame);
        $this->assertFalse($withOther);
    }
    public function test_empty(): void
    {
        $ref = TenantConfigMagicLinkEnabledVO::empty();
        $this->assertNull($ref->value());
    }
    public function test_try_from_empty(): void
    {
        $ref = TenantConfigMagicLinkEnabledVO::tryFrom(null, new ConstraintFailList());
        $this->assertNull($ref->value());
    }
}
