<?php

# @autogenerated
declare(strict_types=1);

namespace Civi\Lughauth\Features\Access\RelyingParty\Domain\ValueObject\Holder;

use Civi\Lughauth\Shared\Value\Validation\ConstraintFailList;
use Civi\Lughauth\Features\Access\RelyingParty\Domain\ValueObject\RelyingPartyEnabledVO;

trait RelyingPartyEnabledAttributeHolder
{
    protected RelyingPartyEnabledVO|bool|null $enabled = null;
    protected bool $enabledAssigned = false;

    public function getEnabledOrDefault(?RelyingPartyEnabledVO $enabled): ?RelyingPartyEnabledVO
    {
        return $this->enabledAssigned ? ($this->enabled !== null ? RelyingPartyEnabledVO::from($this->enabled) : null) : $enabled;
    }
    public function enabled(RelyingPartyEnabledVO|bool|null $enabled): static
    {
        $this->enabled = $enabled;
        $this->enabledAssigned = true;
        return $this;
    }
    public function getEnabled(): ?bool
    {
        return is_a($this->enabled, RelyingPartyEnabledVO::class) ? $this->enabled->value() : $this->enabled;
    }
    public function unsetEnabled(): static
    {
        $this->enabled = null;
        $this->enabledAssigned = false;
        return $this;
    }
    protected function withDefaultEnabled(): void
    {
        if ($this->enabled === null) {
            $this->enabled = false;
        }
    }
    protected function withAssertedEnabledRules(self $value, ConstraintFailList $errorsList): void
    {
        if ($value->enabledAssigned = $this->enabledAssigned) {
            $value->enabled = RelyingPartyEnabledVO::tryFrom($this->enabled, $errorsList);
        }
    }
}
