<?php

# @autogenerated
declare(strict_types=1);

use Civi\Lughauth\Features\Access\UserAccessTemporalCode\Domain\ValueObject\Accessor\UserAccessTemporalCodeRegisterCodeExpirationAccessor;
use PHPUnit\Framework\TestCase;

/**
 * Unit tests for the UserAccessTemporalCodeRegisterCodeExpirationAccessor trait.
 *
 * Covers null default, string/VO assignment via withRegisterCodeExpiration,
 * getRegisterCodeExpiration/registerCodeExpiration accessors, and isRegisterCodeExpirationChanged with/without original.
 */
class UserAccessTemporalCodeRegisterCodeExpirationAccessorUnitTest extends TestCase
{
    /**
     * Asserts that withRegisterCodeExpiration creates a new instance with the RegisterCodeExpiration set
     * from a string value, and getRegisterCodeExpiration returns the primitive string.
     */
    public function testWithRegisterCodeExpirationFromString(): void
    {
        // Arrange
        $holder = new ImplWithUserAccessTemporalCodeRegisterCodeExpirationAccessorUnitTest();

        // Act
        $result = $holder->withRegisterCodeExpiration((new \DateTimeImmutable('1980-08-20T14:32:45.123Z')));

        // Assert
        $this->assertNotSame($holder, $result);
        $this->assertEquals((new \DateTimeImmutable('1980-08-20T14:32:45.123Z')), $result->getRegisterCodeExpiration());
    }
    /**
     * Asserts that withregisterCodeExpiration has access to the value object
     * from a string value, and getRegisterCodeExpiration returns the primitive string.
     */
    public function testWithRegisterCodeExpirationFromValueObject(): void
    {
        // Arrange
        $holder = new ImplWithUserAccessTemporalCodeRegisterCodeExpirationAccessorUnitTest();

        // Act
        $result = $holder->withRegisterCodeExpiration((new \DateTimeImmutable('1980-08-20T14:32:45.123Z')));

        // Assert
        $this->assertNotSame($holder, $result);
        $this->assertEquals((new \DateTimeImmutable('1980-08-20T14:32:45.123Z')), $result->registerCodeExpiration()->value());
    }
    public function testChangedRegisterCodeExpiration(): void
    {
        // Arrange
        $holder = new ImplWithUserAccessTemporalCodeRegisterCodeExpirationAccessorUnitTest();
        $original = $holder->withRegisterCodeExpiration((new \DateTimeImmutable('1980-08-20T14:32:45.123Z')));
        $same = $holder->withRegisterCodeExpiration((new \DateTimeImmutable('1980-08-20T14:32:45.123Z')));
        $modified = $holder->withRegisterCodeExpiration((new \DateTimeImmutable('1981-09-06T14:32:45.123Z')));

        // Act
        $unchanged = $holder->isRegisterCodeExpirationChanged();
        $withSame = $original->isRegisterCodeExpirationChanged($same);
        $withDiferent = $original->isRegisterCodeExpirationChanged($modified);

        // Assert
        $this->assertFalse($unchanged);
        $this->assertFalse($withSame);
        $this->assertTrue($withDiferent);
    }
}
class ImplWithUserAccessTemporalCodeRegisterCodeExpirationAccessorUnitTest
{
    use UserAccessTemporalCodeRegisterCodeExpirationAccessor;
}
