<?php

/* @autogenerated */
declare(strict_types=1);

namespace Civi\Lughauth\Shared\Value\Validation\Rule;

use Override;
use Civi\Lughauth\Shared\Value\Validation\Rule;
use Civi\Lughauth\Shared\Value\Validation\RuleFail;
use Respect\Validation\Validator;

/**
 * Between class validates that a given value is between two specified values, inclusive.
 * @api
 */
class Between implements Rule
{
    /**
     * Create a rule with min and max range
     *
     * @param mixed $min The minimum value.
     * @param mixed $max The maximum value.
     */
    public function __construct(
        private readonly int $min,
        private readonly int $max
    ) {
    }

    /**
     * Checks whether the given value is between the specified min and max values.
     *
     * @param mixed $value The value to validate.
     * @return RuleFail|null Returns null if validation passes, otherwise a RuleFail object.
     */
    #[Override]
    public function check($value): ?RuleFail
    {
        return Validator::between($this->min, $this->max)->isValid($value) ? null : new RuleFail(
            'rule_between',
            $value,
            ['min' => $this->min, 'max' => $this->max]
        );
    }
}
