<?php

/* @autogenerated */
declare(strict_types=1);

namespace Civi\Lughauth\Shared\Value\Validation\Rule;

use Override;
use Civi\Lughauth\Shared\Value\Validation\Rule;
use Civi\Lughauth\Shared\Value\Validation\RuleFail;
use Respect\Validation\Validator;

/**
 * In class validates that the given value is present in a specified list of allowed values.
 * @api
 */
class In implements Rule
{
    /**
     * Create a rule with the list of valid values.
     *
     * @param array $haystack The array of allowed values.
     */
    public function __construct(
        private readonly array $haystack
    ) {
    }

    /**
     * Checks whether the given value is present in the allowed set of values.
     *
     * @param mixed $value The value to validate.
     * @return RuleFail|null Returns null if validation passes, otherwise a RuleFail object.
     */
    #[Override]
    public function check($value): ?RuleFail
    {
        return Validator::in($this->haystack)->isValid($value) ? null : new RuleFail('rule_in', $value, ['allowed' => $this->haystack]);
    }
}
