<?php

/* @autogenerated */
declare(strict_types=1);

namespace Civi\Lughauth\Shared\Value\Validation\Rule;

use Override;
use Civi\Lughauth\Shared\Value\Validation\Rule;
use Civi\Lughauth\Shared\Value\Validation\RuleFail;
use Respect\Validation\Validator;

/**
 * IntVal class validates that the given value is a valid integer.
 * @api
 */
class IntVal implements Rule
{
    /**
     * Checks whether the given value is a valid integer.
     *
     * @param mixed $value The value to validate.
     * @return RuleFail|null Returns null if validation passes, otherwise a RuleFail object.
     */
    #[Override]
    public function check($value): ?RuleFail
    {
        /** @psalm-suppress UndefinedInterfaceMethod */
        return Validator::intVal()->isValid($value) ? null : new RuleFail('rule_int_value', $value, []);
    }
}
