<?php

/* @autogenerated */
declare(strict_types=1);

namespace Civi\Lughauth\Shared\Value\Validation\Rule;

use Override;
use Civi\Lughauth\Shared\Value\Validation\Rule;
use Civi\Lughauth\Shared\Value\Validation\RuleFail;
use Respect\Validation\Validator;

/**
 * Isbn class validates that the given value is a valid ISBN (International Standard Book Number).
 * It checks both ISBN-10 and ISBN-13 formats.
 * @api
 */
class Isbn implements Rule
{
    /**
     * Checks whether the given value is a valid ISBN (either ISBN-10 or ISBN-13).
     *
     * @param mixed $value The value to validate.
     * @return RuleFail|null Returns null if validation passes, otherwise a RuleFail object.
     */
    #[Override]
    public function check($value): ?RuleFail
    {
        /** @psalm-suppress UndefinedInterfaceMethod */
        return Validator::isbn()->isValid($value) ? null : new RuleFail('rule_isbn', $value, []);
    }
}
