<?php

/* @autogenerated */
declare(strict_types=1);

namespace Civi\Lughauth\Shared\Value\Validation\Rule;

use Override;
use Civi\Lughauth\Shared\Value\Validation\Rule;
use Civi\Lughauth\Shared\Value\Validation\RuleFail;
use Respect\Validation\Validator;

/**
 * Max class validates that the given value is less than or equal to a specified maximum value.
 * @api
 */
class Max implements Rule
{
    /**
     * Create a rule to allow at max vallue
     *
     * @param mixed $max The maximum value.
     */
    public function __construct(
        private readonly int $max
    ) {
    }

    /**
     * Checks whether the given value is less than or equal to the maximum value.
     *
     * @param mixed $value The value to validate.
     * @return RuleFail|null Returns null if validation passes, otherwise a RuleFail object.
     */
    #[Override]
    public function check($value): ?RuleFail
    {
        return Validator::max($this->max)->isValid($value) ? null : new RuleFail('rule_max', $value, ['max' => $this->max]);
    }
}
