<?php

/* @autogenerated */
declare(strict_types=1);

namespace Civi\Lughauth\Features\Access\User\Domain;

use Civi\Lughauth\Features\Access\User\Domain\ValueObject\Holder\UserUidAttributeHolder;
use Civi\Lughauth\Features\Access\User\Domain\ValueObject\Holder\UserTenantAttributeHolder;
use Civi\Lughauth\Features\Access\User\Domain\ValueObject\Holder\UserNameAttributeHolder;
use Civi\Lughauth\Features\Access\User\Domain\ValueObject\Holder\UserPasswordAttributeHolder;
use Civi\Lughauth\Features\Access\User\Domain\ValueObject\Holder\UserEmailAttributeHolder;
use Civi\Lughauth\Features\Access\User\Domain\ValueObject\Holder\UserWellcomeAtAttributeHolder;
use Civi\Lughauth\Features\Access\User\Domain\ValueObject\Holder\UserEmailVerifiedAttributeHolder;
use Civi\Lughauth\Features\Access\User\Domain\ValueObject\Holder\UserEnabledAttributeHolder;
use Civi\Lughauth\Features\Access\User\Domain\ValueObject\Holder\UserApproveAttributeHolder;
use Civi\Lughauth\Features\Access\User\Domain\ValueObject\Holder\UserTemporalPasswordAttributeHolder;
use Civi\Lughauth\Features\Access\User\Domain\ValueObject\Holder\UserUseSecondFactorsAttributeHolder;
use Civi\Lughauth\Features\Access\User\Domain\ValueObject\Holder\UserSecondFactorSeedAttributeHolder;
use Civi\Lughauth\Features\Access\User\Domain\ValueObject\Holder\UserBlockedUntilAttributeHolder;
use Civi\Lughauth\Features\Access\User\Domain\ValueObject\Holder\UserProviderAttributeHolder;
use Civi\Lughauth\Features\Access\User\Domain\ValueObject\Holder\UserVersionAttributeHolder;
use Civi\Lughauth\Shared\Value\Validation\ConstraintFailList;

class UserAttributes
{
    use UserUidAttributeHolder;
    use UserTenantAttributeHolder;
    use UserNameAttributeHolder;
    use UserPasswordAttributeHolder;
    use UserEmailAttributeHolder;
    use UserWellcomeAtAttributeHolder;
    use UserEmailVerifiedAttributeHolder;
    use UserEnabledAttributeHolder;
    use UserApproveAttributeHolder;
    use UserTemporalPasswordAttributeHolder;
    use UserUseSecondFactorsAttributeHolder;
    use UserSecondFactorSeedAttributeHolder;
    use UserBlockedUntilAttributeHolder;
    use UserProviderAttributeHolder;
    use UserVersionAttributeHolder;

    private const array UNSETS = [
      'uid' => 'unsetUid',
      'tenant' => 'unsetTenant',
      'name' => 'unsetName',
      'password' => 'unsetPassword',
      'email' => 'unsetEmail',
      'wellcomeAt' => 'unsetWellcomeAt',
      'emailVerified' => 'unsetEmailVerified',
      'enabled' => 'unsetEnabled',
      'approve' => 'unsetApprove',
      'temporalPassword' => 'unsetTemporalPassword',
      'useSecondFactors' => 'unsetUseSecondFactors',
      'secondFactorSeed' => 'unsetSecondFactorSeed',
      'blockedUntil' => 'unsetBlockedUntil',
      'provider' => 'unsetProvider',
      'version' => 'unsetVersion',
    ];

    public function createNewInstance(): User
    {
        $errors = new ConstraintFailList();
        $uid = $this->uidTryBuildInitial($errors);
        $tenant = $this->tenantTryBuildInitial($errors);
        $name = $this->nameTryBuildInitial($errors);
        $password = $this->passwordTryBuildInitial($errors);
        $email = $this->emailTryBuildInitial($errors);
        $wellcomeAt = $this->wellcomeAtTryBuildInitial($errors);
        $emailVerified = $this->emailVerifiedTryBuildInitial($errors);
        $enabled = $this->enabledTryBuildInitial($errors);
        $approve = $this->approveTryBuildInitial($errors);
        $temporalPassword = $this->temporalPasswordTryBuildInitial($errors);
        $useSecondFactors = $this->useSecondFactorsTryBuildInitial($errors);
        $secondFactorSeed = $this->secondFactorSeedTryBuildInitial($errors);
        $blockedUntil = $this->blockedUntilTryBuildInitial($errors);
        $provider = $this->providerTryBuildInitial($errors);
        $version = $this->versionTryBuildInitial($errors);
        if ($errors->hasErrors()) {
            throw $errors->asConstraintException();
        }
        \assert($uid !== null);
        \assert($tenant !== null);
        \assert($name !== null);
        \assert($password !== null);
        return new User(
            uid: $uid,
            tenant: $tenant,
            name: $name,
            password: $password,
            email: $email,
            wellcomeAt: $wellcomeAt,
            emailVerified: $emailVerified,
            enabled: $enabled,
            approve: $approve,
            temporalPassword: $temporalPassword,
            useSecondFactors: $useSecondFactors,
            secondFactorSeed: $secondFactorSeed,
            blockedUntil: $blockedUntil,
            provider: $provider,
            version: $version,
        );
    }
    public function withAssertedRules(): UserAttributes
    {
        $value = new UserAttributes();
        $errorsList = new ConstraintFailList();
        $this->withAssertedUidRules($value, $errorsList);
        $this->withAssertedTenantRules($value, $errorsList);
        $this->withAssertedNameRules($value, $errorsList);
        $this->withAssertedPasswordRules($value, $errorsList);
        $this->withAssertedEmailRules($value, $errorsList);
        $this->withAssertedWellcomeAtRules($value, $errorsList);
        $this->withAssertedEmailVerifiedRules($value, $errorsList);
        $this->withAssertedEnabledRules($value, $errorsList);
        $this->withAssertedApproveRules($value, $errorsList);
        $this->withAssertedTemporalPasswordRules($value, $errorsList);
        $this->withAssertedUseSecondFactorsRules($value, $errorsList);
        $this->withAssertedSecondFactorSeedRules($value, $errorsList);
        $this->withAssertedBlockedUntilRules($value, $errorsList);
        $this->withAssertedProviderRules($value, $errorsList);
        $this->withAssertedVersionRules($value, $errorsList);
        if ($errorsList->hasErrors()) {
            throw $errorsList->asConstraintException();
        }
        return $value;
    }
    public function unset(string $field): void
    {
        if (isset(self::UNSETS[$field])) {
            call_user_func([$this, self::UNSETS[$field]]);
        }
    }
    public function withDefaults(): UserAttributes
    {
        $this->withDefaultUid();
        $this->withDefaultTenant();
        $this->withDefaultName();
        $this->withDefaultPassword();
        $this->withDefaultEmail();
        $this->withDefaultWellcomeAt();
        $this->withDefaultEmailVerified();
        $this->withDefaultEnabled();
        $this->withDefaultApprove();
        $this->withDefaultTemporalPassword();
        $this->withDefaultUseSecondFactors();
        $this->withDefaultSecondFactorSeed();
        $this->withDefaultBlockedUntil();
        $this->withDefaultProvider();
        $this->withDefaultVersion();
        return $this;
    }
}
