<?php

/* @autogenerated */
declare(strict_types=1);

use Civi\Lughauth\Features\Access\TrustedClient\Domain\ValueObject\Holder\TrustedClientRegistrationAccessAttributeHolder;
use Civi\Lughauth\Shared\Value\Validation\ConstraintFailList;
use PHPUnit\Framework\TestCase;

/**
 * Unit tests for the TrustedClientRegistrationAccessAttributeHolder trait.
 *
 * Covers assignment, retrieval, default fallback,
 * transfer between holders, validation rules, and unset operations.
 */
class TrustedClientRegistrationAccessAttributeHolderUnitTest extends TestCase
{
    /**
     * Asserts that the code attribute is not assigned by default
     * and that getRegistrationAccess returns null on a freshly created holder.
     */
    public function testRegistrationAccessNotAssignedByDefault(): void
    {
        // Arrange
        $holder = new ImplWithTrustedClientRegistrationAccessAttributeHolderUnitTest();

        // Assert
        $this->assertFalse($holder->isRegistrationAccessAssigned());
        $this->assertNull($holder->getRegistrationAccess());
    }
}
class ImplWithTrustedClientRegistrationAccessAttributeHolderUnitTest
{
    use TrustedClientRegistrationAccessAttributeHolder;
    public function assertRules(ConstraintFailList $errorsList): self
    {
        $result = new self();
        $this->withAssertedRegistrationAccessRules($result, $errorsList);
        return $result;
    }

    public function applyDefaults(): void
    {
        $this->withDefaultRegistrationAccess();
    }
}
