<?php

/* @autogenerated */
declare(strict_types=1);

namespace Civi\Lughauth\Features\Access\TenantConfig\Domain\ValueObject\Holder;

use Civi\Lughauth\Shared\Value\Validation\ConstraintFailList;
use Civi\Lughauth\Features\Access\TenantConfig\Domain\ValueObject\TenantConfigMagicLinkExpiryMinutesVO;

trait TenantConfigMagicLinkExpiryMinutesAttributeHolder
{
    protected TenantConfigMagicLinkExpiryMinutesVO|int|null $magicLinkExpiryMinutes = null;
    protected bool $magicLinkExpiryMinutesAssigned = false;

    public function getMagicLinkExpiryMinutesOrCurrent(TenantConfigMagicLinkExpiryMinutesVO $magicLinkExpiryMinutes): TenantConfigMagicLinkExpiryMinutesVO
    {
        if ($this->magicLinkExpiryMinutesAssigned) {
            \assert(null !== $this->magicLinkExpiryMinutes);
            return TenantConfigMagicLinkExpiryMinutesVO::from($this->magicLinkExpiryMinutes);
        } else {
            return $magicLinkExpiryMinutes;
        }
    }
    public function magicLinkExpiryMinutesTryBuildInitial(ConstraintFailList $error): ?TenantConfigMagicLinkExpiryMinutesVO
    {
        return  TenantConfigMagicLinkExpiryMinutesVO::tryFrom($this->magicLinkExpiryMinutesAssigned ? $this->magicLinkExpiryMinutes : 30, $error);
    }
    public function magicLinkExpiryMinutes(TenantConfigMagicLinkExpiryMinutesVO|int $magicLinkExpiryMinutes): static
    {
        $this->magicLinkExpiryMinutes = $magicLinkExpiryMinutes;
        $this->magicLinkExpiryMinutesAssigned = true;
        return $this;
    }
    public function getMagicLinkExpiryMinutes(): ?int
    {
        return $this->magicLinkExpiryMinutes instanceof TenantConfigMagicLinkExpiryMinutesVO ? $this->magicLinkExpiryMinutes->value() : $this->magicLinkExpiryMinutes;
    }
    public function isMagicLinkExpiryMinutesAssigned(): bool
    {
        return $this->magicLinkExpiryMinutesAssigned;
    }
    public function writeMagicLinkExpiryMinutesTo(mixed $att): void
    {
        if ($this->magicLinkExpiryMinutesAssigned) {
            \assert(null !== $this->magicLinkExpiryMinutes);
            $att->magicLinkExpiryMinutes($this->magicLinkExpiryMinutes);
        }
    }
    public function readMagicLinkExpiryMinutesFrom(mixed $att): void
    {
        if ($att->isMagicLinkExpiryMinutesAssigned()) {
            $magicLinkExpiryMinutes = $att->getMagicLinkExpiryMinutes();
            \assert(null !== $magicLinkExpiryMinutes);
            $this->magicLinkExpiryMinutes($magicLinkExpiryMinutes);
        }
    }
    public function unsetMagicLinkExpiryMinutes(): static
    {
        $this->magicLinkExpiryMinutesAssigned = false;
        return $this;
    }
    protected function withDefaultMagicLinkExpiryMinutes(): void
    {
        if ($this->magicLinkExpiryMinutes === null) {
            $this->magicLinkExpiryMinutes = 30;
        }
    }
    protected function withAssertedMagicLinkExpiryMinutesRules(self $value, ConstraintFailList $errorsList): void
    {
        if ($value->magicLinkExpiryMinutesAssigned = $this->magicLinkExpiryMinutesAssigned) {
            $value->magicLinkExpiryMinutes = TenantConfigMagicLinkExpiryMinutesVO::tryFrom($this->magicLinkExpiryMinutes, $errorsList);
        }
    }
}
