<?php

# @autogenerated
declare(strict_types=1);

namespace Civi\Lughauth\Features\Access\Role\Domain\ValueObject\Holder;

use Civi\Lughauth\Shared\Value\Validation\ConstraintFailList;
use Civi\Lughauth\Features\Access\Role\Domain\ValueObject\RoleDomainsUidVO;

trait RoleDomainsUidAttributeHolder
{
    protected RoleDomainsUidVO|string|null $uid = null;
    protected bool $uidAssigned = false;

    public function getUidOrDefault(?RoleDomainsUidVO $uid): RoleDomainsUidVO|string|null
    {
        return $this->uidAssigned ? ($this->uid !== null ? RoleDomainsUidVO::from($this->uid) : null) : $uid;
    }
    public function uid(RoleDomainsUidVO|string|null $uid): static
    {
        $this->uid = $uid;
        $this->uidAssigned = true;
        return $this;
    }
    public function getUid(): ?string
    {
        return is_a($this->uid, RoleDomainsUidVO::class) ? $this->uid->value() : $this->uid;
    }
    public function unsetUid(): static
    {
        $this->uid = null;
        $this->uidAssigned = false;
        return $this;
    }
    protected function withDefaultUid(): void
    {
    }
    protected function withAssertedUidRules(self $value, ConstraintFailList $errorsList): void
    {
        if ($value->uidAssigned = $this->uidAssigned) {
            $value->uid = RoleDomainsUidVO::tryFrom($this->uid, $errorsList);
        }
    }
}
