<?php

# @autogenerated
declare(strict_types=1);

namespace Civi\Lughauth\Features\Access\User\Domain\Formula;

use Civi\Lughauth\Features\Access\User\Domain\User;
use Civi\Lughauth\Features\Access\User\Domain\ValueObject\UserApproveVO;
use Civi\Lughauth\Features\Access\User\Domain\UserApproveOptions;

class ApproveCalculator
{
    public static function calculateApprove(?User $original = null): ?UserApproveVO
    {
        return $original ? $original->approve() : UserApproveVO::from(UserApproveOptions::ACCEPTED);
    }
}
