<?php

# @autogenerated
declare(strict_types=1);

namespace Civi\Lughauth\Features\Access\User\Domain\Formula;

use Civi\Lughauth\Features\Access\User\Domain\User;
use Civi\Lughauth\Features\Access\User\Domain\ValueObject\UserApprovedVO;

class ApprovedCalculator
{
    public static function calculateApproved(?User $original = null): ?UserApprovedVO
    {
        return $original ? $original->approved() : UserApprovedVO::from(true);
    }
}
