<?php

/* @autogenerated */
declare(strict_types=1);

namespace Civi\Lughauth\Features\Access\ConsentPurpose\Domain\ValueObject\Accessor;

use Civi\Lughauth\Features\Access\ConsentPurpose\Domain\ValueObject\ConsentPurposeRequiredVO;

trait ConsentPurposeRequiredAccessor
{
    private ConsentPurposeRequiredVO $_required;
    public function isRequired(): bool
    {
        return $this->_required->value();
    }
    public function required(): ConsentPurposeRequiredVO
    {
        return $this->_required;
    }
    public function isRequiredChanged(?self $original = null): bool
    {
        return !$this->_required->equals($original?->_required);
    }
    public function withRequired(ConsentPurposeRequiredVO|bool $required): self
    {
        $copy = clone $this;
        $copy->_required = ConsentPurposeRequiredVO::from($required);
        return $copy;
    }
}
