<?php

# @autogenerated
declare(strict_types=1);

namespace Civi\Lughauth\Features\Access\User\Domain\Event;

use Civi\Lughauth\Features\Access\User\Domain\User;

class UserCreateEvent extends UserEvent
{
    public function __construct(
        User $payload
    ) {
        parent::__construct($payload);
    }
}
