<?php

# @autogenerated
declare(strict_types=1);

use Civi\Lughauth\Features\Document\TemplateAsset\Domain\ValueObject\TemplateAssetEnabledVO;
use Civi\Lughauth\Features\Document\TemplateAsset\Domain\ValueObject\Holder\TemplateAssetEnabledAttributeHolder;
use Civi\Lughauth\Shared\Value\Validation\ConstraintFailList;
use PHPUnit\Framework\TestCase;

/**
 * Unit tests for the TemplateAssetEnabledAttributeHolder trait.
 *
 * Covers assignment, retrieval, default fallback,
 * transfer between holders, validation rules, and unset operations.
 */
class TemplateAssetEnabledAttributeHolderUnitTest extends TestCase
{
        /**
         * Asserts that the code attribute is not assigned by default
         * and that isEnabled returns null on a freshly created holder.
         */
        public function testEnabledNotAssignedByDefault(): void
        {
            // Arrange
            $holder = new ImplWithTemplateAssetEnabledAttributeHolderUnitTest();

            // Assert
            $this->assertFalse($holder->isEnabledAssigned());
            $this->assertNull($holder->isEnabled());
        }
}
class ImplWithTemplateAssetEnabledAttributeHolderUnitTest
{
  use TemplateAssetEnabledAttributeHolder;
    public function assertRules(ConstraintFailList $errorsList): self
    {
        $result = new self();
        $this->withAssertedEnabledRules($result, $errorsList);
        return $result;
    }

    public function applyDefaults(): void
    {
        $this->withDefaultEnabled();
    }}
