<?php

/* @autogenerated */
declare(strict_types=1);

namespace Civi\Lughauth\Features\Document\ThemeVersion\Domain\ValueObject\Accessor;

use Civi\Lughauth\Features\Document\ThemeVersion\Domain\ValueObject\ThemeVersionVersionVO;

trait ThemeVersionVersionAccessor
{
    private ?ThemeVersionVersionVO $_version = null;
    public function getVersion(): ?int
    {
        return $this->_version?->value();
    }
    public function version(): ?ThemeVersionVersionVO
    {
        return $this->_version;
    }
    public function isVersionChanged(?self $original = null): bool
    {
        return null !== $this->_version && !$this->_version->equals($original?->_version);
    }
    public function withVersion(ThemeVersionVersionVO|int|null $version): self
    {
        $copy = clone $this;
        $copy->_version = ThemeVersionVersionVO::from($version);
        return $copy;
    }
}
