<?php

/* @autogenerated */
declare(strict_types=1);

namespace Civi\Lughauth\Features\Access\PlatformIdentity\Domain\ValueObject\Holder;

use Civi\Lughauth\Shared\Value\Validation\ConstraintFailList;
use Civi\Lughauth\Features\Access\PlatformIdentity\Domain\ValueObject\PlatformIdentityTrustedClientVO;
use Civi\Lughauth\Features\Access\TrustedClient\Domain\TrustedClientRef;

trait PlatformIdentityTrustedClientAttributeHolder
{
    protected PlatformIdentityTrustedClientVO|TrustedClientRef|null $trustedClient = null;
    protected bool $trustedClientAssigned = false;

    public function getTrustedClientOrDefault(?PlatformIdentityTrustedClientVO $trustedClient): ?PlatformIdentityTrustedClientVO
    {
        return $this->trustedClientAssigned ? ($this->trustedClient !== null ? PlatformIdentityTrustedClientVO::from($this->trustedClient) : null) : $trustedClient;
    }
    public function trustedClient(PlatformIdentityTrustedClientVO|TrustedClientRef|null $trustedClient): static
    {
        $this->trustedClient = $trustedClient;
        $this->trustedClientAssigned = true;
        return $this;
    }
    public function getTrustedClient(): ?TrustedClientRef
    {
        return $this->trustedClient instanceof PlatformIdentityTrustedClientVO ? $this->trustedClient->value() : $this->trustedClient;
    }
    public function isTrustedClientAssigned(): bool
    {
        return $this->trustedClientAssigned;
    }
    public function writeTrustedClientTo(mixed $att): void
    {
        if ($this->trustedClientAssigned) {
            $att->trustedClient($this->trustedClient);
        }
    }
    public function readTrustedClientFrom(mixed $att): void
    {
        if ($att->isTrustedClientAssigned()) {
            $trustedClient = $att->getTrustedClient();
            $this->trustedClient($trustedClient);
        }
    }
    public function unsetTrustedClient(): static
    {
        $this->trustedClientAssigned = false;
        return $this;
    }
    protected function withDefaultTrustedClient(): void
    {
    }
    protected function withAssertedTrustedClientRules(self $value, ConstraintFailList $errorsList): void
    {
        if ($value->trustedClientAssigned = $this->trustedClientAssigned) {
            $value->trustedClient = PlatformIdentityTrustedClientVO::tryFrom($this->trustedClient, $errorsList);
        }
    }
}
