<?php

/* @autogenerated */
declare(strict_types=1);

use Civi\Lughauth\Features\Access\UserAccessTemporalCode\Domain\ValueObject\Holder\UserAccessTemporalCodeRecoveryCodeAttributeHolder;
use Civi\Lughauth\Shared\Value\Validation\ConstraintFailList;
use PHPUnit\Framework\TestCase;

/**
 * Unit tests for the UserAccessTemporalCodeRecoveryCodeAttributeHolder trait.
 *
 * Covers assignment, retrieval, default fallback,
 * transfer between holders, validation rules, and unset operations.
 */
class UserAccessTemporalCodeRecoveryCodeAttributeHolderUnitTest extends TestCase
{
    /**
     * Asserts that the code attribute is not assigned by default
     * and that getRecoveryCode returns null on a freshly created holder.
     */
    public function testRecoveryCodeNotAssignedByDefault(): void
    {
        // Arrange
        $holder = new ImplWithUserAccessTemporalCodeRecoveryCodeAttributeHolderUnitTest();

        // Assert
        $this->assertFalse($holder->isRecoveryCodeAssigned());
        $this->assertNull($holder->getRecoveryCode());
    }
}
class ImplWithUserAccessTemporalCodeRecoveryCodeAttributeHolderUnitTest
{
    use UserAccessTemporalCodeRecoveryCodeAttributeHolder;
    public function assertRules(ConstraintFailList $errorsList): self
    {
        $result = new self();
        $this->withAssertedRecoveryCodeRules($result, $errorsList);
        return $result;
    }

    public function applyDefaults(): void
    {
        $this->withDefaultRecoveryCode();
    }
}
