<?php

/* @autogenerated */
declare(strict_types=1);

namespace Civi\Lughauth\Features\Notification\Message\Domain\ValueObject\Accessor;

use Civi\Lughauth\Features\Notification\Message\Domain\ValueObject\MessageLockAtVO;

trait MessageLockAtAccessor
{
    private ?MessageLockAtVO $_lockAt = null;
    public function getLockAt(): ?\DateTimeImmutable
    {
        return $this->_lockAt?->value();
    }
    public function lockAt(): ?MessageLockAtVO
    {
        return $this->_lockAt;
    }
    public function isLockAtChanged(?self $original = null): bool
    {
        return null !== $this->_lockAt && !$this->_lockAt->equals($original?->_lockAt);
    }
    public function withLockAt(MessageLockAtVO|\DateTimeImmutable|null $lockAt): self
    {
        $copy = clone $this;
        $copy->_lockAt = MessageLockAtVO::from($lockAt);
        return $copy;
    }
}
