<?php

/* @autogenerated */
declare(strict_types=1);

namespace Civi\Lughauth\Features\Access\UserPersonalApiKey\Infrastructure\Driver\Rest;

use Psr\Http\Message\ResponseInterface;
use Psr\Http\Message\ServerRequestInterface;
use OpenApi\Attributes as OA;
use Throwable;
use Civi\Lughauth\Features\Access\UserPersonalApiKey\Domain\UserPersonalApiKeyRef;
use Civi\Lughauth\Features\Access\UserPersonalApiKey\Application\Usecase\Create\UserPersonalApiKeyCreateUsecase;
use Civi\Lughauth\Features\Access\UserPersonalApiKey\Application\Usecase\List\UserPersonalApiKeyListUsecase;
use Civi\Lughauth\Features\Access\UserPersonalApiKey\Application\Usecase\Update\UserPersonalApiKeyUpdateUsecase;
use Civi\Lughauth\Features\Access\UserPersonalApiKey\Application\Usecase\Delete\UserPersonalApiKeyDeleteUsecase;
use Civi\Lughauth\Features\Access\UserPersonalApiKey\Application\Usecase\Retrieve\UserPersonalApiKeyRetrieveUsecase;
use Civi\Lughauth\Features\Access\UserPersonalApiKey\Application\Usecase\Revoke\UserPersonalApiKeyRevokeUsecase;
use Civi\Lughauth\Shared\Exception\NotFoundException;
use Civi\Lughauth\Shared\Observability\LoggerAwareTrait;
use Civi\Lughauth\Shared\Observability\TracerAwareTrait;

class UserPersonalApiKeyAllowController
{
    use LoggerAwareTrait;
    use TracerAwareTrait;

    public function __construct(
        private readonly UserPersonalApiKeyCreateUsecase $createUsecase,
        private readonly UserPersonalApiKeyListUsecase $listUsecase,
        private readonly UserPersonalApiKeyUpdateUsecase $updateUsecase,
        private readonly UserPersonalApiKeyDeleteUsecase $deleteUsecase,
        private readonly UserPersonalApiKeyRetrieveUsecase $retrieveUsecase,
        private readonly UserPersonalApiKeyRevokeUsecase $revokeUsecase,
    ) {
    }
    #[OA\Get(
        path: "/api/me/acl/access/me/api-keys",
        tags: ["User personal api key access control"],
        description:"Allows",
        responses: [
        new OA\Response(response: 200, description: "Ok"),
    ]
    )
    ]
    public function genericAllow(ServerRequestInterface $request, ResponseInterface $response, array $args): ResponseInterface
    {
        $this->logDebug("Check generic allow for User personal api key");
        $span = $this->startSpan("Generic allow for User personal api key");
        try {
            $value = [
              'allows' => [
                $this->createUsecase->allowCreate(),
                $this->listUsecase->allowList(),
                $this->updateUsecase->allowUpdate(),
              $this->deleteUsecase->allowDelete(),
              $this->retrieveUsecase->allowRetrieve(),
              $this->revokeUsecase->allowRevoke(),
              ],
              'fields' => [
                'noEditables' => $this->updateUsecase->fixedFields(),
                'noVisibles' => $this->retrieveUsecase->hiddenFields()
              ]
            ];
            $encoded = json_encode($value);
            $response->getBody()->write($encoded === false ? '' : $encoded);
            return $response->withStatus(200)
                  ->withHeader('Content-Type', 'application/json');
        } catch (Throwable $ex) {
            $span->recordException($ex);
            throw $ex;
        } finally {
            $span->end();
        }
    }
    #[OA\Get(
        path: "/api/me/acl/access/me/api-keys/{uid}",
        tags: ["User personal api key access control"],
        description:"Allows",
        parameters: [
        new OA\PathParameter(name: "uid", required: true, schema: new OA\Schema(type: "string")),
    ],
        responses: [
        new OA\Response(response: 200, description: "Ok"),
        new OA\Response(response: 404, description: "Not found"),
    ]
    )
    ]
    public function contextualAllow(ServerRequestInterface $request, ResponseInterface $response, array $args): ResponseInterface
    {
        $this->logDebug("Check specific allow for User personal api key");
        $span = $this->startSpan("Specific allow for User personal api key");
        try {
            if (!isset($args['uid'])) {
                throw new NotFoundException('-');
            }
            $ref = new UserPersonalApiKeyRef(uid: $args['uid']);
            $value = [
              'allows' => [
                $this->updateUsecase->allowUpdate($ref),
              $this->deleteUsecase->allowDelete($ref),
              $this->retrieveUsecase->allowRetrieve($ref),
              $this->revokeUsecase->allowRevoke($ref),
              ],
              'fields' => [
                'noEditables' => $this->updateUsecase->fixedFields($ref),
                'noVisibles' => $this->retrieveUsecase->hiddenFields($ref)
              ]
            ];
            $encoded = json_encode($value);
            $response->getBody()->write($encoded === false ? '' : $encoded);
            return $response->withStatus(200)
                  ->withHeader('Content-Type', 'application/json');
        } catch (Throwable $ex) {
            $span->recordException($ex);
            throw $ex;
        } finally {
            $span->end();
        }
    }
}
